### ISSUE TITLE
Edit Mapfiles / Map Source File

### ISSUE THREAD

**Issue by zeug-it** [marlon360/rki-covid-api#100]
Hi, 
great work! we would like to integrate your API in a local Recreation site and add a map only for the region. How to Edit the map .json file. Its easy to add only the needed regions and towns, but what tool /source did you use to edit the viewbox and dimensions. I would love to have a map only for our region in fullsize.
I already copyied all needed areas to a new file and got the map, but it is small and has a lot of space around.

Many thanks,
Martin

**Comment by marlon360** [comment]
Hi @zeug-it 

In the `district.json` you can set the `width`, `height` and `viewbox`. You have to play around with the numbers to find the best values for your selection.

**Comment by zeug-it** [comment]
Yes, I did this. Worked great!

**Comment by marlon360** [comment]
Awesome!
