### ISSUE TITLE
R value for states/districts

### ISSUE THREAD

**Issue by Akeel1994** [marlon360/rki-covid-api#103]
Is it possible to get the R value for the states and districts, too? I think it can be an interesting indicator for the development of the mutants

**Comment by Rubber1Duck** [comment]
RKI is not providing R values for states/districts ............ i think.
In the actual data base there is only a R value for germany! i Don't know if there is another excel sheet with R value calculation for states/destricts.
maybe Marlon knows ......

**Comment by marlon360** [comment]
I haven't found any R values for states or districts.

This websites calculates some values: https://rtlive.de
