### ISSUE TITLE
Spike in district incidences as of today

### ISSUE THREAD

**Issue by flodt** [marlon360/rki-covid-api#106]
This Is likely an external problem:
I am seeing a spike in the week incidences of various districts on my dashboard with incidences that do not occur in the officially updated Excel table published by the RKI. The official dashboard is also currently not displaying any data.
However, these spikes seem to come directly from the RKI, as they are present in both this API's data as well as the RKI's API directly.

Has anybody experienced something similar today?
Is it intentional that the district incidence history API is still displaying the incidence state as of yesterday?

Thank you!

**Comment by marlon360** [comment]
While the RKI is updating their data, we often see some wrong numbers.
Here you can view the status of the update: https://experience.arcgis.com/experience/478220a4c454480e823b17327b2bf1d4

**Comment by flodt** [comment]
Is there any way to check whether the data is currently being updated programmatically?

**Comment by flodt** [comment]
**Update**: this was addressed here: https://www.br.de/nachrichten/deutschland-welt/verwirrung-um-inzidenzwerte-rki-bestaetigt-datenpanne,SQ6SRTA
