### ISSUE TITLE
Long Map Loading Time

### ISSUE THREAD

**Issue by antonstech** [marlon360/rki-covid-api#109]
Hello, i am currently programming a Discordbot using the API But the Time to get the Image for the Map needs so long that discord.py aborts it.
![image](https://user-images.githubusercontent.com/58666027/109471847-a3077480-7a71-11eb-9745-76357c75c5b5.png)
Here is a example of the Loading Time
Can you fix this or are your Server just overloaded?

**Comment by marlon360** [comment]
The server is on 99% usage. Some people are calling the API every second.
I will try to block those spammers to improve the performance.

**Comment by Rubber1Duck** [comment]
> ............................  Some people are calling the API every second. ......................

shaking head, .....................  why are they doing that ??????????????

**Comment by antonstech** [comment]
> The server is on 99% usage. Some people are calling the API every second.
> I will try to block those spammers to improve the performance.

@marlon360 why arent you just making a System where everyone has his own API-Key with limited usage?

**Comment by Rubber1Duck** [comment]
This Issue should be done ............... or not?

**Comment by sinjs** [comment]
Host the server by yourself.

**Comment by antonstech** [comment]
@sinmineryt I tryed but it somehow didnt work

**Comment by sinjs** [comment]
> 
> 
> @sinmineryt I tryed but it somehow didnt work

@antonstech What is the error you are getting?

**Comment by antonstech** [comment]
@sinmineryt I can set it up again later and send you the error

**Comment by sinjs** [comment]
> 
> 
> @sinmineryt I can set it up again later and send you the error

It's better when we do that on Discord, add me: sin.js#6969

**Comment by marlon360** [comment]
@antonstech and @sinmineryt Feel free to use the Discussion feature to share your knowledge with the community.
https://github.com/marlon360/rki-covid-api/discussions

You can start a new discussion under Q&A for your problem.

**Comment by antonstech** [comment]
@sinmineryt I sent you a request
