### ISSUE TITLE
Current incidence value is equal to that of the previous day

### ISSUE THREAD

**Issue by mindbreaker** [marlon360/rki-covid-api#111]
I have now checked the values and the incidence value of the previous day returns the same value as that of the current day.

Here is an example:

https://api.corona-zahlen.org/districts/09172/

`"weekIncidence":120.83565407017909`

https://api.corona-zahlen.org/districts/09172/history/incidence/5

`{"weekIncidence":120.83565407017909,"date":"2021-03-02T00:00:00.000Z"}`

I have tried other counties as well.

**Comment by Rubber1Duck** [comment]
> 
> 
> I have now checked the values and the incidence value of the previous day returns the same value as that of the current day.
> 
> Here is an example:
> 
> https://api.corona-zahlen.org/districts/09172/
> 
> `"weekIncidence":120.83565407017909`

This is not the value from today! This is the value from yesterday! the value from today you will get tomorrow!

> 
> https://api.corona-zahlen.org/districts/09172/history/incidence/5
> 
> `{"weekIncidence":120.83565407017909,"date":"2021-03-02T00:00:00.000Z"}`
> 
> I have tried other counties as well.

The values witch are **_published_** today are always the values from yesterday!

**Comment by mindbreaker** [comment]
Sorry, my mistake.

**Comment by Rubber1Duck** [comment]
you are welcome ............. no problem
