### ISSUE TITLE
Problems with the parser because of new state Bund

### ISSUE THREAD

**Issue by Akeel1994** [marlon360/rki-covid-api#113]
Hey,

our app has problems parsing the json because of the new state "Bund" in vaccinations. This state has null and string values which are not matching with the actual data types of the fields. Is there any possibility to fit it? 

Edit: can you just write 0 instead of "-" or null into the fields? It would be better to parse and fix the problem.

**Comment by Akeel1994** [comment]
Hey @marlon360, 
can you fix this problem? We are not able to parse the vaccination data since friday. 

Edit: we have found a workaround.

**Comment by kaolick** [comment]
I still have the problem. I think it not a good idea that everybody develops his own workaround. 

Can you please still fix this issue?

Thanks in advance

**Comment by marlon360** [comment]
Fixed with fd771625dec2678ef000d94fe84a90aa5eaeb68d
Should be online soon!
Thanks @Akeel1994 for pointing out the issue. And thanks @kaolick for reopening the issue.
