### ISSUE TITLE
Request limit is a problem

### ISSUE THREAD

**Issue by Akeel1994** [marlon360/rki-covid-api#114]
Hey,

I have noticed that we are having problems with the normal app usage because of the new limitations. 
I guess 15 requests per minute are too low. 
The app gets states, districts, general, vaccination and map data. You can also click on the cards of you favorites to get the history data for favorites (we are calling 4 endpoints to get the history data e.g. incidence for last 31 days. With 3 or more cards you are really fast to the limit and data is not loading anymore for the history. We are already saving a lot of data in a database so the user don't have to fetch the states, general, district and vaccination data with every app start over the day. 
I can understand that a limitation is important to keep the server load low. So I want to suggest another solution. I think it would make more sense to not limit the requests per minute. You could instead say that 1.000 requests per day are allowed. The data is not changing so often, so that would be a better solution and apps like our app wouldn't have the problem anymore that you get really fast to the limit.

**Comment by mkay96** [comment]
Same issue, daily request limit could be more effective

**Comment by marlon360** [comment]
Hey!
The problem is not the daily number of requests. The server struggles with many simultaneous requests.
With this limit I try to motivate the people to add a short delay between requests rather than requesting all endpoints in a short amount of time.

You can always host the server yourself if you want to use it without limitations.

Let me know if you are interested in a paid tier where you get an API key which has no limitations.

**Comment by Akeel1994** [comment]
> Hey!
> The problem is not the daily number of requests. The server struggles with many simultaneous requests.
> With this limit I try to motivate the people to add a short delay between requests rather than requesting all endpoints in a short amount of time.
> 
> You can always host the server yourself if you want to use it without limitations.
> 
> Let me know if you are interested in a paid tier where you get an API key which has no limitations.

Yeah, I can really understand that. But in my opinion the current solution is not perfect yet. 
We have designed the app already to make only one fetch for the endpoints states, districts, vaccination and general per day. So i think that not the users of our app are the problem overloading the servers. 
15 requests per minute is a little bit to less to use the app normally. Maybe you can increase it to 30 or so? Then there would be enough "Puffer" for the app users.

**Comment by Akeel1994** [comment]
Edit: Wir werden versuchen die API selbst zu hosten, dann sollte das kein Problem mehr sein :)
