### ISSUE TITLE
API used on project https://www.frankenjura.com (project)

### ISSUE THREAD

**Issue by zeug-it** [marlon360/rki-covid-api#115]
Hi its a great api, I used a self hosted version to integrate on https://www.frankenjura.com/frankenjura/corona

**Comment by mindbreaker** [comment]
@zeug-it i think you have to make a pull request to add this.

**Comment by Rubber1Duck** [comment]
hmmm in the docs are written:

```
Project Showcase (projects using this API)

Add your project by opening an issue with your project details!
```
so this should be enough .......................
