### ISSUE TITLE
Fehler bei den Impfzahlen 

### ISSUE THREAD

**Issue by HuiiBuh** [marlon360/rki-covid-api#118]
Der Impf Endpunkt liefert folgende Daten, wenn man ihn aufruft. 
```json
{
  "administeredVaccinations":8716654,
  "vaccinated":597855
} 
```

`administeredVaccinations` soll alle bisher verimpften Dosen enthalten.   
`vaccinated` sind laut Dokumentation alle Personen, die zweimal geimpft wurden. Rein mathematisch sind die Zahlen allerdings ja nicht möglich, weil die fünf Millionen ja zwei Dosen bekommen haben müssten, was bei neuen Millionen verimpften Dosen garnicht möglich ist.

**Comment by marlon360** [comment]
Hey @HuiiBuh 

In der Doku heißt es:
> `administeredVaccinations` The total number of administered vaccine doses (sum of first and second vaccination)
> `vaccinated` Number of people who got the first of two vaccinations.

Also `administeredVaccinations` sind alle verimpften Dosen.
Und `vaccinated ` sind die Anzahl der Menschen, die mindestens eine Impfung bekommen haben.

Die Zahlen stimmen also.

**Comment by HuiiBuh** [comment]
Sorry I missed the _of_...
