### ISSUE TITLE
error on missing slash in the states path

### ISSUE THREAD

**Issue by v-braun** [marlon360/rki-covid-api#119]
Get since today an error if the states endpoind miss a slash at the end:

**does not work**
```
https://api.corona-zahlen.org/states
```

**work**
```
https://api.corona-zahlen.org/states/
```

For the districts endpoint both versions work ( `/districts` AND `/districts/ ` )

No Priority because simple to fix.
Question: is it possible to tag the Docker Image on docker.io with a continues build number? 
I am hosting this API and set the :V2 tag, unfortunatley my app crashed on a new deployment because the issue above was for me a broken change :(

**Comment by v-braun** [comment]
Update:
it is really confusing, I think it is not related to the slash!
Maybe the slash caused a cache busting (or forced to not use the cache)?

I had the same issue now with the `/districts/` endpoint (with and without shlash):

![image](https://user-images.githubusercontent.com/4738210/111039247-4fac0380-842d-11eb-9a7e-f45b35c24ee0.png)

**Comment by Rubber1Duck** [comment]
As the message says, this was a RKI Issue!

**Comment by v-braun** [comment]
Is the RKI response cached if an error happen?

Because `/states` doesnt worked (returned the above error) and `/states/` worked.
After a while both worked again fine (1 hour)

**Comment by Sarcasmonaut** [comment]
yeah, I do think the messages get cached, even if an error is thrown.
I managed to reproduce this locally by replacing the implementation of an endpoint with a simple `throw new Error('...')`
![image](https://user-images.githubusercontent.com/25012926/111269414-e693de00-862e-11eb-88f7-9c5f149f67e4.png)

After reverting to the regular implementation, the error response remains until the cache is cleared.
Expiry currently is set to 1800 seconds, hence after 30 minutes you get another try.

My suggestion would be to configure a different expiry for errors: 
https://www.npmjs.com/package/express-redis-cache#expiration
![image](https://user-images.githubusercontent.com/25012926/111270826-a5043280-8630-11eb-9528-aa3e90ccc913.png)

However, the errors are also returned with a statusCode of 200, check with the current issue on #122: 
![image](https://user-images.githubusercontent.com/25012926/111271668-cd406100-8631-11eb-8db0-240e994145be.png)

**Comment by v-braun** [comment]
I see!
Than the title of this issue makes absolute no sense.
The slash at the end caused a cache busting and the endpoint worked because RKI was "healthy" again.

I think this could be closed than.
