### ISSUE TITLE
Vaccinations history has decimal values 

### ISSUE THREAD

**Issue by gregorsarnow** [marlon360/rki-covid-api#121]
The endpoint "GET https://api.corona-zahlen.org/vaccinations/history" returns a decimal value for the number of second vaccinations on the days 03/07 and 03/08 as you can see here:
    
            {
                "date": "2021-03-07T00:00:00.000Z",
                "vaccinated": 114893,
                "firstVaccination": 114893,
                "secondVaccination": 34600.5
            },
            {
                "date": "2021-03-08T00:00:00.000Z",
                "vaccinated": 178973,
                "firstVaccination": 178973,
                "secondVaccination": 51629.5
            }

The [RKI](https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Daten/Impfquoten-Tab.html) .xlsx-file includes the following:
07.03.2021 | 114.893 | 34.601 | 149.494
-- | -- | -- | --
08.03.2021 | 178.973 | 51.630 | 230.603

So it seems there is a bug in the API.
Quick fix is to just to round up the values but would be better to have a look in to it.

**Comment by Rubber1Duck** [comment]
> The [RKI](https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Daten/Impfquoten-Tab.html) .xlsx-file includes the following:
> 07.03.2021 	114.893 	34.601 	149.494
> 08.03.2021 	178.973 	51.630 	230.603
> 
> So it seems there is a bug in the API.
> Quick fix is to just to round up the values but would be better to have a look in to it.

You are wrong!
The cells in the RKI .xlsx file are reduced to 0 decimal values!

![RKI1](https://user-images.githubusercontent.com/6493772/111213832-7c991b80-85d1-11eb-81be-b6f7febd45d4.png)

if you extend the values from 7.3. and 8.3. to 1 decimal value this shows up

![RKI2](https://user-images.githubusercontent.com/6493772/111214159-e6b1c080-85d1-11eb-948b-d7cde63d01bf.png)

so what the API reads out is exactly what RKI transmit! Okay, ,5 vacciation makes no sence but there is no bug in the API!

**Comment by gregorsarnow** [comment]
Well, my fault, sorry. 
Very weird. Didn't expect them to record .5 vaccinations 😂

Now the question is wether it's 34.601 or 34.600 vaccinations for 03/07? => Round up or cut?

**Comment by Rubber1Duck** [comment]
a few weeks ago there was the problem too. after a few days RKI corrected the values .................. 
if round up or cut , i think thats make not a big difference! Excel rounds it up if the number of decimal values are set to 0!
and that is what RKI published!

**Comment by Rubber1Duck** [comment]
The .5 Values are still there. I have written a PR, Marlon have to merge it if he agreed.

**Comment by Rubber1Duck** [comment]
In the meenwhile RKI corrected the data! I think the Issue can be closed!
