### ISSUE TITLE
Current incidence value not in history values

### ISSUE THREAD

**Issue by mindbreaker** [marlon360/rki-covid-api#123]
The current, reported incidence value is no longer present in the history query.

https://api.corona-zahlen.org/districts/09172/history/incidence/5
https://api.corona-zahlen.org/districts/09172/

**Comment by marlon360** [comment]
Interesting, it seems to happen only for certain districts.

This works: https://api.corona-zahlen.org/districts/02000/history/incidence/5

**Comment by Rubber1Duck** [comment]
I meen thats similuar to #82

**Comment by mindbreaker** [comment]
OK. Today the value is missing again. I checkt the issue #82 from @Rubber1Duck and the current incidence is in the history api call.

**Comment by Rubber1Duck** [comment]
it is complicated :-) there are 6 new cases, but from this 6 cases 1 is for 20.03.2021 und  5 for 21.03.2021 witch you can see here (lower right corner)
![09172](https://user-images.githubusercontent.com/6493772/112136093-cf289800-8bce-11eb-92ce-c31979c64688.png)

therefor at 22.3.2021 (yesterday) there is no new cases so the history for 22.3.2021 is not shown in https://api.corona-zahlen.org/districts/09172/history/incidence/5

if you have the possibility, set this day to "0" (RKI do so to calculate the incidence!)

thats exactly what i want to descibe in my issue!

it is possilbe to patch this but my TS/Javascript Experience is not good enough and Marlon seems busy at the moment! and i dont find a good explanation to debug ts code. Anyone any hint to a description for ts code debuging? in german it would be great.

by the way it is not a good idea to set this to "0" without checking if all data is updated! so a additional Field "Datenstand" is needed in all nessesary requests to RKI API!

**Comment by leonfroschauer** [comment]
Same here, the incidence value for munich is today at 98.30039360582553 (https://api.corona-zahlen.org/districts/09162), but in the frozen history, the last data is from yesterday. But with the incidence history I am completly done, because, there is the incidence value from today labled as yesteraday:

```json
// https://api.corona-zahlen.org/districts/09162/history/incidence/5

{
  "data": {
    "09162": {
      "ags": "09162",
      "name": "München",
      "history": [
        {
          "weekIncidence": 135.6262455987161,
          "date": "2021-05-01T00:00:00.000Z"
        },
        {
          "weekIncidence": 132.32486157768426,
          "date": "2021-05-02T00:00:00.000Z"
        },
        {
          "weekIncidence": 122.7575854351022,
          "date": "2021-05-03T00:00:00.000Z"
        },
        {
          "weekIncidence": 110.96692821713137,
          "date": "2021-05-04T00:00:00.000Z"
        },
        {
          "weekIncidence": 98.30039360582553,
          "date": "2021-05-05T00:00:00.000Z"
        }
      ]
    }
  },
  "meta": {
    "source": "Robert Koch-Institut",
    "contact": "Marlon Lueckert (m.lueckert@me.com)",
    "info": "https://github.com/marlon360/rki-covid-api",
    "lastUpdate": "2021-05-05T00:00:00.000Z",
    "lastCheckedForUpdate": "2021-05-06T06:35:21.750Z"
  }
}
```

```json
// https://api.corona-zahlen.org/districts/09162/history/frozen-incidence/5

{
  "data": {
    "09162": {
      "ags": "09162",
      "name": "SK München",
      "history": [
        {
          "weekIncidence": 126.6653461131,
          "date": "2021-05-02T00:00:00.000Z"
        },
        {
          "weekIncidence": 126.3958453766,
          "date": "2021-05-03T00:00:00.000Z"
        },
        {
          "weekIncidence": 112.3818070833,
          "date": "2021-05-04T00:00:00.000Z"
        },
        {
          "weekIncidence": 98.9741454469,
          "date": "2021-05-05T00:00:00.000Z"
        }
      ]
    }
  },
  "meta": {
    "source": "Robert Koch-Institut",
    "contact": "Marlon Lueckert (m.lueckert@me.com)",
    "info": "https://github.com/marlon360/rki-covid-api",
    "lastUpdate": "2021-05-05T06:25:58.000Z",
    "lastCheckedForUpdate": "2021-05-06T06:37:44.831Z"
  }
}
```
In addition, there is not enough value in the view of one value! Because if I call 5 values, I only get 4, etc.
```
// https://api.corona-zahlen.org/districts/09162

{
  "data": {
    "09162": {
      "ags": "09162",
      "name": "München",
      "county": "SK München",
      "state": "Bayern",
      "population": 1484226,
      "cases": 69269,
      "deaths": 1193,
      "casesPerWeek": 1459,
      "deathsPerWeek": 3,
      "stateAbbreviation": "BY",
      "recovered": 60552,
      "weekIncidence": 98.30039360582553,
      "casesPer100k": 4667.011627609272,
      "delta": {
        "cases": 374,
        "deaths": 8,
        "recovered": 363
      }
    }
  },
  "meta": {
    "source": "Robert Koch-Institut",
    "contact": "Marlon Lueckert (m.lueckert@me.com)",
    "info": "https://github.com/marlon360/rki-covid-api",
    "lastUpdate": "2021-05-06T00:00:00.000Z",
    "lastCheckedForUpdate": "2021-05-06T06:20:07.465Z"
  }
}
```

**Comment by Rubber1Duck** [comment]
> Same here, the incidence value for munich is today at 98.30039360582553 (https://api.corona-zahlen.org/districts/09162), but in the frozen history, the last data is from yesterday. But with the incidence history I am completly done, because, there is the incidence value from today labled as yesteraday:

Wow, that sounds very angry ............. 
it is never possible to give values for today! all values that are today published by RKI are values from yesterday, because today is running ....... they say today that we have yesterday blablabla new cases (or whatelse)! how many new cases we have today the RKI can only say at 23:59:59 o'clock.....
but you are right i also think that the dates in frozen-history should be 1 less
