### ISSUE TITLE
Germany is broken

### ISSUE THREAD

**Issue by sinjs** [marlon360/rki-covid-api#124]
The endpoint `/germany` is broken. 

#122 mentions that too, the same error is happening in the self hosted server.

It's definetly a parse error, and already mentioned in #122. I'll try finding the issue and open a pr.

**Comment by sinjs** [comment]
Can't really find a fix for the issue, the RKI R-Wert list breaks the "ä" but only some of them:

![does not work](https://user-images.githubusercontent.com/50749166/111278760-37f59a80-863a-11eb-8fbc-ac2ed1a32b93.png)

here it works:
![works](https://user-images.githubusercontent.com/50749166/111278791-42b02f80-863a-11eb-9d82-35ebc09bc395.png)

using `Buffer.from(..., 'utf-8')` does not help.

**Comment by marlon360** [comment]
Fixed with 7969b65c3c0e73a5618c551ca28c7c739e7d62bb
