### ISSUE TITLE
Different current values in history and current day

### ISSUE THREAD

**Issue by ChristophKrause** [marlon360/rki-covid-api#125]
This has been seen for a month, but has been tested today.

reproduction:
https://api.corona-zahlen.org/germany
"cases":5480,"deaths":238,"recovered":9106
vs
https://api.corona-zahlen.org/germany/history/cases
"cases":3758,"date":"2021-03-15T00:00:00.000Z"
https://api.corona-zahlen.org/germany/history/deaths
"deaths":4,"date":"2021-03-15T00:00:00.000Z"
https://api.corona-zahlen.org/germany/history/recovered
recovered":127,"date":"2021-03-12T00:00:00.000Z"

The first values can be confirmed as shown on the RKI Dashboard.
I guess the other values are from somewhere else.
I have no idea, why there is such a big difference.
I suggest to add two more datasources for the german overall values.
Deaths and infected can be retrieved from Worldometer and JHU (maybe recovered too).

**Comment by marlon360** [comment]
Hi @ChristophKrause 

This API only covers data from the RKI, because this is the data that is relevant for political decisions or rules.
The history is calculated correctly, see #64

**Comment by ChristophKrause** [comment]
Thanks, but I still wonder why the current day is inconsistent to these two calls. 
As far as I understood this is a fault from the RKI
