### ISSUE TITLE
r0 value not updated

### ISSUE THREAD

**Issue by hajo62** [marlon360/rki-covid-api#139]
r0 value 5 days old.
See screenshot taken mar 26:
<img width="385" alt="grafik" src="https://user-images.githubusercontent.com/15800980/112600670-cbd11e80-8e11-11eb-9374-b62ca09251b4.png">

**Comment by Rubber1Duck** [comment]
The r-Value witch is published by this API is the value witch RKI called "Punktschätzer der 4-Tage R-Wert".
As you can see in [https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Projekte_RKI/Nowcasting_Zahlen.xlsx?__blob=publicationFile](https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Projekte_RKI/Nowcasting_Zahlen.xlsx?__blob=publicationFile) Data from 21.03.2021 is the newest Value witch is publisched by RKI!
![r-Value](https://user-images.githubusercontent.com/6493772/112613727-b1527180-8e20-11eb-9194-691dc0a48657.png)

**Comment by hajo62** [comment]
Ok.
I thought it where broken, because I allready got todays value yesterday evening

**Comment by Rubber1Duck** [comment]
> 
> 
> Ok.
> I thought it where broken, because I allready got todays value yesterday evening

wow.................. you got todays values yesterday in the evening??????????? thats realy curious because that could not be! (as i described above)
if the next time this happend, please make some screenshots an have a look in the link to the RKI Excelsheet to verify what is in there!

**Comment by hajo62** [comment]
Here a screenshot of that what can't be.
That's the value history from my Home Assistant: As you can see, it fetched the 0.96 at 21:29:10.

<img width="462" alt="grafik" src="https://user-images.githubusercontent.com/15800980/112616375-f2985080-8e23-11eb-812c-c31c70565b1e.png">

**Comment by Rubber1Duck** [comment]
sorry i missunderstoud you, thougth you get a r-Value dated with the date from today from the API.
The value you get yesterday, was the value from 21.03.2021 witch is the newest one RKI published.
i dont know when RKI is updating the excel sheet witch is datasource for this API!

**Comment by hajo62** [comment]
okay. My mistake.
From my point of view a bit strange that RKI publishes i.e. at 26.03. data for 22.03.. (although they are calculated with a 4 day interval)
