### ISSUE TITLE
Getting data from different dates

### ISSUE THREAD

**Issue by lvlanson** [marlon360/rki-covid-api#14]
Is there a possibility to get the data from different dates? Is there any API for that?

**Comment by marlon360** [comment]
Hi @lvlanson!
There is an API for that here: https://npgeo-corona-npgeo-de.hub.arcgis.com/datasets/dd4580c810204019a7b8eb3e0b329dd6_0

At the moment this API is not included in this repository.

Feel free to open a PR to add this functionality.

**Comment by lvlanson** [comment]
Thank you! That is good and useful information <3

**Comment by JaHollYT** [comment]
> Thank you! That is good and useful information <3

Have you figured out how to use the link above to get the data for a period from the past?
I could need some help :)

**Comment by lvlanson** [comment]
Hey @JaHollYT ,

you can essentially load a big dataset via the "APIs" Button and get the JSON file.
its 230mb of data to this point. I haven't analyzed the data yet.

https://opendata.arcgis.com/datasets/dd4580c810204019a7b8eb3e0b329dd6_0.geojson

You could also get in touch with me via a messenger, if you'd like.
