### ISSUE TITLE
-1 deaths in Erlangen

### ISSUE THREAD

**Issue by markxoe** [marlon360/rki-covid-api#140]
If you look at the data from the endpoint [here](https://api.corona-zahlen.org/districts)

You see this:

```
{"ags":"09562","name":"Erlangen","county":"SK Erlangen","state":"Bayern","population":112528,"cases":3095,"deaths":89,"casesPerWeek":94,"deathsPerWeek":0,"stateAbbreviation":"BY","recovered":2858,"weekIncidence":83.53476468079056,"casesPer100k":2750.4265605004975,"delta":{"cases":39,"deaths":-1,"recovered":8}}
```

Taking a closer look at `"delta":{"cases":39,"deaths":-1,"recovered":8}}` with negative deaths!?

Is there a reason for that?

**Comment by Rubber1Duck** [comment]
Thats exactly what RKI is publishing! So you have to ask RKI what this meens!
The Healthdepartments of the districts are transmitting the values to RKI every day, and maybe they makes some Errors at some time ........
So thats not a Issue of this API!

**Comment by markxoe** [comment]
Okay thanks 👍🏻
