### ISSUE TITLE
Project: COVID-19 Dashboard

### ISSUE THREAD

**Issue by beyerleinf** [marlon360/rki-covid-api#143]
First of all: Thanks for the great API!

I've built a dashboard to display current and historical data: [https://covid.beyerleinf.de](https://covid.beyerleinf.de)

**Comment by Rubber1Duck** [comment]
Added to PR #141

**Comment by beyerleinf** [comment]
Thanks, @Rubber1Duck! :)

**Comment by ChristophKrause** [comment]
Thanks, @Rubber1Duck! :)

You should think about showing the increase of infections in% too. This helps to get a feeling about the current situation.
The deaths should have another scale in the graph and a switch to et a X-Offset for setting the deaths to relate them to the infections

**Comment by beyerleinf** [comment]
@ChristophKrause Thanks for the feedback! :)

What should that percentage relate to? %-increase of total infections?

You're right about the deaths. They're pretty pointless in the chart, currently. Need to look into what I could do about that with my chart library.

**Comment by ChristophKrause** [comment]
@beyerleinf 
I would relate the percentage to the value 7 days ago 

Deaths: Maybe you could offer a field to apply a optional factor to the deaths
