### ISSUE TITLE
Wordpress-Plugin für Corona-Zahlen in Deutschland

### ISSUE THREAD

**Issue by MarcusCJHartmann** [marlon360/rki-covid-api#147]
Ein Wordpress-Plugin, das die Coronazahlen der API in Deutschland in einem Overlay auf Wordpress-Seiten bringt.
Jede Wordpresseite, auf der das Plugin läuft, führt dabei einen eigenen Cache in der Datenbank, um die Anfragemenge auf die API so gering wie möglich zu halten. Es wird höchstens einmal am Tag pro Website eine Anfrage an die API durchgeführt.

Ein Gestaltungsentwurf könnte wie folgt aussehen:
![Entwurf](https://user-images.githubusercontent.com/12703253/113425259-dbcc9d80-93d1-11eb-89e3-d55b5178fd13.jpg)

Mein Ziel ist es, das Plugin in das Wordpress-Pluginverzeichnis zu bringen.

Liebe Grüße

Marcus C J Hartmann

**Comment by beyerleinf** [comment]
Sehr cool!

**Comment by MarcusCJHartmann** [comment]
Das Plugin steht nun und hat das erste Review fürs Wordpress Repo erhalten. Ich arbeite die Beanstandungen und Änderungswünsche nun ein. Alles faire Punkte, die die Qualität und Kompatibilität mit allen möglichen Umgebungen sicherstellen.
Enthalten sind in dem Plugin:

- Overlay (siehe Screenshot) mit den Optionen an/aus, links-/rechtsseitig
- Widget für Sidebars und Footer
-  Ein Shortcode
- Autoinsert, der den Shortcode automatisch in Posts/Pages am Anfang/Ende/nach x Absätzen einfügt

Alle Varianten können außerdem mit eigenem CSS versehen werden.

**Comment by marlon360** [comment]
https://de.wordpress.org/plugins/corona-zahlen-deutschland-cng/
