### ISSUE TITLE
What are Vaccination indications?

### ISSUE THREAD

**Issue by shellixa** [marlon360/rki-covid-api#151]
What are these Vacc. indications of "age","job","medical" and "nursingHome"... what do they say?

**Comment by Rubber1Duck** [comment]
thats the reason why they are vaccinated!
![indikation](https://user-images.githubusercontent.com/6493772/113716216-a59d5f80-96ea-11eb-8325-3bc6370c0119.png)

**Comment by shellixa** [comment]
thanks!
