### ISSUE TITLE
Structure of vaccination xlsx file is changed

### ISSUE THREAD

**Issue by Rubber1Duck** [marlon360/rki-covid-api#153]
The strcture of source vaccination xlsx file is changed. The parser must be rewitten!
![vaccination](https://user-images.githubusercontent.com/6493772/114023494-3bfc8d00-9873-11eb-958e-83f96767d6ea.png)

**Comment by marlon360** [comment]
Oh no..
They changed everything. They also dropped the "Indikatoren".

We need to change the API and this will break some applications.

I have very limited time at the moment and I am happy if someone else can pick up the work for this.

**Comment by Rubber1Duck** [comment]
Are you able to provide the interface definition, just as you imagine it?

`export interface VaccinationCoverage {`
etc.

i think the rest i am able to provide

**Comment by HappyFr1tz** [comment]
> Oh no..
> They changed everything. They also dropped the "Indikatoren".
> 
> We need to change the API and this will break some applications.
> 
> I have very limited time at the moment and I am happy if someone else can pick up the work for this.

How long do you think it would take you to adapt the API to it? I use this API every day to query the data.

**Comment by Akeel1994** [comment]
Maybe they will add the Indikatoren again.

**Comment by Rubber1Duck** [comment]
I am working on a solution ..... maybe today (Friday) PR is ready!

**Comment by fe-lix-werner** [comment]
There is also data available from impfdashboard https://impfdashboard.de/daten Less data but probably more consistant due to tsv file format

**Comment by Rubber1Duck** [comment]
> How long do you think it would take you to adapt the API to it? I use this API every day to query the data.

Hopefully @marlon360 will merge the PR soon ....

**Comment by hajo62** [comment]
Well done. Thanks a lot!
