### ISSUE TITLE
/vaccinations broken

### ISSUE THREAD

**Issue by grenzbotin** [marlon360/rki-covid-api#155]
Hello,

today we noticed a problem with the endpoint:
`https://api.corona-zahlen.org/vaccinations`

The response:
`{"error":{"message":"An error occurred.","details":"Cannot read property 'includes' of undefined","stack":"TypeError: Cannot read property 'includes' of undefined\n at Object. (/usr/src/app/src/data-requests/vaccination.ts:205:50)\n at Generator.next ()\n at fulfilled (/usr/src/app/dist/data-requests/vaccination.js:5:58)\n at runMicrotasks ()\n at processTicksAndRejections (internal/process/task_queues.js:97:5)"}}`

Thanks for providing the endpoints. =)

**Comment by gregorsarnow** [comment]
Duplicate of #153

**Comment by wooligan** [comment]
I guess the problem is that the RKI changed their spreadsheet.
It would be great if you could fix it, @marlon360 
Thank you very much for your effort! Great API!

**Comment by JonathanN1203** [comment]
@wooligan there is another issue about that. Maybe it would be fixed today. Have a look at that https://github.com/marlon360/rki-covid-api/issues/153

**Comment by Rubber1Duck** [comment]
Patch is ready, and waiting for merge ....
patched example
![vaccination_example](https://user-images.githubusercontent.com/6493772/114209378-d5549d80-995e-11eb-8f93-c0e0b818f798.png)

**Comment by Rubber1Duck** [comment]
after some bug fixes it will look like so (still waiting for merge)
![vaccination_example3](https://user-images.githubusercontent.com/6493772/114229087-a991e180-9977-11eb-82d7-e1beeb842e83.png)

**Comment by Rubber1Duck** [comment]
patch is merged, this issue can be closed!

**Comment by marlon360** [comment]
Closed with #156

**Comment by Akeel1994** [comment]
> after some bug fixes it will look like so (still waiting for merge)
> 
> ![vaccination_example3](https://user-images.githubusercontent.com/6493772/114229087-a991e180-9977-11eb-82d7-e1beeb842e83.png)
> 
> 

Can you put 0 instead of null?

**Comment by marlon360** [comment]
`0` would be a false information. `null` indicates that the value is not available.
Unfortunately you have to handle `null` in your application.

**Comment by Akeel1994** [comment]
> `0` would be a false information. `null` indicates that the value is not available.
> Unfortunately you have to handle `null` in your application.

Yeah as seen from this perspective you're right.
