### ISSUE TITLE
"r"-"value" missing

### ISSUE THREAD

**Issue by stingrayx** [marlon360/rki-covid-api#157]
Hello,

when executing "GET https://api.corona-zahlen.org/germany" the value property of the r data structure is missing on my side. Can anyone confirm this behaviour? Is it a bug?

Thanks.

Best regards
Thomas

**Comment by Rubber1Duck** [comment]
RKI changed the header of the column :-)

**Comment by Rubber1Duck** [comment]
PR is written, waiting for merge
