### ISSUE TITLE
New cases

### ISSUE THREAD

**Issue by eloo** [marlon360/rki-covid-api#16]
Hi, i really like your api but would it be possible to get the new cases as well?

Thanks
eloo

**Comment by marlon360** [comment]
I am using this API as the data source: https://opendata.arcgis.com/datasets/dd4580c810204019a7b8eb3e0b329dd6_0.geojson

It is not possible to calculate the number of new cases from this data. Because every day the number of cases gets updated for the current date and even dates in the past.

Since this repository is a stateless API, I cannot calculate the difference to the last day.
A solution to this problem would be a database where I store the number of cases each day and compare it to the latest data.

**Comment by marlon360** [comment]
More information from the RKI Dashboard website:

> Wichtige Information
>  
> In Einklang mit den internationalen Standards der WHO und des ECDC wertet das RKI alle labordiagnostischen Nachweise von SARS-CoV-2 unabhängig vom Vorhandensein oder der Ausprägung der klinischen Symptomatik als COVID-19-Fälle. Unter COVID-19-Fällen werden somit sowohl akute SARS-CoV-2-Infektionen als auch COVID-19-Erkrankungen zusammengefasst.
>  
> Für die Gesamtzahl pro Bundesland/Landkreis werden die den Gesundheitsämtern nach Infektionsschutzgesetz gemeldeten Fälle verwendet, die dem RKI bis zum jeweiligen Tag um 0 Uhr übermittelt wurden.
> Für die Darstellung der neuübermittelten Fälle pro Tag wird das Meldedatum verwendet – das Datum, an dem das lokale Gesundheitsamt Kenntnis über den Fall erlangt und ihn elektronisch erfasst hat.
> Zwischen der Meldung durch die Ärzte und Labore an das Gesundheitsamt und der Übermittlung der Fälle an die zuständigen Landesbehörden und das RKI können einige Tage vergehen (Melde- und Übermittlungsverzug). Jeden Tag werden dem RKI neue Fälle übermittelt, die am gleichen Tag oder bereits an früheren Tagen an das Gesundheitsamt gemeldet worden sind. Diese Fälle werden in der Grafik Neue COVID-19-Fälle/Tag dann bei dem jeweiligen Datum ergänzt.
>  
> Der genaue Infektionszeitpunkt der gemeldeten Fälle kann in aller Regel nicht ermittelt werden. Das Meldedatum an das Gesundheitsamt spiegelt daher am besten den Zeitpunkt der Feststellung der Infektion (Diagnosedatum) und damit das aktuelle Infektionsgeschehen wider. Durch den Meldeverzug sind die Daten die letzten Tage in der Grafik  noch unvollständig und füllen sich mit den in den kommenden Tagen nachfolgend übermittelten Daten auf.  Aus dem Verlauf der übermittelten Daten allein lässt sich daher kein Trend zu den aktuell erfolgten Neuinfektionen ablesen. 
> Das Erkrankungsdatum ist der Tag, an dem der Patient nach eigener Angabe bzw. nach Angabe des behandelnden Arztes mit klinischen Symptomen erkrankt ist. Das Erkrankungsdatum kann wegen der sehr zeitigen Labortests auch nach dem Meldedatum liegen. Liegt dem Gesundheitsamt das Erkrankungsdatum nicht vor, so wird alternativ das Meldedatum genutzt.
>  
> Ausgehend vom Beginn der Erkrankung, bzw. wenn dieser nicht bekannt ist, vom Meldedatum, ergibt sich ein geschätztes Datum der Genesung für jeden Fall. Da im Einzelfall auch deutlich längere Erkrankungsverläufe möglich sind, bzw. die hier genutzten Informationen nicht bei allen Fällen dem RKI übermittelt werden, sind die so berechneten Daten nur grobe Schätzungen für die Anzahl der Genesenen und sollten daher auch nur unter Berücksichtigung dieser Limitationen verwendet werden.
>  
> Für eine detailliertere Analyse der der COVID-19-Fälle verweisen wir auf den täglichen Lagebericht des RKI.

**Comment by marlon360** [comment]
https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Fallzahlen.html

This table shows the difference. This can be crawled.

A few weeks ago they added a captcha to prevent crawling, but it seems they removed it.
