### ISSUE TITLE
Feature Request: Free Beds in hospitals

### ISSUE THREAD

**Issue by ChristophKrause** [marlon360/rki-covid-api#163]
Story:
The user wants to get information about the beds in hospitals 

Todo:
Add fetching, parsing, saving and accessing the data

Datasource:
https://www.intensivregister.de/#/aktuelle-lage/reports 
(https://diviexchange.blob.core.windows.net/%24web/DIVI_Intensivregister_Auszug_pro_Landkreis.csv)

**Comment by HappyFr1tz** [comment]
Hi, you can also use the API from DIVI directly. It would be kind of unnecessary to host it here if the organisation already offers it itself. 
Source: https://www.intensivregister.de/api/public/reporting/laendertabelle

**Comment by Rubber1Duck** [comment]
Duplicate #73 
and maybe it is a little bit tricky with the rights!?
https://github.com/marlon360/rki-covid-api/issues/73#issuecomment-765900037
