### ISSUE TITLE
RKI too many requests

### ISSUE THREAD

**Issue by JonathanN1203** [marlon360/rki-covid-api#175]
Hi, 

I think there is a problem with some parts of the API from the RKI. An error message appears like this "Unable to perform query. Too many requests.", "Details": ["API calls quota exceeded (1201)! Maximum allowed (1200) per minute. Retry after 60 sec.". This comes when I visit e.g. https://api.corona-zahlen.org/districts/02000/history/incidence/

**Comment by Rubber1Duck** [comment]
I have the same issue! also on my self hosting maschine.
Some request are running some not.

![error_2021_04_14](https://user-images.githubusercontent.com/6493772/114696940-8bcccf80-9d1d-11eb-9670-7fd492f429ef.png)

I think this is a RKI issue, and we have to wait

**Comment by marlon360** [comment]
Seems to work again.

**Comment by cc13com** [comment]
Unfortunately seems not to work again. At least not for my environment

`{"error":{"message":"There is a problem with the official RKI API.","rkiError":{"code":429,"message":"Unable to perform query. Too many requests.","details":["API calls quota exceeded (1738)! maximum allowed (1200) per Minute. Retry after 60 sec."]},"url":"https://services7.arcgis.com/mOBPykOjAyBO2ZKk/arcgis/rest/services/RKI_COVID19/FeatureServer/0/query?where=NeuerFall IN(1,0) AND IdLandkreis = '09564'&objectIds=&time=&resultType=standard&outFields=AnzahlFall,MeldeDatum,Landkreis,IdLandkreis&returnIdsOnly=false&returnUniqueIdsOnly=false&returnCountOnly=false&returnDistinctValues=false&cacheHint=false&orderByFields=IdLandkreis,MeldeDatum&groupByFieldsForStatistics=IdLandkreis,MeldeDatum,Landkreis&outStatistics=[{\"statisticType\":\"sum\",\"onStatisticField\":\"AnzahlFall\",\"outStatisticFieldName\":\"cases\"}]&having=&resultOffset=&resultRecordCount=&sqlFormat=none&f=json&token="}}`

**Comment by JonathanN1203** [comment]
I have got the same issue again

**Comment by Rubber1Duck** [comment]
But as of yesterday this is a RKI issue `API calls quota exceeded (1738)! maximum allowed (1200) per Minute. Retry after 60 sec.`
It seems that the RKI API is well used in the morning ..........
