### ISSUE TITLE
Feature Request: Testzahlen 

### ISSUE THREAD

**Issue by matze1708** [marlon360/rki-covid-api#176]
Hallo,
 wäre es machbar, die Gesamtzahl der Tests mit darzustellen?

Ich kenne leider nur die eine Tabelle vom RKI:
[https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Daten/Testzahlen-gesamt.xlsx?__blob=publicationFile](url)

Vielleicht gibt es noch eine weitere. 

Danke.

**Comment by Rubber1Duck** [comment]
geht nich gibs nich .............. :-)
aber es muss halt jemand machen! Lass dich nicht abhalten einen entsprechenden PR zu erstellen :-)

**Comment by Rubber1Duck** [comment]
Was genau aus der Exceltabelle hättest du gerne?
vieleicht (ohne zu viel Hoffnung zu schüren) kann ich da was zusammenbasteln ...............

**Comment by matze1708** [comment]
Interessant wäre aus dem 2. Arbeitsblatt
Die Werte 
Kalenderwoche
Anzahl Tests
Positiv getestet
Positiven Anzahl 
Übermittelnde Labore


vll gibts das aber auch als API von Arcgis... das habe ich nur noch nicht gefunden.

Diese Daten sind halt mindestens immer eine Woche alt.

Was aber passiert, die alten Zahlen verändern sich!
Das liegt am Probenrückstau, die werden dem Datum der Entnahme zugewiesen.


Danke LG

**Comment by Rubber1Duck** [comment]
Nicht alle Daten vom RKI werden von Arcgis verwaltet/gehostet!
Die Impfzahlen und der R-Wert kommen auch aus Exceltabellen!
Ich schau mal ob ich das hinbekomme. Verstehe noch nicht alles von Type Script, das meiste muss ich mit trail and error machen ..... und leider fehlt mir immernoch eine debug Möglichkeit, das bekomme ich einfach nicht hin mit VS Code ..... bin ich scheinbar doch schon zu alt dafür .....

**Comment by matze1708** [comment]
Danke.

Im Prinzip ist es ganz einfaches JavaScript?!

Axios ist auch ganz cool.

Runter schreiben kann ich das noch nicht, muss auch viel googeln, aber es wird besser.

Ich nutzte PhpStorm oder InteliJ
Da könntest du was mit XDebug machen.

Habe ich aber nur einmal probiert.

Wird mit in den Docker eingebunden.

**Comment by matze1708** [comment]
Klasse !! Wie schnell kannst du das :-) Hut ab.
Habe es mir mal angesehen und auf mein lokales System geclont.
Ich muss mir grade mal überlegen, wie ich am besten ein neues Datenbankmodel aufbaue, so das es sinnig ist. 
Hatte bei meinem Test alles in einer Tabelle. Cases/Death/Recovered. Ist aber nicht perfomant. 

Dennoch muss ich mir irgendwo, initial Daten her holen. Denke, da muss ich trotzdem auf die CSV vom RKI zurück greifen, da die API´s dass dann in dem Stil nicht rausrücken.

**Comment by Rubber1Duck** [comment]
ne du ich kann das nicht schnell, @marlon360 kann das schnell :-)
ein bischen copy and paste aus anderen requests, und viel trail and error, und dann hadere ich noch oft mit github ......
aber gut, es läuft, mal schauen wie lange bis das RKI mal wieder was an dem Excelfile ändert
nun muss es @marlon360 nur moch mergen
