### ISSUE TITLE
Missing r-Value in /germany Response

### ISSUE THREAD

**Issue by Toni-99** [marlon360/rki-covid-api#185]
Today I got an error, because the "value" fiels in the https://api.corona-zahlen.org/germany Response was missing. It just shows a date field. Could you please fix it?

**Comment by JonathanN1203** [comment]
I can see the data 
![image](https://user-images.githubusercontent.com/50752465/115670448-b6381180-a349-11eb-8fff-a5ae4cfed5d9.png)

**Comment by Toni-99** [comment]
Data is given but not the correct r-Value

![grafik](https://user-images.githubusercontent.com/71496013/115672106-7c680a80-a34b-11eb-8725-9b3f3504bf2f.png)
