### ISSUE TITLE
Feature Request: Raspberry Pi (arm) Support for docker image

### ISSUE THREAD

**Issue by stijink** [marlon360/rki-covid-api#192]
Raspberry Pi (arm) Support for docker image would be really awesome :-)

**Comment by Rubber1Duck** [comment]
arm is already supported, but you have to build that image by yourself! (at the moment!)
You can self build this dockerimage on your raspberry!
Install OS on your raspberry. (following is for Raspberry Pi OS )
update your os
`sudo apt get update && sudo apt upgrade`

install git
`sudo apt install git`

install docker
`curl -sSL https://get.docker.com | sh`

Add permission to Pi User to run Docker Commands
`sudo usermod -aG docker pi`

Reboot now!

Test Docker installation
`docker run hello-world`

After reboot Install proper dependencies
`sudo apt-get install -y libffi-dev libssl-dev`
`sudo apt-get install -y python3 python3-pip`
`sudo apt-get remove python-configparser`

Install Docker Compose
`sudo pip3 -v install docker-compose`

now clone this repository
`cd ~`
`git clone https://github.com/marlon360/rki-covid-api.git`

go to the directory
`cd rki-covid-api`

build the image
`docker build -t rki-covid-server:v2 .`  (dont forget the dot at the end)

depending on your raspberry the build process need some time! longest time is to compile the needed lib libvips in the correct version!

after build you should have a look on your image
`docker image ls` 

you should see the image rki-covid-server with tag v2

now edit the file docker-compose.prod.yml
change line 13
https://github.com/marlon360/rki-covid-api/blob/3aea537f7a767ad3487efef4d81e53b75f1f99ae/docker-compose.prod.yaml#L13
to 
`image: rki-covid-server:v2`

yeah, you are done and ready to start your container

`docker-compose -f docker-compose.prod.yaml up` for normal startup
or
`docker-compose -f docker-compose.prod.yaml up -d` for running as service

now you can reach your rkiserver under `http//ip or name of your raspberry:8080/germany` or whatever you want to see

if you are running raspberry PiOS 64 bit you can alternatly use my image 
rubber4duck/test-rki-api witch is for arm64v8!

all the above is tested with raspberry pi 2, 3 and 4 under PiOS 32 bit and 64 bit (if 64bit is possible) witch meens arm32v7 and arm64v8
it should also run on a raspberry 1 with arm32v6 but this is not testet yet and i dont know if this make sense.

if anything is changed in this repository (bugfixes or enhancements)
Stop your docker container
`cd ~/rki-covid-api`
`docker-compose -f docker-compose.prod.yaml down`
save your docker-compose.prod.yaml file
`cp docker-compose.prod.yaml ~/`

update your local repo copy
`git restore docker-compose.prod.yaml`
`git pull`

copy back your docker-compose.prod.yaml
`cp ~/docker-compose.prod.yaml ./`

build a new image
`docker build -t rki-covid-server:v2`
build time is now very much shorter mostly!

and start your container
`docker-compose -f docker-compose.prod.yaml up -d`

**Comment by stijink** [comment]
You're right. Of course. Didn't thought about that at the first moment. :-)
