### ISSUE TITLE
vaccinations 

### ISSUE THREAD

**Issue by HappyFr1tz** [marlon360/rki-covid-api#193]
Hi, there was some mistake in the vaccinations. The RKI itself reports only 220,000 vaccinations for today, but the API lists more than one million vaccinations. In any case, the data from the RKI are likely to be correct, as a total of well over 20 million vaccinations would otherwise have to be reported.

**Comment by Rubber1Duck** [comment]
The RKI added a new column for the Johnson&Johnson vaccine Janssen.
![Janssen](https://user-images.githubusercontent.com/6493772/116227820-d5251200-a754-11eb-8d4e-24392b8492c3.png)
the parser has to be rewritten!
Unfornatly i have no time to write that PR at the moment ..... maybe in the early evening ...

**Comment by Rubber1Duck** [comment]
PR is written, @marlon360 has to merge
