### ISSUE TITLE
Vaccintation history broken

### ISSUE THREAD

**Issue by mmkk19** [marlon360/rki-covid-api#195]
Vaccination history does not show total and first vaccinations.
It seems like they did it again: they renamed columns.
"Begonnene Impfserie" instead of "Einmal geimpft".

I think the total value didn't work anyway before - it was the same as first vaccinations.

Could anyone fix that?

**Comment by Rubber1Duck** [comment]
> I think the total value didn't work anyway before - it was the same as first vaccinations.

Thats for compatibility reasons!

Okay, i will do that patch ...... a few minutes .....

**Comment by Rubber1Duck** [comment]
done. @marlon360 has to merge this!
