### ISSUE TITLE
Zertifikat

### ISSUE THREAD

**Issue by xhendrikg** [marlon360/rki-covid-api#205]
![grafik](https://user-images.githubusercontent.com/69456711/116806952-aaf69a00-ab30-11eb-99a6-bf245214b62c.png)

**Comment by xhendrikg** [comment]
auf corona-zahlen.org, Browser: Firefox

**Comment by Rubber1Duck** [comment]
use [https://api.corona-zahlen.org](https://api.corona-zahlen.org) instead of [corona-zahlen.org](corona-zahlen.org)

**Comment by marlon360** [comment]
No problems on my end.
