### ISSUE TITLE
Docker image deliver wrong vaccination numbers

### ISSUE THREAD

**Issue by cc13com** [marlon360/rki-covid-api#206]
Hello,

I'm using your docker image(s) on my own server (see also https://github.com/marlon360/rki-covid-api/issues/101). Since a view days the "vaccination/history" delivers wrong data. I saw in another issue that the RKI renamed the column. I updated the image, restarted the container but the "vaccination" numbers are still "0". 

Is the renamed column not reflected in this docker-container?

**Comment by Rubber1Duck** [comment]
how did you restart the container?
try this please
"docker-compose up -d -V" maybe you see the cached entrys! "-V" rebuilds/flush the cache
if you try this API all seems fine!
[https://api.corona-zahlen.org/vaccinations/history](https://api.corona-zahlen.org/vaccinations/history)
![vaccination_history](https://user-images.githubusercontent.com/6493772/116810361-a7204300-ab43-11eb-8c1d-f3a05b1ebd56.png)

**Comment by Rubber1Duck** [comment]
i have just tried this docker image
`marlon360/rki-covid-server:v2` and all went fine!

**Comment by marlon360** [comment]
Try running `docker-compose pull && docker-compose up -d -V` in the directory of your docker-compose file.

**Comment by cc13com** [comment]
With `docker-compose pull && docker-compose up -d -V` it's working well now. Wonder why, but I did a `pull` of the new image this morning.

Is there a difference between image `marlon360/rki-covid-server:v2` and `docker.pkg.github.com/marlon360/rki-covid-api/rki-server:v2`?

**Comment by marlon360** [comment]
The docker image on Docker Hub and GitHub Packages are the same, but I think there are some problems with permission when pulling GitHub Packages.
