### ISSUE TITLE
testing endpoint  -  add latest value  -  Feature request

### ISSUE THREAD

**Issue by hajo62** [marlon360/rki-covid-api#210]
To use your values in Home Assistant, it would be useful to not _only_ have the testing history, but to have a kind of latest or actual value. Or even better (to reduce amount of transferred data) a testing endpoint, which just has the values of the last/latest week.
(I'm not using the Home Assistant Integration; I pull the values by my own)

**Comment by marlon360** [comment]
PR #209 will add this feature.

**Comment by marlon360** [comment]
@hajo62 What du you mean by „latest value“?
The sum of all tests?
The latest history value is the latest value the RKI provides, there are no daily numbers.

**Comment by hajo62** [comment]
To minimize the effort, I only asked for the absolut value of last week. Would make it easier to use that in Home Assistant.
<img width="346" alt="grafik" src="https://user-images.githubusercontent.com/15800980/116968777-7233fd80-acb5-11eb-99f9-3913dbff9526.png">
HA has a REST-Sensor; it's fairly easy to get values from a JSON object returned, if that object is _fixed_. It is more complicate to get the _lastest_ value from your /testing/history endpoint, because _latest_ (59 in the screenshot above) changes every week,

**Comment by marlon360** [comment]
Now you can call https://api.corona-zahlen.org/testing/history/1 to get the latest data.
