### ISSUE TITLE
The frozen-incidence/history dates should be 1 less

### ISSUE THREAD

**Issue by Rubber1Duck** [marlon360/rki-covid-api#217]
> Same here, the incidence value for munich is today at 98.30039360582553 (https://api.corona-zahlen.org/districts/09162), but in the frozen history, the last data is from yesterday. But with the incidence history I am completly done, because, there is the incidence value from today labled as yesteraday:

Wow, that sounds very angry ............. 
it is never possible to give values for today! all values that are today published by RKI are values from yesterday, because today is running ....... they say today that we have yesterday blablabla new cases (or whatelse)! how many new cases we have today the RKI can only say at 23:59:59 o'clock.....
but you are right i also think that the dates in frozen-history should be 1 less

_Originally posted by @Rubber1Duck in https://github.com/marlon360/rki-covid-api/issues/123#issuecomment-833482585_

**Comment by Rubber1Duck** [comment]
It is not possible to publish a incidence value for today because it will not be published until tomorrow!

**Comment by Rubber1Duck** [comment]
that can be easily done by 
change this line 
https://github.com/marlon360/rki-covid-api/blob/4feb606efa37d1b1970dcf65d71f61a5c62face1/src/data-requests/frozen-incidence.ts#L51-L53
to 
`const date =  AddDaysToDate(new Date(
        dateKey.toString().replace(date_pattern, "$3-$2-$1")
      ), -1);`

**when #216 is merged!**

and adding AddDaysToDate here
https://github.com/marlon360/rki-covid-api/blob/4feb606efa37d1b1970dcf65d71f61a5c62face1/src/data-requests/frozen-incidence.ts#L3

I think.

**Comment by marcusraitner** [comment]
> It is not possible to publish a incidence value for today because it will not be published until tomorrow!

The RKI nevertheless does in their Excel; see also the issue I created today #220. I totally agree that it is not very logical an in the calculation I did previously in my little Scriptable Widget I did it as you suggested. But finally for the sake of consistency I changed it to the RKI's definition. And I would suggest that we are here at least consistent because currently the latest incidence value for frozen is for today whereas for the normal history it's for yesterday.

**Comment by Rubber1Duck** [comment]
> 
> 
> > It is not possible to publish a incidence value for today because it will not be published until tomorrow!
> 
> The RKI nevertheless does in their Excel; see also the issue I created today #220. I totally agree that it is not very logical an in the calculation I did previously in my little Scriptable Widget I did it as you suggested. But finally for the sake of consistency I changed it to the RKI's definition. And I would suggest that we are here at least consistent because currently the latest incidence value for frozen is for today whereas for the normal history it's for yesterday.

the most important thing for this API is that it is done the same everywhere! What the end user does with the data is up to him. I think that it should be fine with him that he knows exactly how to interpret the data.

**Comment by marcusraitner** [comment]
> > > It is not possible to publish a incidence value for today because it will not be published until tomorrow!
> > 
> > 
> > The RKI nevertheless does in their Excel; see also the issue I created today #220. I totally agree that it is not very logical an in the calculation I did previously in my little Scriptable Widget I did it as you suggested. But finally for the sake of consistency I changed it to the RKI's definition. And I would suggest that we are here at least consistent because currently the latest incidence value for frozen is for today whereas for the normal history it's for yesterday.
> 
> the most important thing for this API is that it is done the same everywhere! What the end user does with the data is up to him. I think that it should be fine with him that he knows exactly how to interpret the data.

Absolutely. I was just stumbling across this problem while I tried to implement a switch into my widget where you can choose between the frozen values and the "normal" and then this behaviors becomes very apparent ;-) But I can of course work around it, though I would prefer consistency.
