### ISSUE TITLE
Feature Request: 7-day r value

### ISSUE THREAD

**Issue by marlon360** [marlon360/rki-covid-api#219]
At the moment we only use the 4-day r value. Apps like Corona Warn App use the 7-day r value.
We should add it to the API as well.

**Comment by Rubber1Duck** [comment]
Where do you want to publish this value?
under /germany too?
at 14:50 MEST or GMT+2 the aktual file looks like this: (unfornatly the file is not updated today till now!)
![r-value1](https://user-images.githubusercontent.com/6493772/118273583-640b8b80-b4c4-11eb-9fc1-0bf3379637a6.png)
![r-value2](https://user-images.githubusercontent.com/6493772/118273627-72f23e00-b4c4-11eb-954b-15a8bb688391.png)

The latest entry for 4 day r-value is from 2021-05-09 and the latest 7 day r-value is from 2021-05-08 (i dont know how this works....)

so for each r-value there must be a seqerate date!

should it look like this under /germany:

```json
{
"cases":3577040,
"deaths":85848,
"recovered":3259004,
"weekIncidence":96.5446379140808,
"casesPer100k":4301.047807457481,
"casesPerWeek":80293,
"delta":{
            "cases":11336,
            "deaths":190,
            "recovered":18689},
"r":{
            "4-day-r-value":0.77,
            "date":"2021-05-09T00:00:00.000Z",
            "7-day-r-value":0.87,
            "date":"2021-05-08T00:00:00.000Z"},
"meta":{
"source":"Robert Koch-Institut",
"contact":"Marlon Lueckert (m.lueckert@me.com)",
"info":"https://github.com/marlon360/rki-covid-api",
"lastUpdate":"2021-05-13T23:00:00.000Z",
"lastCheckedForUpdate":"2021-05-14T12:58:02.107Z"}}
```
???

**Comment by Rubber1Duck** [comment]
This can be closed i think
