### ISSUE TITLE
Requested 12 days, but got only 11 values

### ISSUE THREAD

**Issue by marcusraitner** [marlon360/rki-covid-api#223]
I do request 12 days via https://api.corona-zahlen.org/districts/09175/history/frozen-incidence/12 and get only 11 values as response. Why is it?

`{"data":{"09175":{"ags":"09175","name":"LK Ebersberg","history":[{"weekIncidence":141.3166816337,"date":"2021-05-02T00:00:00.000Z"},{"weekIncidence":130.8745623012,"date":"2021-05-03T00:00:00.000Z"},{"weekIncidence":130.1784210123,"date":"2021-05-04T00:00:00.000Z"},{"weekIncidence":115.5594539468,"date":"2021-05-05T00:00:00.000Z"},{"weekIncidence":114.8633126579,"date":"2021-05-06T00:00:00.000Z"},{"weekIncidence":94.6752152817,"date":"2021-05-07T00:00:00.000Z"},{"weekIncidence":116.2555952356,"date":"2021-05-08T00:00:00.000Z"},{"weekIncidence":116.2555952356,"date":"2021-05-09T00:00:00.000Z"},{"weekIncidence":113.4710300803,"date":"2021-05-10T00:00:00.000Z"},{"weekIncidence":111.3826062138,"date":"2021-05-11T00:00:00.000Z"},{"weekIncidence":109.2941823472,"date":"2021-05-12T00:00:00.000Z"}]}},"meta":{"source":"Robert Koch-Institut","contact":"Marlon Lueckert (m.lueckert@me.com)","info":"https://github.com/marlon360/rki-covid-api","lastUpdate":"2021-05-12T06:51:21.000Z","lastCheckedForUpdate":"2021-05-13T05:46:27.941Z"}} `

**Comment by marcusraitner** [comment]
Now it worked. Strange. Got now the following:

`{"data":{"09175":{"ags":"09175","name":"LK Ebersberg","history":[{"weekIncidence":141.3166816337,"date":"2021-05-02T00:00:00.000Z"},{"weekIncidence":130.8745623012,"date":"2021-05-03T00:00:00.000Z"},{"weekIncidence":130.1784210123,"date":"2021-05-04T00:00:00.000Z"},{"weekIncidence":115.5594539468,"date":"2021-05-05T00:00:00.000Z"},{"weekIncidence":114.8633126579,"date":"2021-05-06T00:00:00.000Z"},{"weekIncidence":94.6752152817,"date":"2021-05-07T00:00:00.000Z"},{"weekIncidence":116.2555952356,"date":"2021-05-08T00:00:00.000Z"},{"weekIncidence":116.2555952356,"date":"2021-05-09T00:00:00.000Z"},{"weekIncidence":113.4710300803,"date":"2021-05-10T00:00:00.000Z"},{"weekIncidence":111.3826062138,"date":"2021-05-11T00:00:00.000Z"},{"weekIncidence":109.2941823472,"date":"2021-05-12T00:00:00.000Z"},{"weekIncidence":99.5482043035,"date":"2021-05-13T00:00:00.000Z"}]}},"meta":{"source":"Robert Koch-Institut","contact":"Marlon Lueckert (m.lueckert@me.com)","info":"https://github.com/marlon360/rki-covid-api","lastUpdate":"2021-05-13T07:04:16.000Z","lastCheckedForUpdate":"2021-05-13T07:05:15.604Z"}}`

**Comment by Rubber1Duck** [comment]
Hi Marcus, thats because in the first case the data wasn't updated (lastUpdate 2021-05-12), so the value for 2021-05-13 isn't availible. In the second caes the data is updated (lastUpdate: 2021-05-13) and the value for 2021-05-13 is shown.....!

**Comment by marcusraitner** [comment]
Ok, got it. Somehow the "days" parameter in the request was then misleading; at least to me. In my interpretation (maybe I should read the f*** manual first) this meant "give me the last X days you have no matter when the last update was.

**Comment by Rubber1Duck** [comment]
here it is like "give me all values that you have with date >today - days"

**Comment by marcusraitner** [comment]
Which is also fine and also makes sense for me, because then I have a gap in my widget and see that there is an update still pending.

**Comment by Rubber1Duck** [comment]
Then this issue can be closed?

**Comment by marcusraitner** [comment]
Yes, please. Is a feature, not a bug 😉

**Comment by Rubber1Duck** [comment]
I can't close this issue! You have to do this!

**Comment by marcusraitner** [comment]
Done
