### ISSUE TITLE
Risk areas (RKI)

### ISSUE THREAD

**Issue by HappyFr1tz** [marlon360/rki-covid-api#227]
Hi, 
I wanted to ask if it is somehow possible to integrate the list from the RKI with the risk areas and possibly display Europe as a map, as it already works with the counties and federal states. Somehow other people already manage to do this automatically, but such an interface is not publicly available.
The data on the risk areas is available for example here: https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Risikogebiete_neu.html 
or directly from the German Foreign Office at 
https://www.auswaertiges-amt.de/de/ReiseUndSicherheit/reise-und-sicherheitshinweise.

**Comment by Rubber1Duck** [comment]
Hi,
both sources are difficult to parse !
If anybody knows a xlsx file or a database this should be possible!

**Comment by Rubber1Duck** [comment]
no further replies for 8 months .... will close this issue
