### ISSUE TITLE
Error: history data returns errors.

### ISSUE THREAD

**Issue by UplDev** [marlon360/rki-covid-api#230]
Not sure if you're aware of it:
Several or all history-related endpoints return no data. This worked fine only yesterday.

E.g. [https://api.corona-zahlen.org/districts/history/frozen-incidence/7](https://api.corona-zahlen.org/districts/history/frozen-incidence/7)
returns 
`{"error":{"message":"An error occurred.","details":"Cannot read property 'A2' of undefined","stack":"TypeError: Cannot read property 'A2' of undefined\n    at Object.<anonymous> (/usr/src/app/src/data-requests/frozen-incidence.ts:37:27)\n    at Generator.next (<anonymous>)\n    at fulfilled (/usr/src/app/dist/data-requests/frozen-incidence.js:5:58)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)"}}`

non-history-related endpoints seem to be working fine, although I didn't test them all.

**Comment by SystemKeeper** [comment]
Guess it’s related to https://github.com/marlon360/rki-covid-api/pull/228
