### ISSUE TITLE
Inzididenzverlauf aktualisiert sich sehr langsam

### ISSUE THREAD

**Issue by GlaubeKeinemDev** [marlon360/rki-covid-api#231]
Hi,

Ich habe nur eine kleine Frage wieso updated sich der Inzidenzverlauf (/districts/:ags/history/incidence/:days) meines Landkreises so langsam (22.05.2021 letztes Update), während wenn ich normal /districts anfrage die Inzidenz sich täglich aktualisiert?

MfG

**Comment by Rubber1Duck** [comment]
Wenn die letzten Tage 0 neue Fälle waren, wird nicht aktualisiert! ist in issue #82 beschrieben!
