### ISSUE TITLE
Wrong data for frozen incidence

### ISSUE THREAD

**Issue by netcom-severs** [marlon360/rki-covid-api#236]
Today at around 09:20 am the api for "frozen incidence" delivered wrong data for District "LK Görlitz" for 2021-06-08: 52.6284579121

To that time, the RKI excel sheet did not even show values for that date. 
See Attachment: 
[Fallzahlen_Kum_Tab ‎8 ‎Juni ‎2021 ‏‎09.18 Uhr.xlsx](https://github.com/marlon360/rki-covid-api/files/6615100/Fallzahlen_Kum_Tab.8.Juni.2021.09.18.Uhr.xlsx)

After the RKI updated the Excel sheet at around 10 am, the api shows the right value "16.2231674745".
See Attachment: 
[Fallzahlen_Kum_Tab ‎8 ‎Juni ‎2021 ‏‎10.19 Uhr.xlsx](https://github.com/marlon360/rki-covid-api/files/6615144/Fallzahlen_Kum_Tab.8.Juni.2021.10.19.Uhr.xlsx)

Earlier this morning, araound 7 am, the api reported the weekIncidence only until "2021-06-07", which is the expected behavior if the data source is not updated by the RKI.

The issue occurred on https://api.corona-zahlen.org/ as well as on our self hosted environment.

BTW: Don´t now if related, but "52.6284579121" seems to be the incidence for "LK Gotha (16067)" for toady, which is two rows below of "LK Görlitz".

Request: https://api.corona-zahlen.org/districts/14626/history/frozen-incidence/8
Response: 
`{
   "data":{
      "14626":{
         "ags":"14626",
         "name":"LK Görlitz",
         "history":[
            {
               "weekIncidence":63.3099218518,
               "date":"2021-06-01T00:00:00.000Z"
            },
            {
               "weekIncidence":37.5902660995,
               "date":"2021-06-02T00:00:00.000Z"
            },
            {
               "weekIncidence":30.0722128796,
               "date":"2021-06-03T00:00:00.000Z"
            },
            {
               "weekIncidence":28.4894648333,
               "date":"2021-06-04T00:00:00.000Z"
            },
            {
               "weekIncidence":23.3455336829,
               "date":"2021-06-05T00:00:00.000Z"
            },
            {
               "weekIncidence":21.367098625,
               "date":"2021-06-06T00:00:00.000Z"
            },
            {
               "weekIncidence":21.367098625,
               "date":"2021-06-07T00:00:00.000Z"
            },
            {
               "weekIncidence":52.6284579121,
               "date":"2021-06-08T00:00:00.000Z"
            }
         ]
      }
   },
   "meta":{
      "source":"Robert Koch-Institut",
      "contact":"Marlon Lueckert (m.lueckert@me.com)",
      "info":"https://github.com/marlon360/rki-covid-api",
      "lastUpdate":"2021-06-08T05:42:56.000Z",
      "lastCheckedForUpdate":"2021-06-08T08:02:22.761Z"
   }
}`

**Comment by Rubber1Duck** [comment]
@netcom-severs do you still have issues with this?
if not, close this issue please

**Comment by netcom-severs** [comment]
No, that issue occurred only once. I don´t feel realy comfortable with closing this issue as we do not know the root cause,
But I also do not belive that we are able to find it...
