### ISSUE TITLE
RKI did it again: Broken Vaccination History

### ISSUE THREAD

**Issue by laurenzfg** [marlon360/rki-covid-api#237]
RKI subtly changed the Excel sheet again. At the moment of this issue, the Datum column is of the string type, not the Datum type. Thus [https://api.corona-zahlen.org/vaccinations/history/7](https://api.corona-zahlen.org/vaccinations/history/7) currently has an empty result.

**Comment by laurenzfg** [comment]
I did some debugging, it does not recognize any line as Date. So this if check always fails:

    if ((entry.Datum as any) instanceof Date) {

**Comment by HappyFr1tz** [comment]
> RKI subtly changed the Excel sheet again. At the moment of this issue, the Datum column is of the string type, not the Datum type. Thus https://api.corona-zahlen.org/vaccinations/history/7 currently has an empty result.

The data for today (https://api.corona-zahlen.org/vaccinations) are now correct, after they were completely distorted earlier. No idea what the RKI has done, but it was not correct. Maybe it helps you, if you fall back on the data from today for the time being.

**Comment by laurenzfg** [comment]
They changed the number format for the date cells. I looked into the raw representation of the xlsx, and some cells were configured with number format 44, which is not even standardized [see the xlsx documentation](https://github.com/closedxml/closedxml/wiki/NumberFormatId-Lookup-Table).
I did not what they did with their Excel.

One day, no government agency will use whacky desktop programs and proprietary formats to publish open data!

**Comment by laurenzfg** [comment]
But the data for today extracted from the coverage table does not include the total number of vaccinations. Since RKI changed the semantics of the coverage table, you cannot add both deltas to get that. @HappyFr1tz 

I just wait if RKI corrects their table tomorrow. This is all a big mess.

**Comment by laurenzfg** [comment]
OK so I looked into this again. There are in fact two problems:

- the date cells are set to the string type instead of the date type. Either we have to adjust to accept dates as strings or RKI fixes the table formatting. See the attached RKI and corrected table.
[Table Corrected 10 Jun 21.xlsx](https://github.com/marlon360/rki-covid-api/files/6631651/Table.Corrected.10.Jun.21.xlsx)
[Table RKI 10 Jun 21.xlsx](https://github.com/marlon360/rki-covid-api/files/6631652/Table.RKI.10.Jun.21.xlsx)
- In todays issue, the RKI switched from plural table headers to singular table headers (Erstimpfungen --> Erstimpfung). I made a PR to adapt to this.

**Comment by Rubber1Duck** [comment]
I think it is time to catch all this cases as we are doing in r-value.ts!
I suggest the following:
```
  let vaccinationHistory: VaccinationHistoryEntry[] = [];
  const pattern = /(\d{2})\.(\d{2})\.(\d{4})/;
  for (const entry of json) {
    const firstVac =
      entry["Erstimpfung"] ||
      entry["Erstimpfungen"] ||
      entry["mindestens einmal geimpft"];
    const secVac =
      entry["Zweitimpfung"] ||
      entry["Zweitimpfungen"] ||
      entry["vollständig geimpt"] ||
      entry["vollständig geimpft"];
    if (typeof entry.Datum == "string") {
      const dateString: string = entry.Datum;
      const DateNew: Date = new Date(dateString.replace(pattern, "$3-$2-$1"));
      vaccinationHistory.push({
        date: DateNew,
        vaccinated: firstVac ?? 0, // legacy attribute
        firstVaccination: firstVac ?? 0,
        secondVaccination: secVac ?? 0,
      });
    } else if (entry.Datum instanceof Date) {
      vaccinationHistory.push({
        date: entry.Datum,
        vaccinated: firstVac ?? 0, // legacy attribute
        firstVaccination: firstVac ?? 0,
        secondVaccination: secVac ?? 0,
      });
    }
  }

  if (days == null) {
    days = json.length;
  } //to filter out undefined dates
  const reference_date = new Date(getDateBefore(days + 1));
  vaccinationHistory = vaccinationHistory.filter(
    (element) => element.date > reference_date
  );
```
@laurenzfg would you insert this to your PR?

This is working now!!!!!!!!!!!!!!!!!!!!

**Comment by Rubber1Duck** [comment]
@marlon360 Marlon, as the problematic that the Janssen Vaccine is counted to first AND second vaccination (i think to calculate the right rates) the total ammount of vaccination per day can not calculated by adding first and second vaccination!
The total vaccinations per day are published in the XLSX sheet, and it is not a problem to insert a additional "field" e.g. "totalVaccination" to the api!
What do you think about?
And maybe it is time to kick out the indication fields?

**Comment by laurenzfg** [comment]
> I think it is time to catch all this cases as we are doing in r-value.ts!
> I suggest the following:
> 
> ```
>   let vaccinationHistory: VaccinationHistoryEntry[] = [];
>   const pattern = /(\d{2})\.(\d{2})\.(\d{4})/;
>   for (const entry of json) {
>     const firstVac =
>       entry["Erstimpfung"] ||
>       entry["Erstimpfungen"] ||
>       entry["mindestens einmal geimpft"];
>     const secVac =
>       entry["Zweitimpfung"] ||
>       entry["Zweitimpfungen"] ||
>       entry["vollständig geimpt"] ||
>       entry["vollständig geimpft"];
>     if (typeof entry.Datum == "string") {
>       const dateString: string = entry.Datum;
>       const DateNew: Date = new Date(dateString.replace(pattern, "$3-$2-$1"));
>       vaccinationHistory.push({
>         date: DateNew,
>         vaccinated: firstVac ?? 0, // legacy attribute
>         firstVaccination: firstVac ?? 0,
>         secondVaccination: secVac ?? 0,
>       });
>     } else if (entry.Datum instanceof Date) {
>       vaccinationHistory.push({
>         date: entry.Datum,
>         vaccinated: firstVac ?? 0, // legacy attribute
>         firstVaccination: firstVac ?? 0,
>         secondVaccination: secVac ?? 0,
>       });
>     }
>   }
> 
>   if (days == null) {
>     days = json.length;
>   } //to filter out undefined dates
>   const reference_date = new Date(getDateBefore(days + 1));
>   vaccinationHistory = vaccinationHistory.filter(
>     (element) => element.date > reference_date
>   );
> ```
> 
> @laurenzfg would you insert this to your PR?
> 
> This is working now!!!!!!!!!!!!!!!!!!!!

I included (and tested) your suggested code in #238 .

**Comment by laurenzfg** [comment]
> @marlon360 Marlon, as the problematic that the Janssen Vaccine is counted to first AND second vaccination (i think to calculate the right rates) the total ammount of vaccination per day can not calculated by adding first and second vaccination!
> The total vaccinations per day are published in the XLSX sheet, and it is not a problem to insert a additional "field" e.g. "totalVaccination" to the api!
> What do you think about?
> And maybe it is time to kick out the indication fields?

I decided to address this problem in a systematic fashion by including the latest history entry in the coverage endpoint. See #239 for details.

**Comment by Rubber1Duck** [comment]
I think it would have been better to wait for Marlon's answer, but okay your decision.

**Comment by laurenzfg** [comment]
> I think it would have been better to wait for Marlon's answer, but okay your decision.

Sure, it's his call since he is the maintainer! He can choose between #238 (just the fix) and #239 (include latest history entry as well). Or incorporate #238 first and have a discussion regarding #239.

I just wanted to include it into my mirror of the API to be able to get my project running again.

**Comment by Rubber1Duck** [comment]
Changing existing structures are critical, because all API Users have to work on thier apps!
But you are right Marlon has to decide witch solution he wants to merge. Hopefully he will respond soon.

**Comment by laurenzfg** [comment]
> Changing existing structures are critical, because all API Users have to work on thier apps!
> But you are right Marlon has to decide witch solution he wants to merge. Hopefully he will respond soon.

Absolutely! A benefit of my proposal is that the API introduces a new element and leaves the deltas as-is. The weird thing is that RKI changed the meanings of the delta... So even if we leave the API stable, it is kinda instable since our upstream changed.
The alternative would be to translate the RKI table into the old semantic.
