### ISSUE TITLE
Impfinformationsabruf funktioniert nicht.

### ISSUE THREAD

**Issue by GlaubeKeinemDev** [marlon360/rki-covid-api#240]
Hey,

Mir ist aufgefallen bei meiner selbstgehosteten RestAPI kann ich die Impfinformationen nicht abrufen.

`{
"error": {
"message": "An error occurred.",
"details": "Cannot read property 'state' of undefined",
"stack": "TypeError: Cannot read property 'state' of undefined\n    at Object.<anonymous> (/usr/src/app/src/data-requests/vaccination.ts:232:19)\n    at Generator.next (<anonymous>)\n    at fulfilled (/usr/src/app/dist/data-requests/vaccination.js:5:58)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)"
}
}`

**Comment by JonathanN1203** [comment]
nutzt du den link? https://api.corona-zahlen.org/vaccinations/history

**Comment by Rubber1Duck** [comment]
schau mal hier #237 
PR ist geschrieben, jedoch hat Marlon noch nicht gemerged .....
Übergangsweise kannst du dieses Image benutzen "rubber4duck/rki-api:v2" (für Platformen amd64 - arm64/v8 - arm/v7 und arm/v6) empfehle aber dringend wenn hier wieder alles läuft auf das original zurück zu gehen, da ich daran öfters rumspiele!

**Comment by JonathanN1203** [comment]
ah, dann nimm ich erstmal des von dir. Wie muss ich mir denn dafür die Container baun?

**Comment by Rubber1Duck** [comment]
nach dieser Anleitung https://github.com/marlon360/rki-covid-api#start-server
ersetze "marlon360/rki-covid-server:v2" durch "rubber4duck/rki-api:v2"

**Comment by JonathanN1203** [comment]
perfekt danke dir

**Comment by marlon360** [comment]
Fixed with #239
