### ISSUE TITLE
Frozen values not updated

### ISSUE THREAD

**Issue by marcusraitner** [marlon360/rki-covid-api#253]
Hi there, seems that the most current values of https://api.corona-zahlen.org/districts/history/frozen-incidence/7 are from July 9. Probably not your fault, but rather that of the RKI … wanted to let you know nevertheless.

**Comment by Rubber1Duck** [comment]
![01](https://user-images.githubusercontent.com/6493772/125194759-e7422700-e252-11eb-99da-04c9b23aad34.png)

**Comment by marcusraitner** [comment]
Alles klar. War das schon immer so?

**Comment by Rubber1Duck** [comment]
nein, sonst war es täglich ................... wenn die nix ändern können sind die nicht glücklich :-)

**Comment by marcusraitner** [comment]
> nein, sonst war es täglich ................... wenn die nix ändern können sind die nicht glücklich :-)

🙄 Wenn sie dann wenigstens nicht ständig mit dem Excel rumhantieren würden, sondern einfach mal eine richtige API, aber dafür haben sie bestimmt keine Zeit, weil mit dem Excel beschäftigt … irgendwie müssen die Zahlen ja aus den vielen Fax in das Excel kommen 😉

**Comment by Rubber1Duck** [comment]
Das Issue kann geschlossen werden oder?

**Comment by marcusraitner** [comment]
Ja!
