### ISSUE TITLE
Map colour

### ISSUE THREAD

**Issue by HappyFr1tz** [marlon360/rki-covid-api#254]
Hi, I have a question about the colours on the maps. In the legend, the colour code #FEFFB1 is given for the incidence from 15 to 25, but today the code #D5DDD0 came out for Berlin on the States Map. This caused confusion for one of my users because he could not assign the colour to the legend. However, I have already noticed this problem several times, that colours appear on the map that are not stored in the legend. Is this due to the size of the image, that the colours run in such small districts / federal states or is it due to something else?

![image](https://user-images.githubusercontent.com/63804808/126080284-4b2a8cfc-c8b7-4ac6-b288-4a5e4a59a8b2.png)

**Comment by Rubber1Duck** [comment]
Oh yeah, you are right
![color1](https://user-images.githubusercontent.com/6493772/126081356-606c4ac6-441d-4d7b-bd8d-d5f4cffd8f10.png)

on my own server with the same quality setting for the png it seems right

![color2](https://user-images.githubusercontent.com/6493772/126081369-ac096bda-b721-425b-8304-29d9af762fa8.png)

what the damn is this?

the only thing what is different is that i am running a newer Version of lib vips............

will give it a try ................

**Comment by Rubber1Duck** [comment]
i just debug the original code from here and .............. the result is rigth !? i'm confused now

i#m in investigation

**Comment by Rubber1Duck** [comment]
I made a mistake, I have a different quality setting, so it was correct on my server!
Quality Setting of 25 solves the problem! (i am running 50, but to hold the resulting image smal this should be as smal as possible)
PR is written! @marlon360  has to merge it!
