### ISSUE TITLE
Error in API response

### ISSUE THREAD

**Issue by mindbreaker** [marlon360/rki-covid-api#261]
There is an error in the response:
URL: https://api.corona-zahlen.org/districts/09172

_{"error":{"message":"An error occurred.","details":"Cannot read property 'attributes' of undefined","stack":"TypeError: Cannot read property 'attributes' of undefined\n    at Object.<anonymous> (/usr/src/app/src/data-requests/districts.ts:116:43)\n    at Generator.next (<anonymous>)\n    at fulfilled (/usr/src/app/dist/data-requests/districts.js:5:58)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)"}}_

**Comment by hajo62** [comment]
Same for [states](https://api.corona-zahlen.org/states/NW) or other [districts](https://api.corona-zahlen.org/districts/05315).

**Comment by Toni-99** [comment]
On germany it's 

`
{

    "cases": null,
    "deaths": null,
    "recovered": null,
    "weekIncidence": 17.885762008792195,
    "casesPer100k": 0,
    "casesPerWeek": 14875,
    "delta": {
        "cases": null,
        "deaths": null,
        "recovered": null
    },
    "r": {
        "rValue4Days": {
            "date": "2021-07-30T00:00:00.000Z"
        },
        "rValue7Days": {
            "value": 1.06,
            "date": "2021-07-29T00:00:00.000Z"
        },
        "date": "2021-07-29T00:00:00.000Z"
    },
    "meta": {
        "source": "Robert Koch-Institut",
        "contact": "Marlon Lueckert (m.lueckert@me.com)",
        "info": "https://github.com/marlon360/rki-covid-api",
        "lastUpdate": "2021-08-02T23:00:00.000Z",
        "lastCheckedForUpdate": "2021-08-03T06:47:36.039Z"
    }

}
`

Thx 4 ur help :)

**Comment by mklippel** [comment]
The same here!

Last days RKI had some problems, but this error is different.

Maybe RKI changed complete API after the problems?

**Comment by Rubber1Duck** [comment]
The Data is still in updating process!
![updating](https://user-images.githubusercontent.com/6493772/127979255-ce1c45b4-23e4-4a08-abd0-cde727430751.png)
We have to wait ........................

**Comment by ThumbGen** [comment]
Disclaimer: I didn't check the code to see when/how data gets fetched/cached, hence my question might seem naive.

I need during the next weeks to be able to rely on some results of the API (for a live demo). Is there any simple 'trick' how to cache them and 'isolate' my demo so I am sure it will work reliably?

Thank you for any idea!

**Comment by j0n4sk4pp4** [comment]
@ThumbGen I guess one thing you could do is:

1. Clone this repo
2. Hope, that the data is available in time
3. save the responses you need to json files
4. edit this repo to get the data from your json files instead of the urls
_Edit: You dont need step 5 and 6, I guess_
5. create a docker image
6. edit the docker-compose to use your image

This should do the trick in mocking the data

**Comment by ThumbGen** [comment]
Thanks a lot, was afraid I had to do that :/ I was hoping I could use a Redis 'snapshot' somehow without touching any code, nor recreating the image. Simply backing-up a 'succesfull' Redis snapshot and restoring it, if I see that the API has problems :)

**Comment by j0n4sk4pp4** [comment]
@ThumbGen This project uses [express-redis-cache](https://github.com/rv-kip/express-redis-cache). Maybe it is enough to set the `expire` in `src/server.ts` `line: 45` to something really high. But this is also not a real snapshot.

**Comment by claaslange** [comment]
The parsing of the Excel file for the frozen incidences seems to be broken as well. https://api.corona-zahlen.org/districts/history/frozen-incidence/7 returns 
```
{
  "error": {
    "message": "An error occurred.",
    "details": "Cannot read property 'toString' of undefined",
    "stack": "TypeError: Cannot read property 'toString' of undefined\n    at /usr/src/app/src/data-requests/frozen-incidence.ts:44:34\n    at Array.map (<anonymous>)\n    at Object.<anonymous> (/usr/src/app/src/data-requests/frozen-incidence.ts:42:24)\n    at Generator.next (<anonymous>)\n    at fulfilled (/usr/src/app/dist/data-requests/frozen-incidence.js:5:58)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)"
  }
}
```
for instance.

Update: Tried to fix that in https://github.com/marlon360/rki-covid-api/pull/262

**Comment by j0n4sk4pp4** [comment]
The API seems to work again.
