### ISSUE TITLE
History Data is missing

### ISSUE THREAD

**Issue by Toni-99** [marlon360/rki-covid-api#264]
https://api.corona-zahlen.org/districts/history/frozen-incidence/7

Litterally all history Endpoints are returning an error message like:

`{

    "error": {
        "message": "An error occurred.",
        "details": "Cannot read property 'toString' of undefined",
        "stack": "TypeError: Cannot read property 'toString' of undefined\n    at /usr/src/app/src/data-requests/frozen-incidence.ts:44:34\n    at Array.map (<anonymous>)\n    at Object.<anonymous> (/usr/src/app/src/data-requests/frozen-incidence.ts:42:24)\n    at Generator.next (<anonymous>)\n    at fulfilled (/usr/src/app/dist/data-requests/frozen-incidence.js:5:58)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)"
    }

}`

**Comment by Rubber1Duck** [comment]
see https://github.com/marlon360/rki-covid-api/issues/261#issuecomment-891768832
PR is written, see https://github.com/marlon360/rki-covid-api/pull/262#issue-702207047
unfortunately, Marlon seems to have very little time, and is very busy and/or in vaccation..............
