### ISSUE TITLE
Sum of 1st and 2nd vaccination > administered vaccination

### ISSUE THREAD

**Issue by kaolick** [marlon360/rki-covid-api#268]
In the API description for it says:

`administeredVaccinations` The total number of administered vaccine doses (sum of first and second vaccination)

But when you add up the numbers for first and second vaccination this sum is bigger than this value. IS this a miscalculation or do I miss something here?

Example from Sunday 08.08.2021:

"administeredVaccinations": 94272474
"vaccinated": 51750882
"secondVaccination": {
            "vaccinated": 44999521,

51750882 + 44999521 = 96750403

**Comment by Rubber1Duck** [comment]
See the remark in describtion
`ATTENTION vaccinations with Janssen are counted as both firstVaccination and secondVaccination but are only counted once in administeredVaccinations!`
51750882 + 44999521 = 96750403
minus 94272474 = 2477929 = Janssen 
![janssen](https://user-images.githubusercontent.com/6493772/128630188-3755d833-26ee-423b-8fe4-f2d8ab1e8107.png)

so the documentation is not exactly right ................ should be (sum of first und second vaccination minus 1 time janssen) or similar ....

**Comment by Rubber1Duck** [comment]
i think this issue can be closed, because thats not a bug, thats exactly what the RKI provide
