### ISSUE TITLE
Wrong colour at district map

### ISSUE THREAD

**Issue by HappyFr1tz** [marlon360/rki-covid-api#273]
Hi, can anyone tell me why at least two districts (Wuppertal & Leverkusen) have the wrong colour? Actually, the two counties should be marked in grey with the colour #DAB7BA (incidence over 200), but they are only marked with the colour #B374DD. 
![image](https://user-images.githubusercontent.com/63804808/131217371-ac842869-2968-4a17-84ae-407e01bc60e7.png)

**Comment by Rubber1Duck** [comment]
it seems thats still a png compression artefact ............ if the quality is set to 100 all looks okay!
currend quality setting 25
![districts25](https://user-images.githubusercontent.com/6493772/131254493-4a05ed9f-5d9c-42c6-b7d8-19fe3afedc4c.jpg)
with quality setting 100
![districts100_crop](https://user-images.githubusercontent.com/6493772/131254512-52766fec-113d-4ff2-876c-f09d17cbcfd7.jpg)
thats the actual color settings
![Colorsettings](https://user-images.githubusercontent.com/6493772/131254790-719ef121-5741-443b-a0d9-64e8fd5c49be.png)

**Comment by Rubber1Duck** [comment]
i tested some values and it seems that quality 75 is high enough ( quality value 50 not!)
