### ISSUE TITLE
 7-Tage-Hospitalisierungsinzidenz

### ISSUE THREAD

**Issue by marcusraitner** [marlon360/rki-covid-api#275]
Du you already have an idea, whether it will be possible to provide the "7-Tage-Hospitalisierungsinzidenz" in your API? I'd like to show it in my Scriptable-Widget.

**Comment by HappyFr1tz** [comment]
I don't know if they will include it in this API, however, here would be a source from the RKI. The table is always updated on Thursday. https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Daten/Klinische_Aspekte.html

**Comment by JDTm** [comment]
Here is the information/table from the bavarian site: https://www.lgl.bayern.de/gesundheit/infektionsschutz/infektionskrankheiten_a_z/coronavirus/karte_coronavirus/index.htm#kennzahlen

BR24 created this page
https://datawrapper.dwcdn.net/2L501/9/

**Comment by marcusraitner** [comment]
Thanks for your input. At least the data is somewhere, but at the moment it does not seem, that it is provided in a reasonable format for the whole country …

**Comment by flodt** [comment]
Is there an update on this? I am also looking for a "reasonable" way to get this data for the whole country

**Comment by Rubber1Duck** [comment]
i had a look on it but i dont find any suitable source ........... :-(

**Comment by Whippie72** [comment]
Only thing i found, was this API linked on the RKI website:
https://github.com/robert-koch-institut/COVID-19-Hospitalisierungen_in_Deutschland

https://github.com/robert-koch-institut/COVID-19-Hospitalisierungen_in_Deutschland/blob/master/Aktuell_Deutschland_COVID-19-Hospitalisierungen.csv

**Comment by marcusraitner** [comment]
That looks quite promising, @Whippie72!

**Comment by Rubber1Duck** [comment]
I will have a look on this .............. and will do my best :-)

**Comment by Rubber1Duck** [comment]
Okay, patch is ready, PR is written and ready to merge.
@marlon360 has to accept the PR!
![hospitalization](https://user-images.githubusercontent.com/6493772/136107477-3891bc60-e6c5-4d27-9705-cce9105b3c77.png)
![hospi-states](https://user-images.githubusercontent.com/6493772/136107695-22595c04-f951-4249-bf81-0737d6710df2.png)

**Comment by marcusraitner** [comment]
Awesome! Can't wait to show it in my Widget 🙏

**Comment by Rubber1Duck** [comment]
Marlon seems to be busy ..................

**Comment by nSystemz** [comment]
Nice to see, hopefully the request will be accepted

**Comment by ghost** [comment]
Probleme mit den Daten aus [robert-koch-institut/COVID-19-Hospitalisierungen_in_Deutschland](https://raw.githubusercontent.com/robert-koch-institut/COVID-19-Hospitalisierungen_in_Deutschland/master/Aktuell_Deutschland_COVID-19-Hospitalisierungen.csv):

#### Stadt Bremen
Der Corona Verordnung liegt die Hospitalisierungsrate der Stadt Bremen zugrunde und nicht die Hospitalisierungsrate des Bundeslandes Bremen. Bei anderen Gebieten ist es vielleicht ähnlich.

- https://www.gesundheit.bremen.de/corona/corona/zahlen/corona-fallzahlen-37649

#### Niedersachsen
Niedersachsen verwendet Daten aus dem IVENA eHealth System, welche von den Daten des RKI abweichen.

- https://github.com/robert-koch-institut/COVID-19-Hospitalisierungen_in_Deutschland/issues/1
- https://www.niedersachsen.de/Coronavirus/aktuelle_lage_in_niedersachsen/niedersachsen-und-corona-aktuelle-leitindikatoren-203487.html

**Comment by Rubber1Duck** [comment]
Das pssiert halt wenn die einzelnen Bundesländer ihre eigene Suppe kochen ................
Diese API bereitet aber nur Daten des RKI in geeigneter Weise auf und stellt sie wieder bereit! nicht mehr und nicht weniger.

**Comment by HappyFr1tz** [comment]
Hi, when can we expect this update to be added? Most of the data is correct so far. @marlon360
