### ISSUE TITLE
Wrong quote for vaccination

### ISSUE THREAD

**Issue by Whippie72** [marlon360/rki-covid-api#280]
Endepoint:
https://api.corona-zahlen.org/vaccinations

Delivers wrong vaccination quote. It´s actually at 1351.47 (135%)

  "data": {
    "administeredVaccinations": 103559222,
    "vaccinated": 55039872,
    "vaccination": {
      "biontech": 38449918,
      "moderna": 4418936,
      "astraZeneca": 9226488,
      "janssen": 2944530
    },
    "delta": 99182,
    **"quote": 1351.47,**
    "secondVaccination": {
      "vaccinated": 51328733,
      "vaccination": {
        "biontech": 39885678,
        "moderna": 5058350,
        "astraZeneca": 3440175,
        "janssen": 126217
      },
      "delta": 135147,
      "quote": 0.682
    },

**Comment by marcusraitner** [comment]
I have discovered the same problem. Only 1st vaccinations are affected; secondVaccination is fine.

**Comment by marlon360** [comment]
The booster vaccination was added to the excel sheet. The parser needs to be adapted to the new structure.

**Comment by marcusraitner** [comment]
Thanks @marlon360!

**Comment by HappyFr1tz** [comment]
Just as an aside: the vaccination rate for second vaccinations is also wrong. Does anyone have time for a fix? Maybe @Rubber1Duck ?

**Comment by Rubber1Duck** [comment]
Sorry i am on vacation..... back on Sunday

**Comment by Rubber1Duck** [comment]
Hi all back from vacation at 13:30 ...... 
Then my 3 year old granddaughter came to visit. Played with her for 4 hours. Then eat a little something.
Then wrote this patch, it couldn't be any faster ............ now @marlon360 has to merge this .................

**Comment by marcusraitner** [comment]
Thanks a lot @Rubber1Duck! First things first. Love it!
