### ISSUE TITLE
Proxy server problem (502 bad request)

### ISSUE THREAD

**Issue by marlon360** [marlon360/rki-covid-api#285]
Error on proxy server:

> Proxy Error
>
> The proxy server received an invalid response from an upstream server.
> The proxy server could not handle the request
>
> Reason: DNS lookup failure for: services7.arcgis.com

**Comment by marlon360** [comment]
Hey @shinebar1001, can you look into this?

**Comment by shinebar1001** [comment]
I'm sorry. Classic. HDD full, at boot no resolv.conf could be created (LXC in Proxmox).
Can you please remove the link as this site is not public (nor restricted due to my lazyness :))
Thanks,
Danny

**Comment by marlon360** [comment]
Thanks @shinebar1001
