### ISSUE TITLE
/germany Endpoint returns 502 Error

### ISSUE THREAD

**Issue by Toni-99** [marlon360/rki-covid-api#288]
Nothing to say additionally

<img width="1494" alt="grafik" src="https://user-images.githubusercontent.com/71496013/137441616-f62f99b2-9467-48bc-9af8-ccffcaa0a52e.png">

**Comment by shinebar1001** [comment]
I have to check that: 
`[Fri Oct 15 00:27:36.828703 2021] [proxy_http:error] [pid 1370:tid 139690162243328] (70007)The timeout specified has expired: [client 114.119.148.184:36154] AH01102: error reading status line from remote server services7.arcgis.com:443`

**Comment by shinebar1001** [comment]
It's working again. Suricata (IDS/IDP) detected some traffic as malicious and blocked the connection.

**Comment by obakuhl** [comment]
I am still getting a bad gateway error. It seems that the website https://api.corona-zahlen.org/germany is not accessible.

**Comment by shinebar1001** [comment]
Hm. @marlon360 is V1 connecting in another way to the proxy? I don't see any blocks at the moment and https://v2.rki.marlon-lueckert.de/germany works fine.

**Comment by xrstf** [comment]
Even just trying to open https://api.corona-zahlen.org/ yields a HTTP 502 for me. Can't be the rate limiting, as I normally do not open the API from my home connection.

**Comment by marlon360** [comment]
Fixed
