### ISSUE TITLE
Frage: Einwoherzahl Bundesweit

### ISSUE THREAD

**Issue by GlaubeKeinemDev** [marlon360/rki-covid-api#290]
Hallo zusammen,

wollte mal Fragen, wieso bei allem die Einwohnerzahl als Parameter "population" angegeben wird aber allgemein über den Request /germany keine Einwohnerzahl dabei steht, eventuell könnte man das noch hinzufügen. Wäre sonst bisschen umständlich um Deutschlandweit die Einwohner zu erfahren alle Bundesländer abzufragen und alles addieren zu lassen.

MfG

**Comment by Rubber1Duck** [comment]
Ersatzweise kannst du die Einwohnerzahl auch mit den gegebenen Werten in /germany berechnen!
weekIncidence = (casesPerWeek / population) * 100000
umgestellt nach population
population = (casesPerWeek * 100000) / incidence
für heute
"weekIncidence":74.44408264365869, "casesPerWeek":61904
(61904 * 100000) / 74.44408264365869 = 83,155,031

hinzufügen zu /germany ist kein Problem, aber worin besteht der Mehrwert?

**Comment by GlaubeKeinemDev** [comment]
Danke erstmal für die Information, dass man es so ausrechnen kann wär ich garnicht draufgekommen. Für mich wäre es einfach einheitlicher, da es ja sonst bei Bundesländern etc. mit angegeben ist, aber der Rechenweg ist gut.
