### ISSUE TITLE
Add Hospitalization history

### ISSUE THREAD

**Issue by Rubber1Duck** [marlon360/rki-covid-api#300]
Quote from [https://github.com/robert-koch-institut/COVID-19-Hospitalisierungen_in_Deutschland#zeitlicher-bezug-der-hospitalisierten-covid-19-f%C3%A4lle](https://github.com/robert-koch-institut/COVID-19-Hospitalisierungen_in_Deutschland#zeitlicher-bezug-der-hospitalisierten-covid-19-f%C3%A4lle)

`............. Wenn die Hospitalisierung mehr als 7 Tage nach der Meldung erfolgt, dann werden diese Fälle zum Berichtsdatum nicht in der 7-Tage-Hospitalisierungsinzidenz erfasst, sondern werden nur bei rückblickender Betrachtung der Daten sichtbar. Ebenso können Melde- und Übermittlungsverzug zu einer eingeschränkten Vollständigkeit der Daten führen. Die Daten sind demnach zum Berichtsdatum noch unvollständig. Nach einigen Tagen liegen die Inforamtionen vollständiger vor, sodass sich die 7-Tage-Hospitalisierungsinzidenz für den Berichtstag im Nachhinein noch erhöht.`

This means that the last hospitalization incidence has little meaning!
I think the history should be provided.
The data has already been evaluated and "only" needs to be output somewhere. The question here is how (structure) and where (under which link) !? (states, germany and age-groups)

**Comment by marcusraitner** [comment]
I would be highly interested in this data for my widget. Please keep me in the loop.
