### ISSUE TITLE
Error code 1010

### ISSUE THREAD

**Issue by sabefix** [marlon360/rki-covid-api#306]
I use the API with OpenHAB to display some values for private use.
Since three days i get "error code 1010" as response. Looks like a Cloudfrare issue: [https://support.cloudflare.com/hc/de/articles/360029779472-Cloudflare-1XXX-Fehler-beheben#error1010](url)
Has been added some filtering for non-browser access or is this my "personal" problem?

**Comment by marlon360** [comment]
Does it work now? I disabled the browser integrity check.

**Comment by sabefix** [comment]
The error disappeared today at about 12:20.

But from 14:18 until now I see a lot of other errors, e.g.
Calling 
`https://api.corona-zahlen.org/districts/03404/history/cases/7` 
results in
`{"error":{"message":"There is a problem with the official RKI API.","rkiError":{"code":499,"message":"Token Required","messageCode":"GWM_0003","details":["Token Required"]},"url":"https://services7.arcgis.com/mOBPykOjAyBO2ZKk/arcgis/rest/services/RKI_COVID19/FeatureServer/0/query?where=NeuerFall IN(1,0) AND IdLandkreis = '03404' AND MeldeDatum >= TIMESTAMP '2021-10-26'&objectIds=&time=&resultType=standard&outFields=AnzahlFall,MeldeDatum,Landkreis,IdLandkreis&returnIdsOnly=false&returnUniqueIdsOnly=false&returnCountOnly=false&returnDistinctValues=false&cacheHint=false&orderByFields=IdLandkreis,MeldeDatum&groupByFieldsForStatistics=IdLandkreis,MeldeDatum,Landkreis&outStatistics=[{\"statisticType\":\"sum\",\"onStatisticField\":\"AnzahlFall\",\"outStatisticFieldName\":\"cases\"}]&having=&resultOffset=&resultRecordCount=&sqlFormat=none&f=json&token="}}`

Calling 
`https://api.corona-zahlen.org/districts/03404`
results in
`{"error":{"message":"An error occurred.","details":"Cannot read properties of undefined (reading 'map')","stack":"TypeError: Cannot read properties of undefined (reading 'map')\n    at /workspace/src/data-requests/districts.ts:89:35\n    at Generator.next (<anonymous>)\n    at fulfilled (/workspace/dist/data-requests/districts.js:5:58)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)"}}`

Calling the API via my browser produces the same errors. So that might be something different.

**Comment by sabefix** [comment]
Now it's working again.
Thanks for your help!
