### ISSUE TITLE
New maps with legend are not working if selfhosted 

### ISSUE THREAD

**Issue by Rubber1Duck** [marlon360/rki-covid-api#316]
on selfhosted API the new map feature with legend are not working as expected!
the resulting image looks like this
![map](https://user-images.githubusercontent.com/6493772/140658762-2f2169fc-c908-4a4d-bdb9-2004abca4eee.png)

i start to add the ttf fonts in the Dockercontainer with this result

![map2](https://user-images.githubusercontent.com/6493772/140661305-ec062712-e10b-4f08-9e4d-3dd90c718d78.png)

looks fine but the date is not in the right format!
After some search with our friend google i found out the following By default --with-intl=small-icu is used to build node, which contains just the en-US locale! (see [https://github.com/nodejs/node/issues/8500](https://github.com/nodejs/node/issues/8500) ) (for node <=V12, for node >V12 this is not the case!)
the solution is to add a additional module `full-icu` and a ENV. tried it with this image

![map3](https://user-images.githubusercontent.com/6493772/140661728-5159bd9f-8f3b-4914-8f9e-98a19e8adec2.png)

looks fine!

now i will make the PR.

**Comment by Rubber1Duck** [comment]
@marlon360 : Marlon are you not running the same Dockercontainer on your server? I realy dont understand why on your API all looks fine , and if selfhosted not!

**Comment by marlon360** [comment]
> @marlon360 : Marlon are you not running the same Dockercontainer on your server? I realy dont understand why on your API all looks fine , and if selfhosted not!

I switched to railway.app for hosting the api. They use a heroku container. This is the deployment log:

> 20: Pulling from heroku/buildpacks
Digest: sha256:7cb3a4b114f017e09f477da01c461fb2506a8e70d7385a2f2f1d36b09244205e
Status: Image is up to date for heroku/buildpacks:20
20: Pulling from heroku/pack
Digest: sha256:5642f5ab128c749b8c40cf78698cb7ed2fa25791dea0772f794ec8da705faada
Status: Image is up to date for heroku/pack:20
===> DETECTING
heroku/nodejs-engine     0.7.4
heroku/nodejs-npm        0.4.4
heroku/nodejs-typescript 0.2.3
heroku/procfile          0.6.2
===> ANALYZING
Previous image with name "registry.railway.app/cd631ff9-b32b-4efc-acb6-fb5efd0ef9cc" not found
===> RESTORING
===> BUILDING
[INFO] Node.js Buildpack
[INFO] Setting NODE_ENV to production
[INFO] Installing toolbox
[INFO] - yj
[Installing Node]
[INFO] Getting Node version
[INFO] Resolving Node version
[INFO] Downloading and extracting Node v16.13.0
...
