### ISSUE TITLE
Issue with https://api.corona-zahlen.org/districts/09771/history/cases/10

### ISSUE THREAD

**Issue by JonathanN1203** [marlon360/rki-covid-api#319]
Hi,

if I try to call this URL https://api.corona-zahlen.org/districts/09771/history/cases/10 I get the error that the url of the RKI API is wrong.
![image](https://user-images.githubusercontent.com/50752465/140704957-a2b60956-4201-4ffa-bac0-5db2ccf3e92f.png)

**Comment by Toni-99** [comment]
Same at /germany Endpoint
> https://api.corona-zahlen.org/germany
![grafik](https://user-images.githubusercontent.com/71496013/140718278-2d74f22d-3788-40d5-b4b8-83dea413a0b6.png)

**Comment by Rubber1Duck** [comment]
Hello,

as the error report sounds out, this is a problem with the official RKI API. 
try again later!

**Comment by marlon360** [comment]
At the moment it is not possible to query the data.
This request is not working:
https://services7.arcgis.com/mOBPykOjAyBO2ZKk/arcgis/rest/services/RKI_COVID19/FeatureServer/0/query?where=NeuerFall%20IN(1,0)&objectIds=&time=&resultType=standard&outFields=AnzahlFall,MeldeDatum&returnIdsOnly=false&returnUniqueIdsOnly=false&returnCountOnly=false&returnDistinctValues=false&cacheHint=false&outStatistics=[{"statisticType":"sum","onStatisticField":"AnzahlFall","outStatisticFieldName":"cases"},{"statisticType":"max","onStatisticField":"MeldeDatum","outStatisticFieldName":"date"}]&having=&resultOffset=&resultRecordCount=&sqlFormat=none&f=json&token=

Maybe the dataset is getting too big. Let's see if this gets resolved by the RKI, if not we have to find alternatives.

**Comment by JonathanN1203** [comment]
it seems that it's working now but really slow

**Comment by csigritz** [comment]
Seems like it's working again without any problems

**Comment by Rubber1Duck** [comment]
@JonathanN1203 this issue can be closed i think!

**Comment by JonathanN1203** [comment]
@Rubber1Duck yes sure
