### ISSUE TITLE
after moved vercel to docker 502 and 504 error

### ISSUE THREAD

**Issue by srt10coupe** [marlon360/rki-covid-api#32]
see headline

**Comment by marlon360** [comment]
Yes I am aware of that.
Unfortunately I reached my Vercel quota, so I have to move to another sever. But the traffic is so high, that the server cannot handle it. Now I am working on a caching system.

**Comment by srt10coupe** [comment]
your json api is great, what did you expect - of course the rush is big :)

**Comment by marlon360** [comment]
This is resolved.
In the long term the URL will be replaced with [https://rki.marlon-lueckert.de/](https://rki.marlon-lueckert.de/)
So use this instead.

**Comment by srt10coupe** [comment]
Thx :))
