### ISSUE TITLE
Any chance for "accurat" historical data ?

### ISSUE THREAD

**Issue by Creat1veM1nd** [marlon360/rki-covid-api#320]
Hello,

I understand the mechanism of historical data being changed, but I wondered where to get then "accurat" historical data when one starts an app from scratch. 
Since I do want to construct my own statistics, I would like to get some data. But to have a chance to do comparisions to last week or something like that, I do need good data. 

I saw in other apps that they all have the same number of cases, e.g. +52 for a last day, +62 the day before and +85 another day before. The api call of the history of that district does not provide these numbers, for known reasons. 

Now I wonder how to get those numbers, which are shown in the apps. Is there any chance or is the only option to get data of cases of day before on a daily basis and save them in a DB, which would mean that I do not can do comparisions right away but have to wait at least a week ?

Thanks in advance for any answer.

**Comment by Rubber1Duck** [comment]
Hello,

what you are searching for is in this excelsheet
[https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Daten/Fallzahlen_Kum_Tab.html](https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Daten/Fallzahlen_Kum_Tab.html)
This are the called "frozen" Values. This API is only providing the frozen-incidence Values at this time! eg.:  [https://api.corona-zahlen.org/districts/history/frozen-incidence](https://api.corona-zahlen.org/districts/history/frozen-incidence)

**Comment by Creat1veM1nd** [comment]
Hello,

thanks for the link. But as far as I can see there are only numbers added up for the last 7 days each cell. I was not able to get the true increase from that so far. According to the explanations there should be a table with daily numbers but I can not find it the worksheet at all. I will keep digging.

**Comment by Rubber1Duck** [comment]
Hello,
you are right daily cases and death are only provided for germany not for states and districts ..........
For states and districts only the 7day cases and 7 day incidence is provided!

**Comment by Creat1veM1nd** [comment]
Glad to hear that I was not blind :-)

I will go with the solution to fetch new cases on a daily basis and store them in a DB. 

Thanks for your help!

**Comment by Rubber1Duck** [comment]
Close this issue please!
