### ISSUE TITLE
Returns http status code 200 on error

### ISSUE THREAD

**Issue by KaktusXY** [marlon360/rki-covid-api#321]
Currently there is a problem with the Official-RKI-API.
The Official-RKI-API returns error code 400, but this api returns status code 200, when it shouldn't, because there is obviously a problem.

![grafik](https://user-images.githubusercontent.com/58702689/140774979-1c89ba19-8a87-4d76-9aee-affe6df5bf67.png)

**Comment by JonathanN1203** [comment]
take a look at this issue https://github.com/marlon360/rki-covid-api/issues/319

**Comment by KaktusXY** [comment]
> 
> 
> take a look at this issue #319

the reason for this issue is not the right now not working api, but rather the http status code it returns (it returns code 200 when it shouldn't)

**Comment by Rubber1Duck** [comment]
because of that the error is catched, the resposecode for you is 200! that`s not realy fine .......

**Comment by Rubber1Duck** [comment]
Reopend this Issue, because a patch is now availible....
