### ISSUE TITLE
Krankenhausampel.info - Skript für Webseitenbetreiber

### ISSUE THREAD

**Issue by mario-fliegner** [marlon360/rki-covid-api#322]
Krankenhausampel.info - Die Krankenhausampel für einen (beliebigen) Landkreis als freies und anpassbares Skript für alle Webseitenbetreiber. Pures HTML/CSS und JavaScript, damit ist die Ampel "Screenreader" tauglich und auch für Menschen mit Rot-Grün-Schwäche gibt es eine Option zur Anzeige der Farbnamen (quasi Barrierefrei). 

Findet bereits auf vielen Webseiten von Feuerwehren (hauptsächlich in Bayern) sowie auch Gemeinde-Webseiten Verwendung.

**Comment by JonathanN1203** [comment]
Servus,

ich finde die Idee deines Scripts echt gut. Gibt es irgendwie die Möglichkeit automatisch die Grenzwerte von einem Landkreis auszulesen?

**Comment by mario-fliegner** [comment]
Hi @JonathanN1203 ,
vorbereitet habe ich Möglichkeit zwar schon, allerdings nur auf Bundeslandebene. Die Grenzwerte muss man sich IMHO von jedem Bundesland und/oder Landkreis (sofern verfügbar) manuell selbst ermitteln. Eine Seite oder API, wo alle aktuellen Grenzwerte abgegriffen werden können, ist mir nicht bekannt.

**Comment by JonathanN1203** [comment]
Hi,

ok schade
