### ISSUE TITLE
Germany return error 

### ISSUE THREAD

**Issue by EmBeEins** [marlon360/rki-covid-api#325]
Request error-code 503

https://api.corona-zahlen.org/germany

**Comment by Toni-99** [comment]
![grafik](https://user-images.githubusercontent.com/71496013/141265899-daa5d9af-866b-4d58-a349-e00ec8254064.png)

**Comment by marlon360** [comment]
This is resolved

**Comment by marlon360** [comment]
The endpoint https://api.corona-zahlen.org/germany does not work.

But https://api.corona-zahlen.org/germany/ works.

**Comment by marlon360** [comment]
flushing redis cache resolved the issue
