### ISSUE TITLE
Im New and i have some Problem

### ISSUE THREAD

**Issue by EvilCart** [marlon360/rki-covid-api#328]
Hey there im very new to API and i tried my best to get it work but it wont work if someone could please help me

Here is my Project code in just HTML if someone feels free to take a look and maybe help me out

https://pastebin.com/Vfy3N7Kv

**Comment by marlon360** [comment]
Hey @EvilCart,

you did not set the `id`s on the HTML elements. That's why it cannot find the elements with: `document.getElementById("weekIncidence")`

Here is a working example of your code:
https://codesandbox.io/s/infallible-silence-yiv1n
