### ISSUE TITLE
ARM Version

### ISSUE THREAD

**Issue by dontobi** [marlon360/rki-covid-api#340]
Ich würde gerne den Docker Container auf meinem Raspberry Pi 4 laufen lassen. Leider ist die ARM Architektur nicht unterstützt. Wäre es möglich die Unterstützung von ARM nachzureichen?

**Comment by marlon360** [comment]
@Rubber1Duck Auf deinem Raspberry funktioniert es, oder?

**Comment by dontobi** [comment]
Laut Docker Hub wird lediglich linux/amd64 unterstützt. Ich habe gerade das Compose File geladen und der Container startet bei mir nicht.

**Comment by marlon360** [comment]
@dontobi Du kannst versuchen die erste Zeile im Dockerfile zu ändern:
`FROM arm64v8/node:16-alpine3.12`

**Comment by dontobi** [comment]
Ich versuche mal einen PR hin zu bekommen, damit alle künftigen Releases mit ARM Support kommen.

**Comment by Rubber1Duck** [comment]
ja das klappt astrein!
ich habe docker files für arm64, armv7 und armv6 auf raspberrys 1,2,3 und 4 getested (sollte aber auch auf deren clones laufen) in meinem docker hub repository
allerdings sind sie nicht zu 100 % funktional gleich zu diesem hier, habe an einigen ecken und kanten rumgebastelt.
wenn du es probieren möchtest
ändere `image: marlon360/rki-covid-server:v2` in `image: rubber4duck/rki-api`

kann aber eine exakte kopie zu dieser hier gleich erzeugen dauert nur ein bischen .................

**Comment by Rubber1Duck** [comment]
> Ich versuche mal einen PR hin zu bekommen, damit alle künftigen Releases mit ARM Support kommen.

gab es schonmal ........... #99

**Comment by Rubber1Duck** [comment]
> @dontobi Du kannst versuchen die erste Zeile im Dockerfile zu ändern: `FROM arm64v8/node:16-alpine3.12`

selfbuild geht natürlich auch ......

**Comment by dontobi** [comment]
Okay. Dann spar ich mir die Mühe für ein PR.

**Comment by Rubber1Duck** [comment]
wie marlon schon geschrieben hat kannst du die erste zeile im Dockerfile ändern, und dann das image auf dem raspberry bauen! dauert aber da libvips komplett compiliert werden muss ..................

**Comment by dontobi** [comment]
Ich teste es mal mit dem Container von dir. Sollte das laufen (wovon ich ausgehe), dann werde ich nicht selber bauen müssen. Vielen Dank.

**Comment by Rubber1Duck** [comment]
in ca 30 Minuten steht ein Docker image unter dem namen rubber4duck/rki-covid-server-arm:v2 auf Dockerhub bereit, welches eine exakte Kopie dieses Repositorys ist!

**Comment by Rubber1Duck** [comment]
done, image steht bereit!

**Comment by Rubber1Duck** [comment]
klabbet ? :-)

**Comment by dontobi** [comment]
Ja, hat geklappt. Danke nochmal.
