### ISSUE TITLE
Error on states endpoint

### ISSUE THREAD

**Issue by marcusraitner** [marlon360/rki-covid-api#345]
Probably a problem with the RKI files … 

I get the following when calling `https://api.corona-zahlen.org/states`

`{"error":{"message":"There is a problem with the official RKI API.","rkiError":{"code":400,"message":"","details":["Unable to perform query. Please check your parameters."]},"url":"https://services7.arcgis.com/mOBPykOjAyBO2ZKk/arcgis/rest/services/RKI_COVID19/FeatureServer/0/query?where=NeuGenesen IN(1,0)&objectIds=&time=&resultType=standard&outFields=AnzahlGenesen,MeldeDatum,IdBundeland&returnIdsOnly=false&returnUniqueIdsOnly=false&returnCountOnly=false&returnDistinctValues=false&cacheHint=false&orderByFields=IdBundesland&groupByFieldsForStatistics=IdBundesland&outStatistics=[{\"statisticType\":\"sum\",\"onStatisticField\":\"AnzahlGenesen\",\"outStatisticFieldName\":\"recovered\"},{\"statisticType\":\"max\",\"onStatisticField\":\"MeldeDatum\",\"outStatisticFieldName\":\"date\"}]&having=&resultOffset=&resultRecordCount=&sqlFormat=none&f=json&token="}}`

**Comment by Rubber1Duck** [comment]
#341 #342

**Comment by marcusraitner** [comment]
Sorry! Had a look at the issue list before opening, but didn't find those.

**Comment by marcusraitner** [comment]
Is working again
