### ISSUE TITLE
Hospitalisierungsrate auch bei Landkreisen zur Verfügung stellen

### ISSUE THREAD

**Issue by olebohmbach** [marlon360/rki-covid-api#352]
Die Hospitalisierungsrate auch bei Landkreisen zur Verfügung stellen, Nicht nur bei den Bundesländern oder ganz Deutschland.

**Comment by JonathanN1203** [comment]
hast du davon zufällig nen link, unter dem finde ich nix https://raw.githubusercontent.com/robert-koch-institut/COVID-19-Hospitalisierungen_in_Deutschland/master/Aktuell_Deutschland_COVID-19-Hospitalisierungen.csv

**Comment by olebohmbach** [comment]
Ich habe leider keinen gefunden

**Comment by SystemKeeper** [comment]
https://github.com/robert-koch-institut/COVID-19-Hospitalisierungen_in_Deutschland/issues/2

**Comment by Rubber1Duck** [comment]
Sollte erledigt sein ....
