### ISSUE TITLE
Frage/Dokumentation: Historische Entwicklung Reproduktionszahl/Impffortschritt/Altersverteilung

### ISSUE THREAD

**Issue by nikos** [marlon360/rki-covid-api#353]
Ist es geplant auch die *historischen* Verläufe (soweit man da drankommt) für den: 
* R-Wert
* Impfquote (pro Bundesland?)
* Altersverteilung (pro Bundesland?)

bereitzustellen?

**Comment by Rubber1Duck** [comment]
Eine Lösung für die R-Wert Historie hat es mal gegeben, jedoch bevor diese in den code eingeflossen ist, hat es massive Änderungen zur Ermittlung des R-Wertes gegeben (umstieg von Exceldatei auf guthub-csv) (das RKI veröffentlich keine 4 Tages r-Werte mehr).
Somit ist der patch zur Zeit nicht zu gebrauchen. Da müsst nochmal jemand Hand anlegen und das auf die jetzt geltenenden Umstände anpassen!

zu den historischen Verläufen der Impfquote und der Altersverteilung kenne ich keine Datenquelle die das bereitstellen würde.
Es gibt Archiv Dateien des RKI zurückgehend bis zum 21.7.2021, diese könnte man einzeln auswerten und sich somit den Verlauf erstellen (zumindest ab 21.7.2021) aber on the fly ist das nicht mit vernümpftigen Antwortzeiten zu relisieren OHNE die Werte dauerhaft zu speichern. Das wäre dann eher was für eine Anwendung als für eine API!
