### ISSUE TITLE
Request // Impfquoten je Landkreis

### ISSUE THREAD

**Issue by EmBeEins** [marlon360/rki-covid-api#354]
Impfquoten auf Landkreis-Ebene

https://github.com/robert-koch-institut/COVID-19-Impfungen_in_Deutschland#variablen-1

**Comment by ninja-warrior** [comment]
Achtung: Mit den Zahlen lässt sich keine Impfquote je Landkreis ermitteln. Die Zahlen bündeln die Impfungen nur nach der Örtlichkeit, an der die Impfung durchgeführt wurde. (siehe auch Hinweis im Link)

**Comment by Rubber1Duck** [comment]
Wie schon geschrieben ist eine Quote nicht möglich, Anzahl der impfungen je Landkreis aber schon, fragt sich nur wie nützlich die dann noch sind.

**Comment by Kolap5s** [comment]
Hallo an alle,

weiss jemand ob es irgendwo genaue Daten zur Altersverteilung bei den Impfungen (total, erst, zweit, dritt) seit Beginn der Impfkampagne gibt? Beim RKI gibt es nur eine relative Impfverteilung nach Altersgruppen (<18, 18-60, 60+) ab dem 17.9.2021 aber keine Informationen davor. Ideal wäre eine Aufteilung von Impfquoten bzw. absoluten Zahlen per Alterskategorie 0-15, 15-30, 30-45, etc. aber Beginn der Impfungen Ende letzten Jahres. Weiss jemand was??

**Comment by Rubber1Duck** [comment]
Impfquoten auf Landkreisebene sind nicht zu ermitteln, siehe dazu auch das README im repository [https://github.com/robert-koch-institut /
[COVID-19-Impfungen_in_Deutschland](https://github.com/robert-koch-institut/COVID-19-Impfungen_in_Deutschland)](https://github.com/robert-koch-institut /
[COVID-19-Impfungen_in_Deutschland](https://github.com/robert-koch-institut/COVID-19-Impfungen_in_Deutschland))
