### ISSUE TITLE
Telegram Chatbot 

### ISSUE THREAD

**Issue by DerKutscher** [marlon360/rki-covid-api#355]
Covid Landkreis Zahlen Chatbot auf Telegram https://t.me/COVID_19_GER_bot

Für eine schnelle und einfache Möglichkeit die Wichtigsten Zahlen für einzelne Landkreise abzufragen. 

Danke für die API. Hat mir sehr geholfen alle zahlen einzubinden ;)

**Comment by Toni-99** [comment]
Hey, i dont want to make some ads but CoronaBot has its own Telegram Bot, that you can find by the name @GER_CoronaBot

**Comment by Toni-99** [comment]
Bro ich finde Konkurrenz super aber kennst du schon @GER_CoronaBot? Ist die Telegram Version meines Bots. Kannst du dir ja gern mal ansehen 👌🏻

> https://t.me/GER_CoronaBot

**Comment by DerKutscher** [comment]
Danke für deinen Hinweis. allerdings würde ich nicht von Konkurrenz sprechen ;) denke jedes tool hilft derzeit. Zudem verfolgen wir unterschiedliche nutzungsformen und somit Vorteile für unterschiedliche nutzergruppen.
