### ISSUE TITLE
frozen-incidence history (days): number of results

### ISSUE THREAD

**Issue by csigritz** [marlon360/rki-covid-api#356]
Currently the URL https://api.corona-zahlen.org/states/HH/history/frozen-incidence/7 gives us a result of 3 entries:
```json
{
  "data": {
    "HH": {
      "abbreviation": "HH",
      "name": "Hamburg",
      "history": [
        {
          "weekIncidence": 196.81745208310167,
          "date": "2021-11-23T00:00:00.000Z"
        },
        {
          "weekIncidence": 186.884810507871,
          "date": "2021-11-24T00:00:00.000Z"
        },
        {
          "weekIncidence": 185.37332157251,
          "date": "2021-11-25T00:00:00.000Z"
        }
      ]
    }
  },
  "meta": {
    "source": "Robert Koch-Institut",
    "contact": "Marlon Lueckert (m.lueckert@me.com)",
    "info": "https://github.com/marlon360/rki-covid-api",
    "lastUpdate": "2021-11-25T09:42:44.000Z",
    "lastCheckedForUpdate": "2021-11-29T07:47:16.215Z"
  }
}
```

Last week the RKI changed the publishing frequency of the parsed xlsx file from daily to weekly:
https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Fallzahlen.html

> Hinweis: Diese Exceldatei wird ab dem 25.11.2021 wöchentlich jeden Donnerstag aktualisiert statt wie bisher arbeitstäglich.

Is this the intended behavior? Or should it give 7 entries up to the last known date?

**Comment by HappyFr1tz** [comment]
As far as I know, the API looks from today's date to the last seven days. If there are a few days without data, they are missing from the API and have gaps. The same problem is also with the history for vaccinations. However, a solution is currently being worked on, see: #351

**Comment by csigritz** [comment]
@HappyFr1tz Thx. Then my ticket is a duplicate and i will close it.
