### ISSUE TITLE
Wrong delta cases (all data is not updated today!)

### ISSUE THREAD

**Issue by Friedi1970** [marlon360/rki-covid-api#362]
When I get the delta cases of Bamberg Landkreis I am getting the number of yesterday. The last update was 2021-12-09T00:00:00.000Z, though.

All delivered numbers are from the day before. There was no update.

`{"data":{"09471":{"ags":"09471","name":"Bamberg","county":"LK Bamberg","state":"Bayern","population":147497,"cases":11899,"deaths":172,"casesPerWeek":952,"deathsPerWeek":0,"stateAbbreviation":"BY","recovered":8527,"weekIncidence":645.4368563428409,"casesPer100k":8067.282724394395,"delta":{"cases":171,"deaths":3,"recovered":93}}},"meta":{"source":"Robert Koch-Institut","contact":"Marlon Lueckert (m.lueckert@me.com)","info":"https://github.com/marlon360/rki-covid-api","lastUpdate":"2021-12-09T00:00:00.000Z","lastCheckedForUpdate":"2021-12-09T04:23:54.356Z"}}`

**Comment by Rubber1Duck** [comment]
it seems thats a issue at RKI!
The Dashboard shows up a new incidence of 338.1!!!!! (yesterday 427 !)
The arcis database and the csv on github seems to be updated but it is not! it is the same data as of yesterday!
dont panic :-) i think they will do a update ..................

**Comment by Friedi1970** [comment]
> dont panic :-) 

I won't 🤣 
I just thought it may caused by the API.

**Comment by Rubber1Duck** [comment]
The RKI fixed the issue! if the data of the api is not actual, this is because the redis cache is not flushed! just wait 30 minutes ...........

**Comment by Friedi1970** [comment]
Hmm 🧐 It is again the numbers of yesterday…

**Comment by Rubber1Duck** [comment]
as you can se here [https://services7.arcgis.com/mOBPykOjAyBO2ZKk/arcgis/rest/services/rki_service_status_v/FeatureServer/0/query?where=1%3D1&objectIds=&time=&resultType=none&outFields=*&returnIdsOnly=false&returnUniqueIdsOnly=false&returnCountOnly=false&returnDistinctValues=false&cacheHint=false&orderByFields=&groupByFieldsForStatistics=&outStatistics=&having=&resultOffset=&resultRecordCount=&sqlFormat=none&f=html&token=](https://services7.arcgis.com/mOBPykOjAyBO2ZKk/arcgis/rest/services/rki_service_status_v/FeatureServer/0/query?where=1%3D1&objectIds=&time=&resultType=none&outFields=*&returnIdsOnly=false&returnUniqueIdsOnly=false&returnCountOnly=false&returnDistinctValues=false&cacheHint=false&orderByFields=&groupByFieldsForStatistics=&outStatistics=&having=&resultOffset=&resultRecordCount=&sqlFormat=none&f=html&token=)

the database this api uses is not fully upgraded 
![status_DB](https://user-images.githubusercontent.com/6493772/145534757-75eba12f-6c7f-4978-bf9b-86baed27b0b4.png)

from time to time this happend :-(

we have to wait ....................

**Comment by Friedi1970** [comment]
Ah, got you.
So I will postpone my notifier to 9 instead of 6.

**Comment by Friedi1970** [comment]
> we have to wait ....................

I wonder if it would be possible to deliver a datum whether the data has already been updated, update is running and maybe an error?
I mean, at the moment it is impossible to decide whether the data has been updated or not. The timestamp is not useful :(

**Comment by Rubber1Duck** [comment]
You are right, it is impossible ............. for the API too!
it is very difficult to decide that (if the data is updated or not) and at the moment that maybe possible logic is not coded! 

p.s. sorry for answering so late ....... i was on vacation the last days

**Comment by Friedi1970** [comment]
That‘s really sad :(

**Comment by Rubber1Duck** [comment]
i think we can close this Issue!?
