### ISSUE TITLE
Wrong vaccination quote data

### ISSUE THREAD

**Issue by hajo62** [marlon360/rki-covid-api#366]
https://api.corona-zahlen.org/vaccinations
```
data |  
administeredVaccinations | 143183952
vaccinated | 61091561
vaccination |  
biontech | 43422889
moderna | 4844721
astraZeneca | 9264073
janssen | 3559878
delta | 75855
quote | 271129.02
```
Quote wrong for Germany as well as for States and other quotes like boostered which reports 86,1% for Germany.

I'm not sure which rki table exactly is used, but the vaccination table show i.e for Germany 70,4 %...

**Comment by Rubber1Duck** [comment]
The RKI added a column .............
