### ISSUE TITLE
Datenaufbau "cases/recovered - delta/omnicron"

### ISSUE THREAD

**Issue by nics-on** [marlon360/rki-covid-api#368]
Zunächst vielen Dank für die Bereitstellung der API.

Mir fiel auf dass die Genesenen unter https://api.corona-zahlen.org/germany/history/recovered  sehr rückläufig sind.
Bsp.
`{"recovered":723,"date":"2021-12-20T00:00:00.000Z"}`
vs
`{"recovered":7503,"date":"2021-05-21T00:00:00.000Z"}`

Parallel dazu gibt es bei "Delta" Genesenen unter https://api.corona-zahlen.org/germany , mehr Genesene als Erkrankte.

`"delta":{"cases":22214,"deaths":157,"recovered":38546}`

Frage:

/germany/history/cases = beinhaltet ALLE Fälle inkl. Delta & Omnicron ?
/germany/history/recovered = beinhaltet KEINE Delta/Omnicron- recovered

![image](https://user-images.githubusercontent.com/28743943/147381805-ee1e3725-615f-42ad-8c7f-83c29efc4579.png)

Im offiziellen RKI Dashboard werden offensichtlich nur noch die Werte aus "Delta" verwendet?

![image](https://user-images.githubusercontent.com/28743943/147381470-d3709f20-f428-4e2d-a353-afc62d5004d7.png)
https://experience.arcgis.com/experience/478220a4c454480e823b17327b2bf1d4/page/Landkreise/

Letzte Frage: Gibt es auch schon die Omnikron Daten? https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Situationsberichte/Omikron-Faelle/Omikron-Faelle.html?__blob=publicationFile

Vielen Dank vorab!

**Comment by Rubber1Duck** [comment]
Frohe Weihnachten allen!

in der gesamten API findet KEINE Unterscheidung zwischen den verschiedenen Corona Varianten statt!
das "delta" unter /germany beschreibt nicht die Corona Variante "Delta" sondern den Unterschied zum Vortag! Heute wurden also für gestern 38.546 neu Genesene "angenommen" (siehe hierzu auch die Erklärung des RKI)
`Hinweis zu Genesenen
Anhand der dem RKI von den Gesundheitsämtern übermittelten Detailinformationen zu einem Erkrankungsfall wird für jeden Fall eine Dauer der Erkrankung geschätzt. Für Fälle, bei denen nur Symptome angegeben sind, die auf einen leichten Erkrankungsverlauf schließen lassen, wird eine Dauer der Erkrankung von 14 Tagen angenommen. Bei hospitalisierten Fällen oder Fällen mit Symptomen, die auf einen schweren Verlauf hindeuten (z. B. Pneumonie) wird eine Dauer der Erkrankung von 28 Tagen angenommen. Ausgehend vom Beginn der Erkrankung, bzw. wenn dieser nicht bekannt ist, vom Meldedatum ergibt sich ein geschätztes Datum der Genesung für jeden Fall. Da im Einzelfall auch deutlich längere Erkrankungsverläufe möglich sind, bzw. die hier genutzten Informationen nicht bei allen Fällen dem RKI übermittelt werden, sind die so berechneten Daten nur grobe Schätzungen für die Anzahl der Genesenen und sollten daher auch nur unter Berücksichtigung dieser Limitationen verwendet werden.` 
Genesene werden nicht wirklich erfasst sondern anhand der Zeit angenommen.
in der Historie werden diese 38.546 Genesene jedoch nicht alle an einem Tag geführt sondern auf die entsprechenden Tage seit dem Erkrankungsbeginn, sofern bekannt, bzw. auf das Meldedatum verteilt.
Die Historie wird sich also mit der Zeit verändern. Deine blaue Linie wird sich mit der Zeit immer weiter der orangenen Linie nähern, so wie es bis Anfang Dezember schon der Fall ist. Alle history Daten bis auf frozen-Incidence sind dynamische Daten die sich vor allem in den vergangenen 2 Wochen fast täglich ändern! Für die Genesenen gibt es leider keine entsprechende Grafik auf dem Dashboard, aber anhand der Neuen Faälle kann man das dort auch gut sehen:
22.214 neue Fälle (alle Virusvarianten!)
Diese verteilen sich (Stand heute) auf folgende Tage (Erkrankungsdatum, wenn bekannt, bzw. Meldedatum)
heute 14.710
![fälleheute1](https://user-images.githubusercontent.com/6493772/147383945-c543d03c-bbd1-47e4-99d0-f9adfea2e817.png)
gestern 6.280
![fälleheute2](https://user-images.githubusercontent.com/6493772/147383958-eaa363fd-b130-4a43-bb28-a7374c0cb5a0.png)
vorgestern 925
![fälleheute3](https://user-images.githubusercontent.com/6493772/147383994-fd3acb5d-057c-4f87-9f68-482c520e2b83.png)
usw.

Hier nun noch auf welche Tage sich die 38.546 neu Genesenen verteilen (zu den bereits an diesen Tagen genesenen!) (Minus Werte sind korrekturen!):
+-------+------------+
| value | date       |
+-------+------------+
|     1 | 2020-10-13 |
|    -1 | 2020-11-18 |
|     1 | 2020-11-26 |
|     1 | 2020-11-29 |
|     1 | 2020-12-03 |
|     1 | 2020-12-12 |
|     1 | 2020-12-13 |
|     1 | 2020-12-14 |
|    -1 | 2020-12-17 |
|    -1 | 2020-12-28 |
|    -3 | 2020-12-29 |
|    -4 | 2020-12-30 |
|    -1 | 2020-12-31 |
|    -1 | 2021-01-05 |
|    -2 | 2021-01-06 |
|    -2 | 2021-01-07 |
|     0 | 2021-01-08 |
|    -1 | 2021-01-09 |
|     1 | 2021-01-12 |
|     2 | 2021-01-13 |
|    -1 | 2021-01-26 |
|    -1 | 2021-01-29 |
|    -1 | 2021-02-03 |
|    -2 | 2021-03-25 |
|     1 | 2021-04-14 |
|    -1 | 2021-04-29 |
|     1 | 2021-05-03 |
|     1 | 2021-05-17 |
|     1 | 2021-05-26 |
|     1 | 2021-07-14 |
|    -1 | 2021-07-16 |
|    -1 | 2021-08-28 |
|     1 | 2021-09-01 |
|     1 | 2021-09-18 |
|    -1 | 2021-09-24 |
|     1 | 2021-09-26 |
|     1 | 2021-09-28 |
|     1 | 2021-10-04 |
|     1 | 2021-10-08 |
|    -1 | 2021-10-10 |
|     1 | 2021-10-13 |
|     1 | 2021-10-14 |
|     1 | 2021-10-16 |
|    -1 | 2021-10-24 |
|     0 | 2021-10-25 |
|     0 | 2021-10-27 |
|     2 | 2021-10-29 |
|     0 | 2021-10-30 |
|     0 | 2021-10-31 |
|     1 | 2021-11-01 |
|     4 | 2021-11-02 |
|     1 | 2021-11-03 |
|     2 | 2021-11-04 |
|    -2 | 2021-11-05 |
|     1 | 2021-11-06 |
|    -1 | 2021-11-07 |
|     1 | 2021-11-08 |
|     2 | 2021-11-09 |
|     1 | 2021-11-10 |
|    -4 | 2021-11-11 |
|    -2 | 2021-11-12 |
|    -2 | 2021-11-13 |
|     1 | 2021-11-14 |
|     1 | 2021-11-15 |
|    -2 | 2021-11-16 |
|     0 | 2021-11-17 |
|     1 | 2021-11-18 |
|    -2 | 2021-11-19 |
|    -3 | 2021-11-20 |
|     1 | 2021-11-21 |
|     4 | 2021-11-22 |
|     2 | 2021-11-23 |
|     9 | 2021-11-24 |
|    16 | 2021-11-25 |
|    53 | 2021-11-26 |
| 18502 | 2021-11-27 |
|   167 | 2021-11-28 |
|   516 | 2021-11-29 |
|  1109 | 2021-11-30 |
|   865 | 2021-12-01 |
|   499 | 2021-12-02 |
|   300 | 2021-12-03 |
|   147 | 2021-12-04 |
|    82 | 2021-12-05 |
|    88 | 2021-12-06 |
|    90 | 2021-12-07 |
|    98 | 2021-12-08 |
|    83 | 2021-12-09 |
|   140 | 2021-12-10 |
|  8493 | 2021-12-11 |
|   346 | 2021-12-12 |
|   822 | 2021-12-13 |
|  2264 | 2021-12-14 |
|  1865 | 2021-12-15 |
|  1035 | 2021-12-16 |
|   518 | 2021-12-17 |
|   139 | 2021-12-18 |
|    38 | 2021-12-19 |
|    98 | 2021-12-20 |
|    75 | 2021-12-21 |
|    48 | 2021-12-22 |
|    27 | 2021-12-23 |
|    11 | 2021-12-24 |
+-------+------------+

Edit: zu deiner letzten Frage ob es schon die omikron daten in der Api gibt: Nein, bis jetzt nicht. Ich weiss auch nicht ob das Sinn ergibt, heute ist es Omikron, morgen phi oder sonstwas ...................... und mir ist zur Zeit keine Datenquelle bekannt welche sich durch diese Api "gut" auswerten liesse ..........

**Comment by nics-on** [comment]
Wünsche natürlich auch frohe Weihnachten.
@Rubber1Duck , vielen Dank das löst den Knoten ;)
Das war wohl ein klassisches Missverständnis, "delta" ist dann als Variablenbezeichnung etwas ungünstig "geworden" :)

Vielen Dank & schöne Feiertage noch 🤝
