### ISSUE TITLE
Newest Excelsheet for frozen-incidence values for districts is faulty

### ISSUE THREAD

**Issue by Rubber1Duck** [marlon360/rki-covid-api#369]
The RKI struck again.
![frozen-incidence4](https://user-images.githubusercontent.com/6493772/147479786-ff9d5743-27a3-476c-bab5-1c264b9c4003.png)
as you can see they dont fill the first row with dates for the last 7 days! :-(
so there are no values for the last 7 days for districts!
Germany and states works fine!

**Comment by marlon360** [comment]
<img width="963" alt="Bildschirmfoto 2021-12-30 um 21 31 38" src="https://user-images.githubusercontent.com/11810704/147786165-7f6814d9-90a0-4771-8446-77c446c2d214.png">

I think they fixed it. But thanks for opening the issue!
