### ISSUE TITLE
Home Assistant integration

### ISSUE THREAD

**Issue by thebino** [marlon360/rki-covid-api#37]
Home Assistant Integration (https://github.com/thebino/rki_covid)

I built an integration for Home Assistant where users can track and monitor their districts and create automations based on these numbers.

<img width="905" alt="rki_covid" src="https://user-images.githubusercontent.com/841681/101992938-e8a87280-3cb6-11eb-84a8-86628c858fdb.png">

**Comment by marlon360** [comment]
Hi @thebino 
Awesome work, thanks for using my API!

Could you change the base url to [https://rki.marlon-lueckert.de](https://rki.marlon-lueckert.de). This url will work in the long term. The other one will be shutdown in a few weeks.

**Comment by thebino** [comment]
@marlon360 Base url adjusted 👍

**Comment by marlon360** [comment]
Awesome!

PR is merged.
