### ISSUE TITLE
District History Values

### ISSUE THREAD

**Issue by erbse83** [marlon360/rki-covid-api#371]
Hallo!
ich habe festgestellt, dass die History-Werte der Inzidenzen meines Landkreises in den Daten (https://api.corona-zahlen.org/districts/05774/history/incidence/4) nicht mit den Werten der Realität übereinstimmen... 
Die tagesaktuellen Daten stimmen, aber in der History sind ganz andere Werte vorhanden. Ich beobachte das nun schon mehrere Tage... 
Ist das etwas bekannt oder mache ich einen Fehler?!

**Comment by marlon360** [comment]
Duplicate #64

**Comment by erbse83** [comment]
oh! ok. Thanks. happy new Year! And thanks for your work!

**Comment by marlon360** [comment]
You can use the frozen-incidence endpoint: https://api.corona-zahlen.org/districts/05774/history/frozen-incidence/14

**Comment by erbse83** [comment]
these values ends a few days before yesterday - is it because of the holidays?

**Comment by Rubber1Duck** [comment]
no it is because the RKI update this values only on mondays look here #351

**Comment by Rubber1Duck** [comment]
thats the last values
MariaDB [dfki]> select date,ags,value from districts where ags='05774' and typeid='8' and date >'2021-12-20';
+------------+-------+----------+
| date       | ags   | value    |
+------------+-------+----------+
| 2021-12-21 | 05774 | 278.2688 |
| 2021-12-22 | 05774 | 276.9715 |
| 2021-12-23 | 05774 | 255.5662 |
| 2021-12-24 | 05774 | 227.3501 |
| 2021-12-25 | 05774 | 199.7827 |
| 2021-12-26 | 05774 | 173.5126 |
| 2021-12-27 | 05774 | 167.0261 |
| 2021-12-28 | 05774 | 168.6477 |
| 2021-12-31 | 05774 | 191.3503 |
| 2021-12-30 | 05774 | 184.5395 |
| 2021-12-29 | 05774 | 172.2152 |
+------------+-------+----------+
11 rows in set (0.038 sec)

**Comment by Rubber1Duck** [comment]
i am working for a workaround but this is not realy easy and needs a lot of Data to calulate these things ........... not sure if marlon whants du implement this ........... (round 1,2 gig Diskspace and 500 MB RAM is needed .............. and a mariadb dockercontainer .......... :-(
