### ISSUE TITLE
probable error ./germany/history/deaths/

### ISSUE THREAD

**Issue by EmBeEins** [marlon360/rki-covid-api#373]
In my opinion, the values are not valid.

https://api.corona-zahlen.org/germany/history/deaths/2

**Comment by Rubber1Duck** [comment]
my "Glaskugel" is out of the home  :-) ............ why do you think they are not valid?

maybe you should read #64 !? witch is pinned at the top of the issues! 

this is already valid for the deaths .....

but maybe you have another issue ?!
