### ISSUE TITLE
Impfquoten machen keinen Sinn?

### ISSUE THREAD

**Issue by shellixa** [marlon360/rki-covid-api#377]
https://api.corona-zahlen.org/vaccinations -> data.states.SN.boosterVaccination.quotes
(Werte vom 09.01.2022)
`*total*` ist größer als `A12-A1`
Zu welchem Wert ist es welche Quote?

Danke für eine Antwort!

**Comment by marlon360** [comment]
Pinging @Rubber1Duck

**Comment by Rubber1Duck** [comment]
Hi Logianer,

did you read the docs? [https://api.corona-zahlen.org/docs/endpoints/vaccinations.html](https://api.corona-zahlen.org/docs/endpoints/vaccinations.html)

```
boosterVaccination.quote Quote of boostered people (legacy)
boosterVaccination.quotes Quotes of boostered people by agegroups
boosterVaccination.quotes.total Quote of boostered people (same as boosterVaccination.quote)
boosterVaccination.quotes.A12-A17 Quote of boostered people with age >=12 to <=17 years
boosterVaccination.quotes.A18+ Quote of boostered people with agegroup >= 18 years
boosterVaccination.quotes.A18+.total Quote of boostered people with age >= 18 years
boosterVaccination.quotes.A18+.A18-A59 Quote of boostered people with age >= 18 to <= 59 years
boosterVaccination.quotes.A18+.A60+ Quote of boostered people with age >= 60 years
```
total = gesamtquote aller Einwohner im Bundesland bzw. gesamt Deutschland
A12-A17 = Quote aller Jugendlichen von 12 - 17 Jahren
A18+.total = Quote aller 18 plus jährigen
A18+.A18-A59 = quote aller Erwachsenen von 18 bis 59 Jahren
A60+ = alle 60+ jährigen .................

ist doch eigentlich nicht so schwer ....  ist die selbe Struktur die das RKI auch in der Exceldatei verwendet
[https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Daten/Impfquotenmonitoring.xlsx?__blob=publicationFile ](https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Daten/Impfquotenmonitoring.xlsx?__blob=publicationFile )

**Comment by shellixa** [comment]
Wer lesen kann ist klar im Vorteil...

**Comment by Rubber1Duck** [comment]
kein Problem ....
