### ISSUE TITLE
Extreme slow response

### ISSUE THREAD

**Issue by Friedi1970** [marlon360/rki-covid-api#378]
When trying to access e.g. https://api.corona-zahlen.org/districts/02000 the response takes a very long time.
I use the API in Home Asistant with a REST sensor and it stops working this morning due to the delay.

**Comment by Rubber1Duck** [comment]
my selfhosted raspi responses normal, so this should be a server issue, or a issue with the transparent proxy!
@shinebar1001 is the proxy running normal?

**Comment by marlon360** [comment]
I switched the server a few months ago. It is not using the proxy server anymore. It is now hosted on railway.app and cached with CloudFlare.

**Comment by marlon360** [comment]
Restarted the server. Hopefully this fixes the issue.
Lately there are some problems with Google Cloud maybe this is related.

**Comment by Friedi1970** [comment]
It seems to be solved :)
Thanks!
