### ISSUE TITLE
Wrong Vaccination Quotes / Fehler der Impfquoten

### ISSUE THREAD

**Issue by nils-mac** [marlon360/rki-covid-api#381]
Hallo,
Die Impfquoten werden falsch angezeigt. 36% mind einfach geimpft, 88.5% mind. zweifach geimpft und 83,2% geboostert kann ja irgendwie nicht sein. Liegt das am Fehler des RKI oder was ist passiert?
Vielen Dank für die Bereitstellung der Daten.
LG

**Comment by Rubber1Duck** [comment]
structure in the excel file is changed, the parser must be patched ..........

**Comment by nils-mac** [comment]
Ok...

**Comment by marcusraitner** [comment]
Bei mir past es wieder.
