### ISSUE TITLE
Project: Covid 19 Statistics Germany

### ISSUE THREAD

**Issue by Yanere** [marlon360/rki-covid-api#383]
Hi Marlon, 

first of all thank you for providing the data. I have created a page that shows the statistics for Germany and individual states. 
Visitors will also find links to the most important topics. Be it information about Covid 19, the vaccination or corona tests.

https://covid19ger.netlify.app/

P.s enjoy the coffee 😄

**Comment by marlon360** [comment]
Great job! Thanks for submitting your project!

Thank you very much! But also a shoutout to @Rubber1Duck for his contributions!

**Comment by Yanere** [comment]
Oh i forgot, thank you @Rubber1Duck

**Comment by Rubber1Duck** [comment]
> But also a shoutout to @Rubber1Duck for his contributions!

You're welcome

**Comment by Rubber1Duck** [comment]
> Oh i forgot, thank you @Rubber1Duck

Thanks you too
