### ISSUE TITLE
Extremely slow

### ISSUE THREAD

**Issue by Friedi1970** [marlon360/rki-covid-api#387]
It seems there is again a problem with the server. The responsive time is extremely high.
Example: https://api.corona-zahlen.org/districts/09180

It really seems there is no access and sometimes I get a timeout.

**Comment by Friedi1970** [comment]
@marlon360 would it be possible to restart the server?

**Comment by Rubber1Duck** [comment]
I dont think that this is a server issue because my own server is responding slow this morning, too! maybe a RKI Data issue, or a RKI server issue!

**Comment by Rubber1Duck** [comment]
this is solved i think... close this issue
