### ISSUE TITLE
Response of /germany EP throws an invalid url error

### ISSUE THREAD

**Issue by Toni-99** [marlon360/rki-covid-api#388]
Response: 

    "error": {
        "message": "There is a problem with the official RKI API.",
        "rkiError": {
            "code": 400,
            "message": "Invalid URL",
            "details": [
                "Invalid URL"
            ]
        },
        "url": "https://services7.arcgis.com/mOBPykOjAyBO2ZKk/arcgis/rest/services/RKI_COVID19/FeatureServer/0/query?where=NeuerFall IN(1,-1)&objectIds=&time=&resultType=standard&outFields=AnzahlFall,MeldeDatum&returnIdsOnly=false&returnUniqueIdsOnly=false&returnCountOnly=false&returnDistinctValues=false&cacheHint=false&outStatistics=[{\"statisticType\":\"sum\",\"onStatisticField\":\"AnzahlFall\",\"outStatisticFieldName\":\"cases\"},{\"statisticType\":\"max\",\"onStatisticField\":\"MeldeDatum\",\"outStatisticFieldName\":\"date\"}]&having=&resultOffset=&resultRecordCount=&sqlFormat=none&f=json&token="
    }

**Comment by Rubber1Duck** [comment]
it looks like all arcgis pages relevant to this app are currently unavailable! :-(

**Comment by kian1991** [comment]
I think a token is required now...

**Comment by GlaubeKeinemDev** [comment]
I got the same problem.

**Comment by Rubber1Duck** [comment]
Thats not the first time this happens! we have to wait until arcgis has solved this problem!

**Comment by permaMonk** [comment]
Ok. Thx.

**Comment by Rubber1Duck** [comment]
everything is running again ........ close this issue

**Comment by permaMonk** [comment]
It’s seems to be there again. Temporarily hosp=n helps.
