### ISSUE TITLE
Impfstatus symptomatischer Coronafälle

### ISSUE THREAD

**Issue by scrapix** [marlon360/rki-covid-api#390]
Hi, gibt es eine Möglichkeit die Daten zum "Impfstatus symptomatischer Coronafälle" aus den RKI Wochenberichten per API zur Verfügung zu stellen?
z.B. https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Situationsberichte/Wochenbericht/Wochenbericht_2022-02-03.pdf?__blob=publicationFile 

![image](https://user-images.githubusercontent.com/23144020/152564917-3027f8f7-f0cd-4d9c-ac69-c4bda1037a7b.png)

**Comment by Rubber1Duck** [comment]
nichts ist unmöglich ............. aber hier glaube ich schwer zu machen, da es keinen festen Anker gibt an dem man sich orientieren könnte. Sollte es so sein, was natürlich zu prüfen währe, das es immer Tabelle 3 ist währe es vieleicht möglich, aber nur vieleicht, und sollte der Ersteller des PDF sich mal nicht daran halten das es Tabelle 3 ist läuft wieder alles auf einen Fehler ................
Meiner bescheidenen Meinung nach lohnt es nicht den Aufwand zu betreiben, zu unsicher währe das Ergebnis......
Von daher eher NEIN!
Gerne lasse ich mich eines besseren Belehren :-)

**Comment by Rubber1Duck** [comment]
Ich denke das Issue kann geschlossen werden, eine Ausleitung aus einem PDF ist nicht unmöglich aber wie schon gesagt nicht praktikabel ........ sorry
