### ISSUE TITLE
Not the right color code when requesting /map/districts/legend

### ISSUE THREAD

**Issue by GlaubeKeinemDev** [marlon360/rki-covid-api#397]
If you request /map/districts/legend it says you the right color code for incidence range 350-500 is #5D179B but the right color code is #5e189b.

**Comment by Rubber1Duck** [comment]
I am on vacation, and i am not able to verify that, but for my point of view that is Not possible, but there is one way that this could be happend.
The resulting png Image is send With quality 75 and maybe that is the problem, maybe the Kompression Algorithmus is changing the colors a lite bit

**Comment by Rubber1Duck** [comment]
@GlaubeKeinemDev Hi,
i just make some test to verify what you meen.
the colorcode is defined here
https://github.com/marlon360/rki-covid-api/blob/1782abe75f02101251a0b48a46a4f6fc7d4790ae/src/configuration/colors.ts#L94-L98
so for range 350-500 the color should be #5D179B
today the resulting image is
![districts-legend](https://user-images.githubusercontent.com/6493772/155116236-90301178-4ed3-4d07-b08f-1de392ebd8d9.png)
as you can see here the colorcode in that image is #5D179B! [https://imagecolorpicker.com/de](https://imagecolorpicker.com/de)
![2022-02-22 10_44_37-Window](https://user-images.githubusercontent.com/6493772/155116885-44bcdb54-5355-4815-9178-437e385f8dd6.png)

Why do you think the "right" colorcode should be #5e189b ?

What do you meen with "the right colorcode" ?

**Comment by Rubber1Duck** [comment]
@GlaubeKeinemDev  huhu ......

**Comment by Rubber1Duck** [comment]
Okay, no answer since 2022-02-22, think there is no issue ... closing
