### ISSUE TITLE
API liefert keine Daten mehr # u.a. Token Error

### ISSUE THREAD

**Issue by MrNigt** [marlon360/rki-covid-api#399]
Germany:

{"error":{"message":"There is a problem with the official RKI API.","rkiError":{"code":499,"message":"Token Required","messageCode":"GWM_0003","details":["Token Required"]},"url":"https://services7.arcgis.com/mOBPykOjAyBO2ZKk/arcgis/rest/services/RKI_COVID19/FeatureServer/0/query?where=NeuGenesen IN(1,0)&objectIds=&time=&resultType=standard&outFields=AnzahlGenesen,MeldeDatum&returnIdsOnly=false&returnUniqueIdsOnly=false&returnCountOnly=false&returnDistinctValues=false&cacheHint=false&outStatistics=[{\"statisticType\":\"sum\",\"onStatisticField\":\"AnzahlGenesen\",\"outStatisticFieldName\":\"recovered\"},{\"statisticType\":\"max\",\"onStatisticField\":\"MeldeDatum\",\"outStatisticFieldName\":\"date\"}]&having=&resultOffset=&resultRecordCount=&sqlFormat=none&f=json&token="}}

Districts:

{"error":{"message":"An error occurred.","details":"Cannot read properties of undefined (reading 'map')","stack":"TypeError: Cannot read properties of undefined (reading 'map')\n    at /usr/src/app/src/data-requests/districts.ts:89:35\n    at Generator.next (<anonymous>)\n    at fulfilled (/usr/src/app/dist/data-requests/districts.js:5:58)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)"}}

**Comment by JonathanN1203** [comment]
You have to wait until the rki has updated the files

**Comment by MrNigt** [comment]
The Dashboard Data is already updated. Please refer to https://experience.arcgis.com/experience/478220a4c454480e823b17327b2bf1d4

**Comment by neelix82** [comment]
https://arcgis.esri.de/aenderung-des-rki-covid-19-datensatzes/

**Comment by csigritz** [comment]
Is someone doing a fix for this issue?

**Comment by Rubber1Duck** [comment]
I am on vacation, sorry no IDE available.
May be home on next monday.
But i thing Marlon will do the Job.
Or if anyone is able .... do it, Marlon will be happy

**Comment by Rubber1Duck** [comment]
i just stolen the laptop of my wife, installed some tools, and made aquick patch! but i`m not able to test this! dont want to install docker here too!) and maybe she will speak to me tomorrow again.... :-)
anyone willing and able to test branch new_datasource?

**Comment by HappyFr1tz** [comment]
Hi, I still get the error message. Is it intentional that this issue was closed? @marlon360

**Comment by geektoor** [comment]
@HappyFr1tz you sure? Can you check or post your request here as well? Because as far as i can see, all data sources work fine again.

**Comment by HappyFr1tz** [comment]
Now it runs @geektoor

**Comment by JonathanN1203** [comment]
soweit ich das sehen kann, besteht das Problem weiterhin bei der URL  https://api.corona-zahlen.org/districts/07131/history/incidence/7

**Comment by Rubber1Duck** [comment]
reopen Issue because of ongoing problems with some districts/:ags because IdLankreis is now a integer and not a string (i think)

**Comment by geektoor** [comment]
I briefly checked the changes and if i'm not completely wrong, the "MeldeDatum" timestamp seems to be the issue. Instead of messing around with creating a string to calculate the TIMESTAMP, it seems to work fine to just let the database do it:
```
whereParams.push(`MeldeDatum >= TIMESTAMP '${dateString}'`);
```
might be simply changed to:
```
whereParams.push(`MeldeDatum >= CURRENT_TIMESTAMP -'${days}'`);
```
But just take it as a hint, i have no idea about the internals of the rki-api  and might be simply wrong.

**Comment by Rubber1Duck** [comment]
> https://api.corona-zahlen.org/districts/07131/history/incidence/7

hi @JonathanN1203 

> soweit ich das sehen kann, besteht das Problem weiterhin bei der URL https://api.corona-zahlen.org/districts/07131/history/incidence/7

hi @JonathanN1203 this is patched now!

**Comment by JonathanN1203** [comment]
@Rubber1Duck thx

**Comment by cc13com** [comment]
Hi all,

could it be that the docker container isn't updated/patched? I use the container on my own server and run in the following issue if I try to request from this url: `https://api.my-domain.tdl/districts/09564/history/incidence`

```
{"error":{"message":"An error occurred.","details":"Cannot read properties of null (reading 'ags')","stack":"TypeError: Cannot read properties of null (reading 'ags')\n    at /usr/src/app/src/responses/districts.ts:244:21\n    at Generator.next (<anonymous>)\n    at fulfilled (/usr/src/app/dist/responses/districts.js:5:58)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)"}}
```

I pulled the container 5 min ago.

**Comment by JonathanN1203** [comment]
Hi,

I use the newest version of the API on my Server, this is working well https://corona.api.jnebel.de/districts/09564/history/incidence

Do you have restartet your docker container?

**Comment by cc13com** [comment]
Hi @JonathanN1203 

yes I restarted the container. But, I remembered on issue [206](https://github.com/marlon360/rki-covid-api/issues/206) and restarted the container with `-V` option. Now it looks good.

Thanks!

**Comment by Rubber1Duck** [comment]
it is always a good idea to restart the container with the -v option!

i made a alias for me to make it easier

`alias restart-rki='docker-compose -f ~/rki-covid-api/docker-compose.prod.yaml down && docker-compose -f ~/rki-covid-api/docker-compose.prod.yaml pull && docker-compose -f ~/rki-covid-api/docker-compose.prod.yaml up -d -V'`

**Comment by cc13com** [comment]
In this case I'm totally with you. But I started my Grafana Container in the past once with `-V` and run in an issue. Lost most of my dashboard configuration. ;-) Therefore I'm handle it carefully.
