### ISSUE TITLE
Problems with GET requests

### ISSUE THREAD

**Issue by D035136** [marlon360/rki-covid-api#400]
Hi Marlon,
currently we are facing issues when trying to address the following endpoints:
states
germany
districts

Example error message from states:
{"error":{"message":"There is a problem with the official RKI API.","rkiError":{"code":499,"message":"Token Required","messageCode":"GWM_0003","details":["Token Required"]},"url":"https://services7.arcgis.com/mOBPykOjAyBO2ZKk/arcgis/rest/services/RKI_COVID19/FeatureServer/0/query?where=NeuGenesen IN(1,-1)&objectIds=&time=&resultType=standard&outFields=AnzahlGenesen,MeldeDatum,IdBundeland&returnIdsOnly=false&returnUniqueIdsOnly=false&returnCountOnly=false&returnDistinctValues=false&cacheHint=false&orderByFields=IdBundesland&groupByFieldsForStatistics=IdBundesland&outStatistics=[{\"statisticType\":\"sum\",\"onStatisticField\":\"AnzahlGenesen\",\"outStatisticFieldName\":\"recovered\"},{\"statisticType\":\"max\",\"onStatisticField\":\"MeldeDatum\",\"outStatisticFieldName\":\"date\"}]&having=&resultOffset=&resultRecordCount=&sqlFormat=none&f=json&token="}}

It seems as if some tokens are missing.
Can this be corrected from your side?

Thanks and regards,
Chris Franz.

**Comment by JonathanN1203** [comment]
Hi Chris,

this is a issue from the rki, we have to wait.

**Comment by HappyFr1tz** [comment]
The same as #399 . I think you could close this issue.

**Comment by Rubber1Duck** [comment]
duplicate, close this issue
