### ISSUE TITLE
Docker is not running anymore

### ISSUE THREAD

**Issue by cabralada** [marlon360/rki-covid-api#414]
I have an issue running Docker in my local and in the server. 
also online is not working: 
url: https://cesarcabral.com/corona/
git: https://github.com/cabralada/corona

This started this week. 

I already try to run local: 
`➜  corona git:(main) docker-compose down && docker-compose pull && docker-compose up -d -V`

but also doesn't work.

Full error:

` => ERROR [7/7] RUN npm run build                                                                                        14.7s
------
 > [7/7] RUN npm run build:
#11 1.017
#11 1.017 > my-app@0.1.0 build
#11 1.017 > next build
#11 1.017
#11 2.474 info  - Using webpack 5. Reason: no custom webpack configuration in next.config.js https://nextjs.org/docs/messages/webpack5
#11 2.721 Attention: Next.js now collects completely anonymous telemetry regarding usage.
#11 2.721 This information is used to shape Next.js' roadmap and prioritize features.
#11 2.721 You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
#11 2.721 https://nextjs.org/telemetry
#11 2.721
#11 2.893 info  - Checking validity of types...
#11 13.56 info  - Creating an optimized production build...
#11 13.99 Browserslist: caniuse-lite is outdated. Please run:
#11 13.99 npx browserslist@latest --update-db
#11 13.99
#11 13.99 Why you should do it regularly:
#11 13.99 https://github.com/browserslist/browserslist#browsers-data-updating
#11 14.59 node:internal/crypto/hash:67
#11 14.59   this[kHandle] = new _Hash(algorithm, xofLen);
#11 14.59                   ^
#11 14.59
#11 14.59 Error: error:0308010C:digital envelope routines::unsupported
#11 14.59     at new Hash (node:internal/crypto/hash:67:19)
#11 14.59     at Object.createHash (node:crypto:135:10)
#11 14.59     at BulkUpdateDecorator.hashFactory (/usr/src/node_modules/next/dist/compiled/webpack/bundle5.js:133790:18)
#11 14.59     at BulkUpdateDecorator.update (/usr/src/node_modules/next/dist/compiled/webpack/bundle5.js:133692:50)
#11 14.59     at /usr/src/node_modules/next/dist/compiled/webpack/bundle5.js:56905:9
#11 14.59     at processTicksAndRejections (node:internal/process/task_queues:83:21)
#11 14.59     at runNextTicks (node:internal/process/task_queues:65:3)
#11 14.59     at processImmediate (node:internal/timers:437:9) {
#11 14.59   opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
#11 14.59   library: 'digital envelope routines',
#11 14.59   reason: 'unsupported',
#11 14.59   code: 'ERR_OSSL_EVP_UNSUPPORTED'
#11 14.59 }
#11 14.59
#11 14.59 Node.js v17.7.1`

➜  corona git:(main) docker -v
`Docker version 20.10.13, build a224086`

➜  corona git:(main) node -v
`v14.17.6`

Thanks

**Comment by marlon360** [comment]
Hello @cabralada,

the issues is not related to the Docker Image of this repository.

The problem occurs in the build process of your Dockerfile. Maybe try running it on Node 16.

**Comment by cabralada** [comment]
Hey @marlon360 ... thanks for the fast reply. 
I did what you said, but still the same issue. 

<img width="893" alt="image" src="https://user-images.githubusercontent.com/1890957/159031355-eda11eec-3fed-4f7b-9cf3-3a6d0f2ca7b0.png">

<img width="895" alt="image" src="https://user-images.githubusercontent.com/1890957/159031280-5e56ec01-a66d-4f49-ba9a-ff8d608efe62.png">

`➜  corona git:(main) node -v
v17.7.2`

**Comment by Rubber1Duck** [comment]
as marlon said, try node V16 ! this should solve that issue!
`nvm install 16.13.0` 
`nvm run 16.13.0`

under Node V17 the same issue is reported! 

and maybe you should ask google with the errormessage (as i just did), google is your friend :-)

**Comment by Rubber1Duck** [comment]
and maybe this
`#11 13.99 Browserslist: caniuse-lite is outdated. Please run:`
`#11 13.99 npx browserslist@latest --update-db`

is also a usefull tip!? but i dont know

**Comment by Rubber1Duck** [comment]
i just found this [here](https://namespaceit.com/blog/error-message-error0308010cdigital-envelope-routinesunsupported) mybe a possible solution for you

If you have this on your package.json - 
```
{
  "scripts": {
    "build": "next build"
  }
}
```
Now change it to -
```
{
  "scripts": {
    "build": "NODE_OPTIONS=--openssl-legacy-provider; next build"
  }
}
```
Now run "npm run build". Hope build will work.

**Comment by cabralada** [comment]
oh, thanks so much!
sorry for the late reply ... I will try this!
