### ISSUE TITLE
Timeseries data is not updated by RKI today (2022-03-19) 

### ISSUE THREAD

**Issue by Rubber1Duck** [marlon360/rki-covid-api#415]
The timeseries data this API uses is not updated today. it is still Datenstand: 18.03.2022 0:00 Uhr ! (should be 19.03.2022 0:00 Uhr)
So many data is the data from yesterday! (e.g. newcases germany)
This applies to all data that access this data source:
[https://services7.arcgis.com/mOBPykOjAyBO2ZKk/arcgis/rest/services/Covid19_hubv/FeatureServer/0/](https://services7.arcgis.com/mOBPykOjAyBO2ZKk/arcgis/rest/services/Covid19_hubv/FeatureServer/0/)
![2022-03-19 19_34_35-Window](https://user-images.githubusercontent.com/6493772/159135904-0e01589d-d92a-4abb-85cf-33da16c09d1e.png)
![2022-03-19 19_41_48-Window](https://user-images.githubusercontent.com/6493772/159136267-9e09f260-10b4-4ba9-812d-abc271f984b7.png)

**Comment by helmar74** [comment]
Yes, same here

**Comment by Rubber1Duck** [comment]
Today 2022-03-20 still not updated!
