### ISSUE TITLE
Nothing Here, Yet

### ISSUE THREAD

**Issue by csigritz** [marlon360/rki-covid-api#418]
Currently the API returns some weird page: "Nothing Here, Yet"
![image](https://user-images.githubusercontent.com/956016/160448396-6f52212f-1d63-43ed-ae13-090fc78ce233.png)

This is for URL [https://api.corona-zahlen.org/states/BY](https://api.corona-zahlen.org/states/BY)

[https://api.corona-zahlen.org/states/JH](https://api.corona-zahlen.org/states/HH) works without problems.

**Comment by marlon360** [comment]
Thanks!

Fixed!
