### ISSUE TITLE
Inkonsistente Daten

### ISSUE THREAD

**Issue by marlon360** [marlon360/rki-covid-api#425]
> Sehr geehrter Herr Lueckert,
> 
> mir ist aufgefallen, dass die Wocheninzidenz unter https://api.corona-zahlen.org/districts/05358 nicht mit der Zahl unter https://api.corona-zahlen.org/districts/ übereinstimmt. Ich würde mich sehr freuen, wenn Sie dies beheben könnten.
> 
> Ich wünsche Ihnen ein frohes Osterfest. Mit freundlichen Grüßen

**Comment by Rubber1Duck** [comment]
My self hosted raspberry has the same and right values in both links!
![2022-04-14 11_31_31-Window](https://user-images.githubusercontent.com/6493772/163382724-6e411078-00db-45c7-a26f-e0184ad23b52.png)

I suspect the Redis cache!

@marlon360  try flushing the redis db!

**Comment by Rubber1Duck** [comment]
@marlon360 did you do something in the meantime? now the data is consistent!

**Comment by Toni-99** [comment]
Es scheint wohl den kompletten /germany Endpunkt zu betreffen. Die Anzahl an neuen Genesenen scheint seit Freitag bei 0 zu sein.

**Comment by Rubber1Duck** [comment]
Hallo Toni-99, hmmm kannst du deine Aussage ein bischen präzisieren? eventuell mit ein paar Bildschirmabzügen, ich kann keine Unregelmässigkeiten finden!

**Comment by stingrayx** [comment]
Hallo Rubber1Duck,

ich kann nicht 100% nachvollziehen was Toni-99 für Probleme anspricht. Aber seit Donnerstag letzte Woche gibt es definitiv einen Unterschied zwischen https://api.corona-zahlen.org/germany und dem Aufruf https://api.corona-zahlen.org/germany/

Verwendet man den Aufruf mit Slash am Ende bekommt man die Daten vom 13. bzw. 14. April! Bis zu diesem Zeitpunkt ist dies nie aufgefallen.

<img width="1133" alt="api_germany_slash" src="https://user-images.githubusercontent.com/44950080/163832777-ee48a18a-aa47-4ce4-802a-64f49ec5eebf.png">

**Comment by Rubber1Duck** [comment]
Hallo stingrayx, okay damit kann ich was anfangen und auch nachvollziehen, ich werde beide fälle mal debuggen und mir ansehen was da passiert!
Auf meinem raspberry gibt es den unterschied nicht! das ist sehr komisch ...
![2022-04-18 18_30_49-Window](https://user-images.githubusercontent.com/6493772/163856597-9c289de2-d371-440a-9e54-ebd37c307d8e.png)
.

**Comment by Rubber1Duck** [comment]
Auch local gehosteter Server im debug Modus sendet bei beiden links das selbe richtige Ergebnis! Beide Links verwenden definitiv die selben Routinen, es sei den es gibt einen gültigen Cache Eintrag, dann wird dieser gesendet, was hier scheinbar der Fall ist!
![2022-04-18 18_43_06-Window](https://user-images.githubusercontent.com/6493772/163858379-5c012532-cd2a-459a-a2eb-43388a537a54.png)

Das lässt eigentlich nur den Schluss zu das es inkonsitenzen im verwendenten Cache gibt! Leider hat Marlon sich noch nicht zu meinem Vorschlag aus posting 
https://github.com/marlon360/rki-covid-api/issues/425#issuecomment-1099095280
geäussert....................
Ich denke ein Neustart des Servers bzw. flushen des caches würde das Problem warscheinlich beheben.
Die Frage die sich natürlich stellt ist wie kommt es zu dieser inkonsistenz ............

**Comment by scharmach** [comment]
Vielleicht ist das hier für die Problembehebung noch hilfreich, denn ich bin ebenfalls auf dieses Problem gestoßen. Ich nutze die API, indem ich die Daten per Node-RED abfrage und in Home Assistant auf einem Rasperry Pi anzeigen lasse.

Mir war aufgefallen, dass sich dabei die Inzidenz für Köln nicht mehr aktualisiert. Schon beim Debuggen in Firefox habe ich dann gesehen, dass der von mir ohne Trailing Slash genutzte Link alte Daten zurückspielt:

https://api.corona-zahlen.org/districts/05315 (`lastCheckedForUpdate "2022-04-19T12:56:12.260Z"`)

![grafik](https://user-images.githubusercontent.com/9080980/165259713-aaa4db3f-4a44-47eb-8fb9-ac814ee4e900.png)

Während ich, dank des Kommentars von @stingrayx, dann mit Trailing Slash feststellen konnte, dass ich plötzlich die aktuellen Daten zurückgeliefert bekomme:

https://api.corona-zahlen.org/districts/05315/ (`lastCheckedForUpdate "2022-04-26T08:35:57.127Z"`)

![grafik](https://user-images.githubusercontent.com/9080980/165260073-ee92cfd2-414c-4597-a1da-e68b33ec2e68.png)

Diese Zahlen stimmen dann auch mit denen des RKI, die die Stadt Köln anzeigt, überein: https://www.stadt-koeln.de/leben-in-koeln/gesundheit/infektionsschutz/corona-virus/corona-virus-koeln-entwicklung-der-fallzahlen

**Comment by Rubber1Duck** [comment]
Interessant in diesem Fall ist es das es genau umgekehrt zum germany endpunkt ist! dort gibt es mit / am ende alte Daten, und ohne aktuelle :-( sehr komisch
da marlon sich nicht meldet nehme ich an das er in verdienten Ferien/Urlaub zu sein scheint .....
@marlon360 please comment ......

**Comment by marlon360** [comment]
This should be fixed now!

@Rubber1Duck If we need to purge the cache in the future to solve those issues, we can click on Actions -> Purge Cache -> Run workflow
