### ISSUE TITLE
Vaccination Endpoint returning error

### ISSUE THREAD

**Issue by marcusraitner** [marlon360/rki-covid-api#427]
since today the following error is returned:

`{"error":{"message":"An error occurred.","details":"Cannot read properties of undefined (reading 'state')","stack":"TypeError: Cannot read properties of undefined (reading 'state')\n    at /workspace/src/data-requests/vaccination.ts:323:15\n    at Generator.next (<anonymous>)\n    at fulfilled (/workspace/dist/data-requests/vaccination.js:5:58)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)"}}`

**Comment by Rubber1Duck** [comment]
The RKI change the stucture of the data source, the parser must be rewritten .....

**Comment by Rubber1Duck** [comment]
To keep the existing data structure of the API we have to switch to the csv data on github (witch is not changed!) and do the extract ourselfs ......... but this needs some time, hopefully finish the work this weekend ...
