### ISSUE TITLE
Vaccination endpoint does not return valid data again.

### ISSUE THREAD

**Issue by icsAT** [marlon360/rki-covid-api#431]
![image](https://user-images.githubusercontent.com/74063738/166400990-b4d1592c-4c82-475e-951b-488105114564.jpeg)

Yesterday you fixed the vaccination endpoint and it worked. This morning it seems, that there is an error again. Could you please check this?

**Comment by Rubber1Duck** [comment]
sorry for that! Yesterday in the evening i put another little patch , and there is something going wrong.
After marlon is approving the new PR all should work fine!
