### ISSUE TITLE
/germany Endpoint is down again

### ISSUE THREAD

**Issue by Toni-99** [marlon360/rki-covid-api#436]
As mentioned in the screenshot. Endpoint is /germany

![image](https://user-images.githubusercontent.com/71496013/168540027-96f21861-f431-4129-a919-7da2f20b25e2.png)

**Comment by csigritz** [comment]
Also districts (https://api.corona-zahlen.org/districts) and states(https://api.corona-zahlen.org/states/BY) are currently having problems

**Comment by Rubber1Duck** [comment]
the issue is that there are no new deaths in the rki database, witch meens the newdeaths = 0!
we have to catch this ...... is in work
