### ISSUE TITLE
Issue with Cache again

### ISSUE THREAD

**Issue by stingrayx** [marlon360/rki-covid-api#439]
Hi,

we have an issue with the cache again obviously like in this issue #425 

This time there is a difference using the districts endpoint with ending slash or without

https://api.corona-zahlen.org/districts shows the data from 16th of May.

Thanks for clearing the cache.

Best regards
Thomas

**Comment by Rubber1Duck** [comment]
should be done.
Have anybody a usefull hint whats the reason is for this inconsistence?

**Comment by Rubber1Duck** [comment]
Wenn keiner einen Tipp hat ... closed
