### ISSUE TITLE
API is broken at the moment

### ISSUE THREAD

**Issue by claaslange** [marlon360/rki-covid-api#440]
Looks like the RKI changed something again in regards to the ArcGIS api:

```
{"error":{"message":"There is a problem with the official RKI API.","rkiError":{"code":499,"message":"Token Required","messageCode":"GWM_0003","details":["Token Required"]},"url":"https://services7.arcgis.com/mOBPykOjAyBO2ZKk/arcgis/rest/services/Covid19_hubv/FeatureServer/0/query?where=NeuGenesen IN(1,-1)&objectIds=&time=&resultType=standard&outFields=AnzahlGenesen,MeldeDatum,IdLandkreis,Datenstand&returnIdsOnly=false&returnUniqueIdsOnly=false&returnCountOnly=false&returnDistinctValues=false&cacheHint=false&orderByFields=IdLandkreis&groupByFieldsForStatistics=IdLandkreis,Datenstand&outStatistics=[{\"statisticType\":\"sum\",\"onStatisticField\":\"AnzahlGenesen\",\"outStatisticFieldName\":\"recovered\"},{\"statisticType\":\"max\",\"onStatisticField\":\"MeldeDatum\",\"outStatisticFieldName\":\"date\"}]&having=&resultOffset=&resultRecordCount=&sqlFormat=none&f=json&token="}}
```
Can be seen at:
https://api.corona-zahlen.org/districts

**Comment by Rubber1Duck** [comment]
As the error message said, there is a Problem with the official RKI api! This meens this api get no data!
Hopefully this is solved by arcgis soon....

**Comment by Rubber1Duck** [comment]
It seems that this issue is fixed!?

**Comment by claaslange** [comment]
Yes, looks like it's working again 👍 last time this token error appeared the ArcGis URL needed to be changed, but this time it looks like only a temporary bug.

**Comment by Rubber1Duck** [comment]
SorryAs the error message said, there is a Problem with the official RKI api! This meens this api gets no data!Hopefully this is solved by arcgis soon....Am 30.05.2022 10:18 schrieb Peter Markewitz ***@***.***>:As tue error messanges said, there is a Problem with the official RKI api! This merns this api getragen no data!Hopefully this is solved by arcgis soon....Am 30.05.2022 09:56 schrieb Claas Lange ***@***.***>:
Looks like the RKI changed something again in regards to the ArcGIS api:
{"error":{"message":"There is a problem with the official RKI API.","rkiError":{"code":499,"message":"Token Required","messageCode":"GWM_0003","details":["Token Required"]},"url":"https://services7.arcgis.com/mOBPykOjAyBO2ZKk/arcgis/rest/services/Covid19_hubv/FeatureServer/0/query?where=NeuGenesen IN(1,-1)&objectIds=&time=&resultType=standard&outFields=AnzahlGenesen,MeldeDatum,IdLandkreis,Datenstand&returnIdsOnly=false&returnUniqueIdsOnly=false&returnCountOnly=false&returnDistinctValues=false&cacheHint=false&orderByFields=IdLandkreis&groupByFieldsForStatistics=IdLandkreis,Datenstand&outStatistics=[{\"statisticType\":\"sum\",\"onStatisticField\":\"AnzahlGenesen\",\"outStatisticFieldName\":\"recovered\"},{\"statisticType\":\"max\",\"onStatisticField\":\"MeldeDatum\",\"outStatisticFieldName\":\"date\"}]&having=&resultOffset=&resultRecordCount=&sqlFormat=none&f=json&token="}}

Can be seen at:
https://api.corona-zahlen.org/districts
