### ISSUE TITLE
Moin,

### ISSUE THREAD

**Issue by icsAT** [marlon360/rki-covid-api#444]
leider sieht es gerade so aus, als würden die Endpoints Germany, State und District nicht funktionieren. 

![image](https://user-images.githubusercontent.com/74063738/172039116-705e9cc7-bd09-48de-876f-011873457008.jpeg)

Danke für Eure Arbeit und schöne Pfingsttage.

**Comment by Rubber1Duck** [comment]
Ich bin über Pfingsten nicht zuhause!
Kann leider nichts machen.

**Comment by Rubber1Duck** [comment]
Aufgrund der Fehlermeldung würde ich aber auf einen Fehler beim RKI tippen. Bzw. den Datahoster dessen Name mir gerade nicht einfällt 😎

**Comment by icsAT** [comment]
Sieht heute wieder gut aus. Also hattest Du mit Deiner Vermutung wohl recht.
