### ISSUE TITLE
Germany and District Endpoint's are not working.

### ISSUE THREAD

**Issue by icsAT** [marlon360/rki-covid-api#445]
Looks pretty much like the same issue than last week [#444](https://github.com/marlon360/rki-covid-api/issues/444).

Where I see a comparison to last week is the fact, that the RKI has f.e. no new cases for Germany. 
I did not had a look at the code, so I do not know wich request you send to the RKI, but the one I am using for new cases in Germany for example will usually return a number. In case of 0 (zero) it will return null, which is not a number.
But this is just one possibility and I am just guessing.

Maybe you have the time and chance to check what causes the problem this time.

Greetings André

**Comment by Rubber1Duck** [comment]
PR is done, and after Marlon reviewed this all should work fine again
