### ISSUE TITLE
Vaccinations Data have changed

### ISSUE THREAD

**Issue by Toni-99** [marlon360/rki-covid-api#450]
The RKI has changed their vaccinations excel file again... Endpoint values (/vaccinations) are not valid anymore

Hier mal die Daten aus der aktuellen Tabelle:
<img width="981" alt="grafik" src="https://user-images.githubusercontent.com/71496013/174985809-f7390a1a-f454-4010-958b-15c27a8f60bf.png">

Und hier die Daten, wie sie bei mir von der API kommen
<img width="504" alt="grafik" src="https://user-images.githubusercontent.com/71496013/174986004-49b9c714-0da4-47d6-8120-eb81e52c7dc2.png">

**Comment by Rubber1Duck** [comment]
Hi Toni-99, can you specify your issue?
This api is not providing the numbers of the excelfile! The data source are the github csv files of the RKI!

**Comment by Rubber1Duck** [comment]
no reaction for over 1 month
