### ISSUE TITLE
Daily delta values too high

### ISSUE THREAD

**Issue by Gisbert1** [marlon360/rki-covid-api#451]
Hi,
the daily delta values are unreasonable high for all states and the republic of Germany.

**Comment by HappyFr1tz** [comment]
What problem do you have @Gisbert1 ? The values:

/germany
"weekIncidence": 532.9034150681755,
"casesPer100k": 33159.25046074482,
"casesPerWeek": 443136,
"delta": {
"cases": 119360,
"deaths": 98,
"recovered": 33547

are correct and were transmitted by the RKI. Those of the federal states are also not unusually high.

**Comment by Gisbert1** [comment]
Hi,
during this day the numbers are again very reasonable. Yesterday, the delta numbers were very different, a thousand times larger. I do not record the readings, therefore I cannot give you a proof.
Regards
Gisbert​

**Comment by HappyFr1tz** [comment]
Yesterday there were also problems with the vaccination data. Perhaps there was a general problem at the RKI. Apparently, the matter was resolved on its own, which is why the issue could be closed.
