### ISSUE TITLE
vaccinations endpoint: Daten der A18+falsch für die 2. Booster Impfung

### ISSUE THREAD

**Issue by stormqueen23** [marlon360/rki-covid-api#453]
Beim endpoint /vaccinations kommen im response unter
['data']['2ndBoosterVaccination']['quotes']['A18+']['A18-A59'] und
['data']['2ndBoosterVaccination']['quotes']['A18+']['A60+]
die selben Daten an.

**Comment by Rubber1Duck** [comment]
fixed
