### ISSUE TITLE
Wrong "last Update" Date since move to new hoster

### ISSUE THREAD

**Issue by helmar74** [marlon360/rki-covid-api#458]
Hi, 

the "lastUpdate" item in the meta  data is showing an old date, since moved to new hoster.
It occurs in germany and in states.
<img width="445" alt="image" src="https://user-images.githubusercontent.com/25499089/184806427-52f8315d-b601-4b44-a90a-ea8489b13805.png">

<img width="477" alt="image" src="https://user-images.githubusercontent.com/25499089/184806482-2a5a4540-1d65-4343-a832-6d3209fb203f.png">

Maybe, it can be corrected some time?

Thanks in advance.

**Comment by Rubber1Duck** [comment]
maybe it is nessessary to purge the redis cache ............ unfortnatly the github action to flush the cache is not working
@marlon360  please have a look on it!

**Comment by csigritz** [comment]
Also weekincidence gives the wrong value. In BY it is far below 739 currently.

**Comment by Rubber1Duck** [comment]
i just saw that Marlon flushed the cache, but the error ist still on... and debug the code.
I dont know why, but the used link to the RKI api witch ist requestiing the states data bring back the wrong data!
deleting one option witch ist not in any other link fixed the error! But why is it running for month or years and now not?
making a patch und PR .............
