### ISSUE TITLE
Wrong font in maps since server change?

### ISSUE THREAD

**Issue by codingcat2468** [marlon360/rki-covid-api#460]
Hi,
there seems to be a little bug in the map endpoint.
Since the server change, the text in:

- [districts-legend](https://api.corona-zahlen.org/map/districts-legend)
- [states-legend](https://api.corona-zahlen.org/map/states-legend)
- [states-legend/hospitalization](https://api.corona-zahlen.org/map/states-legend/hospitalization)

is overlapping and is cut off the image.
It looks like the font has changed.

Here is an image:
![map_text_bug](https://user-images.githubusercontent.com/92219997/185744475-fe3435e2-c515-450e-8583-6cc31fb3aa3a.png)

**Comment by Rubber1Duck** [comment]
on my local own hosted server (Rasberry Pi) the picture is right
![2022-08-20](https://user-images.githubusercontent.com/6493772/185767003-463cdf8e-031c-4d85-b4a1-1906ce0f13b3.png)
i think this must be an issue with the fonts availible on the new server.
@marlon360 is your app now running in the dockercontainer? (because there are the needed fonts installed.....)

**Comment by Rubber1Duck** [comment]
unfortnatly the used patch dont resolve the issue :-(

**Comment by Rubber1Duck** [comment]
@marlon360 Hi Marlon, this is hard for me to understand und to debug! running the actual dockercontainer on serval platforms (windows, linux-amd64 and linux-arm64) dont show this faulty picture!
are you running the app also in the container or do you have a other solution! (maybe running direct without docker, or so on)
if you are running this in a docker envirement can you please run the following comand IN the container (`docker exec -it rki-covid-api /bin/sh`)

`/usr/src/app # fc-match Helvetica`
and
`/usr/src/app # fc-match Arial`

and send the output? thanks

**Comment by marlon360** [comment]
The maps should now display the correct font.

I accidentally started the application in a node container and not the actual Dockerfile.
