### ISSUE TITLE
Vacciniation Response not working anymor due to changed structure in repo

### ISSUE THREAD

**Issue by maurermax** [marlon360/rki-covid-api#465]
When doing a `GET https://api.corona-zahlen.org/vaccinations` an error object is being returned

```
{
  "message": "An error occurred while fetching external data.",
  "url": "https://raw.githubusercontent.com/robert-koch-institut/COVID-19-Impfungen_in_Deutschland/master/.zenodo.json",
  "details": "Request failed with status code 404",
  "response": "404: Not Found"
}
```

seems like this path changed to `https://raw.githubusercontent.com/robert-koch-institut/COVID-19-Impfungen_in_Deutschland/master/Metadaten/zenodo.json` instead

**Comment by codingcat2468** [comment]
[https://api.corona-zahlen.org/germany](https://api.corona-zahlen.org/germany) now also throws a similar error:
```
{
	"error": {
		"message": "An error occurred while fetching external data.",
		"url": "https://raw.githubusercontent.com/robert-koch-institut/COVID-19-Hospitalisierungen_in_Deutschland/master/.zenodo.json",
		"details": "Request failed with status code 404",
		"response": "404: Not Found"
	}
}
```
It seems the structure has changed here also.

**Comment by maurermax** [comment]
created a potential fix here: https://github.com/marlon360/rki-covid-api/pull/466
