### ISSUE TITLE
Errors on States (error #404: Not Found) and Germany (Request failed with status code 500) requests

### ISSUE THREAD

**Issue by MrNigt** [marlon360/rki-covid-api#467]
States error message:

{"error":{"message":"An error occurred while fetching external data.","url":"https://raw.githubusercontent.com/robert-koch-institut/COVID-19-Hospitalisierungen_in_Deutschland/master/.zenodo.json","details":"Request failed with status code 404","response":"404: Not Found"}}

Germany error message:

{"error":{"message":"An error occurred while fetching external data.","url":"https://services7.arcgis.com/mOBPykOjAyBO2ZKk/arcgis/rest/services/Coronafälle_in_den_Bundesländern/FeatureServer/0/query?where=1%3D1&outFields=LAN_ew_EWZ,LAN_ew_AGS,Fallzahl,Aktualisierung,Death,cases7_bl,death7_bl,LAN_ew_GEN&returnGeometry=false&outSR=4326&f=json","details":"Request failed with status code 500","stack":"Error: Request failed with status code 500\n    at createError (/usr/src/app/node_modules/axios/lib/core/createError.js:16:15)\n    at settle (/usr/src/app/node_modules/axios/lib/core/settle.js:17:12)\n    at IncomingMessage.handleStreamEnd (/usr/src/app/node_modules/axios/lib/adapters/http.js:293:11)\n    at IncomingMessage.emit (node:events:539:35)\n    at IncomingMessage.emit (node:domain:537:15)\n    at endReadableNT (node:internal/streams/readable:1345:12)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)"}}

**Comment by marlon360** [comment]
Fixed with #466
