### ISSUE TITLE
Get difference to yesterday also for States and Districts

### ISSUE THREAD

**Issue by stingrayx** [marlon360/rki-covid-api#47]
Hi,

would be great if you could add the difference for States and Districts as well, as it's done for General data. I guess this would imply storing those values also in the DB and calculate it accordingly during insert. Optionally it could be also done by storing the files with a daily date stamp and when reading the newest data in the cronjob, read the old data and calculate it. 

For the last option I have already some code available (in Dart unfortunately, but should be no problem to re-write to JavaScript), which I could share with you.

**Comment by marlon360** [comment]
Have a look here: https://v2.rki.marlon-lueckert.de/docs/endpoints/states.html#states-2
Delta values are now supported in states and districts.

**Comment by stingrayx** [comment]
Thanks a lot!

**Comment by stingrayx** [comment]
V2 is great achievement, only missing point IMHO is the weekIncidence difference to yesterday in the delta block of states and districts. I'm aware about the possibility to calculate it, but this seems a big overhead in terms of network requests and data to be analyzed, compared to providing it straight away.
