### ISSUE TITLE
No data updates on /germany endpoint

### ISSUE THREAD

**Issue by Toni-99** [marlon360/rki-covid-api#475]
idk if this is an RKI issue but there are no new data since the 3rd October. Can you please have a look here? :) 

![grafik](https://user-images.githubusercontent.com/71496013/194027409-91f6078a-ea95-4797-a60b-dd544d1f3595.png)

**Comment by Rubber1Duck** [comment]
i cleaned the redis cache, now the data is actual, lets see if this is solving the issue

**Comment by Rubber1Duck** [comment]
it seems this is solved, closing the issue
