### ISSUE TITLE
RKI killed /germany endpoint again

### ISSUE THREAD

**Issue by Toni-99** [marlon360/rki-covid-api#482]
![image](https://user-images.githubusercontent.com/71496013/201026714-39d3821d-b624-437d-8c53-19a4d649511c.png)

**Comment by Rubber1Duck** [comment]
hopefully this is solved by RKI soon.....

**Comment by DSDV** [comment]
Is there an official Contact? 
Since the CoronaWarnAPP is still working i wonder why the API is going down so often. 
Therefor i would like to open "a ticket" with the official RKI Support team ;)

**Comment by Toni-99** [comment]
@Rubber1Duck Scheint nun alles wieder zu laufen. 

@DSDV nop, working with RKI is like programming in Brainfuck, but badder
