### ISSUE TITLE
Problems with the API

### ISSUE THREAD

**Issue by codingcat2468** [marlon360/rki-covid-api#483]
Hi,
in the last days, I've discovered several problems with the API.
All endpoints return strange values for lastUpdate and lastCheckedForUpdate.
These values are always like **2022-11-24T16:50:30.404Z**. Looks like the server updated a few days ago last time and the responses are loaded from cache.
Also, an app on my phone always shows an JSON parsing error because the API response is an empty string.
The documentations page sometimes returns an error message like this or does not even load:
![Screenshot 2022-11-26 at 12-16-34 api corona-zahlen org 502 Bad gateway](https://user-images.githubusercontent.com/92219997/204086265-5d129d23-3bd2-47ac-b5a4-91d5dd08f283.png)

What could be the reason for this?

**Comment by marlon360** [comment]
Thanks for reporting!

These are the errors in the logs:
> 2022-11-26T12:25:17.882997032Z at Parser.emit (node:events:513:28)
2022-11-26T12:25:17.882990921Z at Parser.<anonymous> (/app/src/data-requests/vaccination.ts:355:31)
2022-11-26T12:25:17.882985470Z TypeError: Cannot read properties of undefined (reading 'total')

**Comment by Rubber1Duck** [comment]
I am still in vaccation, it seems that the vaccination Parser must be rewritten or patched, because the headline of the cvs files  are renamed!
I will be back after 2.Advent only then could I take care of it.
Sorry for that!

**Comment by wagnerand** [comment]
The headers didn't change, but they added 5th and 6th vaccination: https://github.com/robert-koch-institut/COVID-19-Impfungen_in_Deutschland/issues/20

**Comment by codingcat2468** [comment]
Hi,
all endpoints are working again, thanks for fixing!
Looks like the reason was really the vaccination parser that let the app crash.
I just have noticed that a few values in the vaccination endpoint are wrong.
The **quote** property of the 1st vaccination looks strange: 520094.64 and the **vaccinated** property of the secondVaccination is 1941.
Maybe the change in the vaccination parser caused some problems with certain values?

**Comment by foaryon** [comment]
> Hi, all endpoints are working again, thanks for fixing! Looks like the reason was really the vaccination parser that let the app crash. I just have noticed that a few values in the vaccination endpoint are wrong. The **quote** property of the 1st vaccination looks strange: 520094.64 and the **vaccinated** property of the secondVaccination is 1941. Maybe the change in the vaccination parser caused some problems with certain values?

2nd and 4th vaccination not working for me.

**Comment by marlon360** [comment]
The vaccination parser has to be adjusted.. #484
