### ISSUE TITLE
Wrong quote on /vaccinations?

### ISSUE THREAD

**Issue by Toni-99** [marlon360/rki-covid-api#484]
I think, there's something going weirdo O.o

![grafik](https://user-images.githubusercontent.com/71496013/205451361-94e4b111-6997-4017-af67-683b2b152f04.png)

**Comment by marlon360** [comment]
Thanks @Toni-99 for opening the issue!

At the moment the vaccinations are incorrect, because the excel file structure changed.
The parser has to be rewritten.

@Rubber1Duck Can you help fixing this bug?

**Comment by Rubber1Duck** [comment]
Of course I can help!
I m just now back from vacation.
I will rewrite the Parser tomorrow!
