### ISSUE TITLE
Wrong array type on /districts and /states

### ISSUE THREAD

**Issue by Toni-99** [marlon360/rki-covid-api#485]
I dont know since when but for now, we have a json data OBEJCT instead of an Array. That makes it hard for people like me that are using spring to interact with the /districts EP. Can you please change it back to array?

![grafik](https://user-images.githubusercontent.com/71496013/205456940-5375ad84-50e5-4286-a257-88f75707ac5c.png)

**Comment by Toni-99** [comment]
I mean in the worst case, I have to add all 400+ districts to my Object wrapper and then get them all via Reflections. I dont want to be that dirty :D

**Comment by marlon360** [comment]
Hey @Toni-99,
we always returned an object to find a district in O(1). So we don't need to iterate over an array to find the district.

Maybe this helps: https://stackoverflow.com/questions/22687771/how-to-convert-jsonobjects-to-jsonarray
