### ISSUE TITLE
New Project 'Corona Charts Deutschland'

### ISSUE THREAD

**Issue by ixkrei-m** [marlon360/rki-covid-api#50]
Hi Marlon,

I build a little project visualizing german corona stats with Charts. The Project involves counts per day as well as counts as total.

https://corona.maximilianhaindl.de
https://github.com/ixkrei-m/rki-ui
https://github.com/ixkrei-m/rki-api

Best regards,
Maxi

**Comment by marlon360** [comment]
Closed with 747211d9ee1e1b8fc1e17ba3817044b34e368801
