### ISSUE TITLE
frozen incidence and map/xxxx/history is not working reply is code 503

### ISSUE THREAD

**Issue by Rubber1Duck** [marlon360/rki-covid-api#501]
@marlon360 i think the api must be restarted! this seems to be happend if many requests are transmitted! e.g. : with a shell script like:
`#!/bin/bash

code deleted
`

 i can reproduce this localy here but i cant find any solution!

**Comment by Rubber1Duck** [comment]
it seems that the RKI restricted the count of request to the excelsheets for fixed incidence, 
working on a sulution!

**Comment by marlon360** [comment]
Did we remove the rate limiter?

Hopefully the IP does not get banned again..

**Comment by Rubber1Duck** [comment]
the rate limiter is still there! 
my ip is not banned and i tested a lot! and i think, because the excelfiles are requested from the RKI WEB site this will not happend. a few days ago that was not a problem, as i said i tested a lot, always without problems but since yesterday it seems the excelfiles cant be requested shortly.  making the request with a browser always works well.
what i not understand is there is not error message, the apiserver just hang up. all requests to the apiserver were no fix incidence values are used are working well, but not where these fix-incidence values are used ?!?!?!?!?

edit: working on a solution where the request to the excelsheets are minimized to once a week, by changeing the redis cache strategie. than this should be solved
