### ISSUE TITLE
An error occurred

### ISSUE THREAD

**Issue by blubbll** [marlon360/rki-covid-api#504]
{"error":{"message":"An error occurred.","details":"Cannot read properties of undefined (reading 'attributes')","stack":"TypeError: Cannot read properties of undefined (reading 'attributes')\n    at /usr/src/app/src/data-requests/germany.ts:71:28\n    at Generator.next (<anonymous>)\n    at fulfilled (/usr/src/app/dist/data-requests/germany.js:5:58)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)"}}

**Comment by goerlich-bz** [comment]
ich bekomme Exception: Request failed for https://api.corona-zahlen.org returned code 499. Truncated server response: {"error":{"message":"There is a problem with the official RKI API.","rkiError":{"code":499,"message":"Token Required","messageCode":"GWM_0003","det...

**Comment by codingcat2468** [comment]
Looks like the RKI API now requires a token?

**Comment by Zawar92** [comment]
Do we require a token now?

**Comment by goerlich-bz** [comment]
apparently "just" for the Covid19_hubv service at the rki arcgis, the other one works just fine.

**Comment by goerlich-bz** [comment]
the rki_key_data_hubv service might be an alternative, at least for recovered and such sums

**Comment by Rubber1Duck** [comment]
This error has happened more than once, and it has always corrected itself after 1 to 2 days. In any case, the underlying tables of the rki api were last updated on 27.2.  between 3:01 and 4:08 am (german time). Let's wait until tomorrow.

**Comment by Rubber1Duck** [comment]
unfortunately the error is still there. could be that the service has been discontinued ........ ?! cant find any information ....

**Comment by Rubber1Duck** [comment]
If the error should still be there tomorrow (2023-03-03), I will create a PR with a different data source!

**Comment by icsAT** [comment]
FYI:
[Bereitstellung der RKI Covid-19 Daten zum Download über den COVID-19 Datenhub endet](https://arcgis.esri.de/bereitstellung-der-rki-covid-19-daten-zum-download-ueber-den-covid-19-datenhub-endet/)

**Comment by Rubber1Duck** [comment]
i am sorry but the Pr is not ready ... thats a lot of work and today i had not so much time, but i am looking forward to finsh the PR tomorrow!

**Comment by Rubber1Duck** [comment]
PR is done. marlon has to review.....
