### ISSUE TITLE
Robert Koch-Institut - rki-covid-api

### ISSUE THREAD

**Issue by otmar-schneider** [marlon360/rki-covid-api#506]
Sehr geehrter Herr Lückert,
ich bin ein Nutzer ihrer o.a. API und war bisher sehr zufrieden damit.
Seit 01.03.2023 habe ich nunmehr keinen ZUgriff mehr auf viele Ihrer Endpinkte.

was kann ich jetzt machen?
gibt es Alternativen?

Danke für Ihre Antwort

**Comment by Rubber1Duck** [comment]
Das RKI (bzw. arcris) hat die Bereitstellung der Hauptdatendatei über eine Api zum 28.2.2023 eingestellt!
bis ersatz beschafft war und alles umprogrammiert hat es ein paar Tage gedauert.
nun sollte aber wieder alles wie vorher laufen, wenn nicht bitte ich um genaue Angabe welche Endpunkt nicht funktionieren!

**Comment by otmar-schneider** [comment]
Danke für die schnelle Antwort..
Nach wie vor funktionieren folgende Endpunkte immer noch nicht:

https://api.corona-zahlen.org/germany/                                    // Token Required
https://api.corona-zahlen.org/germany/history/cases/7/          // Token Required
https://api.corona-zahlen.org/germany/history/incidence/8/   // Token Required
https://api.corona-zahlen.org/germany/history/incidence        // Token Required
https://api.corona-zahlen.org/districts/09780/                          // Token Required   
https://api.corona-zahlen.org/districts/08317/                          // Token Required  
https://api.corona-zahlen.org/districts/01058/                          // Token Required   
https://api.corona-zahlen.org/states/                                        // Token Required   

Danke für Ihre Mühe

**Comment by Rubber1Duck** [comment]
hmmm gerade mit firefox https://api.corona-zahlen.org/germany/ aufgerufen
![germany](https://user-images.githubusercontent.com/6493772/223566240-ffb738a7-8929-4738-b552-eaf78bd35762.png)
auch alle anderen funktionieren !
Browsercache leeren?

**Comment by otmar-schneider** [comment]
Browser Cache natürlich geleert.. 
im benutze den Google Chrome Browser..
..weder direkt im Browser noch bei meinen PHP aufrufen immer JSON Response mit "Token Required"

**Comment by otmar-schneider** [comment]
![google](https://user-images.githubusercontent.com/127237502/223571289-73be14c8-25ad-46b3-b906-60c9b1ebe464.png)

**Comment by otmar-schneider** [comment]
DANKE sehr

funktioniert alles wieder !!!!
