### ISSUE TITLE
Provide timeseries/historical data

### ISSUE THREAD

**Issue by beyerleinf** [marlon360/rki-covid-api#51]
Do you plan on creating endpoints for historical data?

**Comment by marlon360** [comment]
It is planned for V2 of this API:
https://v2.rki.marlon-lueckert.de/germany/history/cases

**Comment by beyerleinf** [comment]
Nice! :partying_face: Will these also be available for states? :)

**Comment by marlon360** [comment]
Yes, history will be available for states and districts.
Here is a list of all endpoints: https://v2.rki.marlon-lueckert.de/

Documentation will follow.

**Comment by ChristophKrause** [comment]
thank you very much, I wa slooking for this for some time. 
I am curious how this data differs from the JHU data.

**Comment by beyerleinf** [comment]
@marlon360 If I can help with any development, you can hit me up if you want. I'd love to help :)

**Comment by CodeBrauer** [comment]
I would also love to have a parameter for the maps, to see the map of a specific date.

**Comment by marlon360** [comment]
Closed with v2
