### ISSUE TITLE
Endpoints ERROR

### ISSUE THREAD

**Issue by otmar-schneider** [marlon360/rki-covid-api#510]
Sehr geehrter Herr Lückert,
leider erzeugen nachfolgende Endpoints wieder FEHLER:

https://api.corona-zahlen.org/germany/
https://api.corona-zahlen.org/districts/09780/
https://api.corona-zahlen.org/districts/08317/
https://api.corona-zahlen.org/districts/01058/
https://api.corona-zahlen.org/states/

FEHLER bei allen: error":{"message":"An error occurred.","details":"Cannot read properties of undefined (reading 'weekIncidence')"

MfG
Otmar Schneider

**Comment by Rubber1Duck** [comment]
duplicate see #509 
and solved
