### ISSUE TITLE
Bad Gateway

### ISSUE THREAD

**Issue by otmar-schneider** [marlon360/rki-covid-api#520]
Hallo Herr Lückert,

der Aufruf von 
https://api.corona-zahlen.org/germany
erzeugt einen BAD GATEWAY (siehe Anlage)

Was ist da los?
MfG
![Bad_Gateway](https://user-images.githubusercontent.com/127237502/233108814-f09f75f5-1903-45dd-a4ea-bf3d878d0c24.png)

**Comment by DSDV** [comment]
Kann ich bestätigen ist bei mir leider auch seit einer Woche so und scheint sich diesmal nicht "von selbst" zu legen :/

**Comment by marlon360** [comment]
Der Server crasht dauerhaft durch: `2023-04-20T17:04:09.038825704Z AxiosError: Request failed with status code 404`.
Ich untersuche das mal.

**Comment by marlon360** [comment]
@Rubber1Duck Dieser Request schlägt fehl: https://raw.githubusercontent.com/Rubber1Duck/RD_RKI_COVID19_DATA/master/dataStore/frozen-incidence/frozen-incidence_2023-04-18_BL.json.gz

**Comment by Rubber1Duck** [comment]
bin dabei das zu fixen!

**Comment by Rubber1Duck** [comment]
läuft alles wieder, sorry das es solange gedauert hat, aber ich bin zur Zeit in Urlaub in Suedfrankreich undhabe das Issue erstheute gesehen, und auf dem Laptop meiner Frau waren nicht alle tools etc. installiert, das musste ich zunächst machen, und das dauert halt über LTE.

**Comment by otmar-schneider** [comment]
Danke sehr.. trotz Urlaub....noch gute ErholungGglg --Diese Nachricht wurde von meinem Android Mobiltelefon mit WEB.DE Mail gesendet.Am 20.04.23, 22:30 schrieb Peter Markewitz ***@***.***>:

   
  läuft alles wieder, sorry das es solange gedauert hat, aber ich bin zur Zeit in Urlaub in Suedfrankreich undhabe das Issue erstheute gesehen, und auf dem Laptop meiner Frau waren nicht alle tools etc. installiert, das musste ich zunächst machen, und das dauert halt über LTE.
