### ISSUE TITLE
Vaccination numbers

### ISSUE THREAD

**Issue by pc-coholic** [marlon360/rki-covid-api#54]
Would you be open to also include the current vaccination numbers ("Impfquoten")?

As of right now, they only seem to be available per state and they would need to be parsed out of an excel-sheet: https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Daten/Impfquoten-Tab.html

**Comment by marlon360** [comment]
V2 of this API is in progress and will support vaccination numbers:
https://v2.rki.marlon-lueckert.de/vaccinations

**Comment by pc-coholic** [comment]
Very nice - I somehow missed the v2-branch!

Thanks for all your work!
