### ISSUE TITLE
New cases and deaths for states/districts 

### ISSUE THREAD

**Issue by Akeel1994** [marlon360/rki-covid-api#55]
Hey, 

can you also implement new cases and new deaths for the states and districts? Until now, this data is only available for Germany. 

Best regards, 
Akeel

**Comment by marlon360** [comment]
Hi!

I am working on a v2 of this api with delta values for states and districts.
Have a look here: https://v2.rki.marlon-lueckert.de/states

This will be officially released soon.

**Comment by Akeel1994** [comment]
> Hi!
> 
> I am working on a v2 of this api with delta values for states and districts.
> Have a look here: https://v2.rki.marlon-lueckert.de/states
> 
> This will be officially released soon.

Thanks for the fast response! That's nice!  Can you also implement the development for the weekincidence which shows if the incidene is increasing or decreasing compared to the last day? You could implement it for general, too.

**Comment by marlon360** [comment]
Good idea!
At them moment you could calculate it yourself with the history data: https://v2.rki.marlon-lueckert.de/states/history/cases

**Comment by Akeel1994** [comment]
> Good idea!
> At them moment you could calculate it yourself with the history data: https://v2.rki.marlon-lueckert.de/states/history/cases
Yeah, we are already calculating the missing values in our app which is in development. But we haven't known about the history data, So we saved the data of a current day in a database and calculated the missing values with the next day at the moment. But with this way we have the problem that the user only sees the values after the second data update. 
Your v2 will make this better and more user friendly. Thanks!

**Comment by marlon360** [comment]
The problem with saving the current data in a database is that the data of the last days gets updated by RKI everyday. Which means that the data in the database is incorrect when the RKI publishes the latest data.

**Comment by Akeel1994** [comment]
> The problem with saving the current data in a database is that the data of the last days gets updated by RKI everyday. Which  means that the data in the database is incorrect when the RKI publishes the latest data.

Good to know! Yeah, we are saving the data only for the calculation at the moment. But we have to rework it when you release the updated apis.

**Comment by marlon360** [comment]
Closed with v2
