### ISSUE TITLE
Error when getting data by /states endpoint by API

### ISSUE THREAD

**Issue by Maxyandr** [marlon360/rki-covid-api#553]
[https://api.corona-zahlen.org/states](https://api.corona-zahlen.org/states)

error message:

`{
  "error": {
    "message": "An error occurred.",
    "details": "Cannot read properties of undefined (reading 'weekIncidence')",
    "stack": "TypeError: Cannot read properties of undefined (reading 'weekIncidence')\n    at /usr/src/app/src/responses/states.ts:114:6\n    at Array.map (<anonymous>)\n    at /usr/src/app/src/responses/states.ts:107:32\n    at Generator.next (<anonymous>)\n    at fulfilled (/usr/src/app/dist/responses/states.js:5:58)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)"
  }
}`

**Comment by Rubber1Duck** [comment]
Still there?
I dont have any Problems!

If it is solved, please close rhis issue
