### ISSUE TITLE
Twitter bot for vaccination numbers

### ISSUE THREAD

**Issue by mawalu** [marlon360/rki-covid-api#59]
Thanks for creating this API. I'm using it to run a twitter bot that tweets daily updates on the vaccination process: https://twitter.com/impfstatus

**Comment by ChristophKrause** [comment]
I recommend to add the current percentage.

**Comment by mawalu** [comment]
Yeah I already updated the format. Starting from tomorrow the tweets will look like this:

```
476.959 von 117.000.000 benötigten Impfdosen wurden verimpft.

▓░░░░░░░░░░░░░░░░░░░ ~0.41%
```

The current version was a bit hacky
