### ISSUE TITLE
double field names

### ISSUE THREAD

**Issue by srt10coupe** [marlon360/rki-covid-api#60]
"cases", "deaths", "recovered" are used twice, can you change that in the "delta" to "todayCases", "todayDeaths", "todayRecovered"? then it's easier to parse the api.

**Comment by beyerleinf** [comment]
Seems like an odd request to me? What problem do you encounter currently?

**Comment by srt10coupe** [comment]
![Screenshot_20210115-202137](https://user-images.githubusercontent.com/399997/104769401-8d631780-576f-11eb-96f9-695472cb8d2a.png)

Cases and deaths appear twice in the response, which causes difficulties during parsing and output.
 Hence the change suggested above.

**Comment by marlon360** [comment]
Hey @srt10coupe!

I think the change is not necessary. I suggest using a JSON Parser to read the response. Parsing by text is not a good method.
