### ISSUE TITLE
Vaccination-data: time series / historic data should be available 

### ISSUE THREAD

**Issue by shinebar1001** [marlon360/rki-covid-api#62]
Hi Marlon,
great project, thank you very much! 
I would propose to add a historic endpoint to the vaccination data, because it is changing after being published quite often because of "Nachmeldungen". I noticed my statistics differ from the one at RKI over time and now started to parse sheet #3 on their Excel-Sheet and updating all my data for the nationwide vaccination statistics once per day. Unfortunately, there seems to be no such mimic for the single states. For the states with special interest for myself I calculated the delta by hand, but this seems to be quite unreliable (I can't believe that the day with most vaccinations in HH has been a saturday, even if the data from RKI says so). 
best regards
Danny

**Comment by marlon360** [comment]
Hi @shinebar1001 

I added this endpoint: https://api.corona-zahlen.org/vaccinations/history

This endpoints responds with an array of dates and the number of vaccinated people in Germany.
History on a state basis is not available.

**Comment by shinebar1001** [comment]
Great, thank you very much!
