### ISSUE TITLE
repeatedly got a CERTIFICATE_VERIFY_FAILED error

### ISSUE THREAD

**Issue by thebino** [marlon360/rki-covid-api#66]
In the last days, a **CERTIFICATE_VERIFY_FAILED** error appeared recurrent. Is there something wrong with the lets encrypt bot configuration or is it triggered manually instead of a cronjob?

**Comment by EmiHermes** [comment]
I have the same problem.

I tried with.....

_import ssl
[...]
context = ssl._create_unverified_context()
urllib.urlopen(url, context=context)_


But it still gets the error.
However, in the last hours I got a new error:
"**urllib.error.HTTPError: HTTP Error 503: Service Temporarily Unavailable**"

I hope that the problem is being fixed, isn't it?

**Comment by Akeel1994** [comment]
@marlon360 
We have the same errors which are described here. 
When  accessing the API from our app, we are not getting any data. We get the error CERTIFICATE_VERIFY_FAILED. 
When I try to access the api with my pc browser, I am also getting the error 503: Service Temporarily Unavailable.

**Comment by LupusArgentum** [comment]
There is still an issue with the SSL certificate on api.corona-zahlen.org. When will this be fixed?

**Comment by marlon360** [comment]
I had to take it offline for today.
The RKI API responds with errors on some endpoints.
This causes a bypass of the caching system which leads to many requests to the RKI API.
Last time this happened my IP got blocked by their server. To prevent this to happen again, I have to add an error handler that caches the error.

This API gets 6 million hits per day, which looks like a DDoS attack if not cached correctly.

This endpoint for example responds with a time out error:
https://services7.arcgis.com/mOBPykOjAyBO2ZKk/arcgis/rest/services/RKI_COVID19/FeatureServer/0/query?where=NeuGenesen+IN(1,0)&objectIds=&time=&resultType=standard&outFields=AnzahlGenesen,MeldeDatum,IdBundeland&returnIdsOnly=false&returnUniqueIdsOnly=false&returnCountOnly=false&returnDistinctValues=false&cacheHint=false&orderByFields=IdBundesland&groupByFieldsForStatistics=IdBundesland&outStatistics=[{%22statisticType%22:%22sum%22,%22onStatisticField%22:%22AnzahlGenesen%22,%22outStatisticFieldName%22:%22recovered%22},{%22statisticType%22:%22max%22,%22onStatisticField%22:%22MeldeDatum%22,%22outStatisticFieldName%22:%22date%22}]&having=&resultOffset=&resultRecordCount=&sqlFormat=none&f=pjson&token=

**Comment by marlon360** [comment]
The RKI fixed their API and this server is back online.
I added error handling. When the RKI API has problems you will receive a response like this:
```json
{
  "error": {
    "message": "There is a problem with the official RKI API.",
    "rkiError": {
      "code": 503,
      "message": "Timeout Error",
      "details": []
    },
    "url": "https://services7.arcgis.com/mOBPykOjAyBO2ZKk/arcgis/rest/services/RKI_COVID19/FeatureServer/0/query?where=NeuGenesen IN(1,0,-9) AND MeldeDatum &gt;= TIMESTAMP '2021-01-11' AND IdBundesland = 2&amp;objectIds=&amp;time=&amp;resultType=standard&amp;outFields=AnzahlGenesen,MeldeDatum,Bundesland,IdBundesland&amp;returnIdsOnly=false&amp;returnUniqueIdsOnly=false&amp;returnCountOnly=false&amp;returnDistinctValues=false&amp;cacheHint=false&amp;orderByFields=IdBundesland,MeldeDatum&amp;groupByFieldsForStatistics=IdBundesland,MeldeDatum,Bundesland&amp;outStatistics=[{\"statisticType\":\"sum\",\"onStatisticField\":\"AnzahlGenesen\",\"outStatisticFieldName\":\"recovered\"}]&amp;having=&amp;resultOffset=&amp;resultRecordCount=&amp;sqlFormat=none&amp;f=pjson&amp;token="
  }
}
```
