### ISSUE TITLE
Docker Image for Raspberry Pi possible?

### ISSUE THREAD

**Issue by Rubber1Duck** [marlon360/rki-covid-api#67]
Hello,
as in Headline written ........... is it possible to make that Docker Image compatible to Raspberry Pi? i tried to build this but there are many Errors in the build, and I'm not able to fix this ................ but maybe someone else are able to?

**Comment by marlon360** [comment]
You can change the image in the Dockerfile to a ARM-compatible node image.
Unfortunately I cannot test it, but please feel free to share your experiences here.

**Comment by Rubber1Duck** [comment]
I tried this already, but this runs in a error ....
will do this one more time tomorrow and post the error then!

**Comment by Rubber1Duck** [comment]
Running on a Raspberry Pi 4 on Ubuntu 20.04 Server with arm64 Arch!
Setting the node image to "arm64v8/node:12" , the build process run into following Error:
ubuntu@ubuntu:~/rki-covid-api$ docker build -t "rki-covid-api:v2" .
Sending build context to Docker daemon  12.16MB
Step 1/9 : FROM arm64v8/node:12
 ---> 494e69e5dfc3
Step 2/9 : WORKDIR /usr/src/app
 ---> Using cache
 ---> 38b804f4fe3a
Step 3/9 : COPY package*.json ./
 ---> Using cache
 ---> 7ebd3aa04658
Step 4/9 : RUN npm install
 ---> Running in 620a25ecf0a6

> sharp@0.27.0 install /usr/src/app/node_modules/sharp
> (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)

ERR! sharp Use with glibc 2.24 requires manual installation of libvips >= 8.10.5
info sharp Attempting to build from source via node-gyp but this may fail due to the above error
info sharp Please see https://sharp.pixelplumbing.com/install for required dependencies
make: Entering directory '/usr/src/app/node_modules/sharp/build'
  CC(target) Release/obj.target/nothing/../node-addon-api/nothing.o
  AR(target) Release/obj.target/../node-addon-api/nothing.a
  COPY Release/nothing.a
  TOUCH Release/obj.target/libvips-cpp.stamp
  CXX(target) Release/obj.target/sharp/src/common.o
../src/common.cc:24:22: fatal error: vips/vips8: No such file or directory
 #include <vips/vips8>
                      ^
compilation terminated.
sharp.target.mk:139: recipe for target 'Release/obj.target/sharp/src/common.o' failed
make: Leaving directory '/usr/src/app/node_modules/sharp/build'
make: *** [Release/obj.target/sharp/src/common.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
gyp ERR! System Linux 5.4.0-1026-raspi
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/src/app/node_modules/sharp
gyp ERR! node -v v12.20.1
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
npm WARN rki-server@1.0.0 No description
npm WARN rki-server@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/webpack-dev-server/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/watchpack-chokidar2/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/@vuepress/core/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sharp@0.27.0 install: `(node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sharp@0.27.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-01-18T14_44_23_580Z-debug.log
The command '/bin/sh -c npm install' returned a non-zero code: 1

I have absolutly no idea how to fix this!
Anyone able to help?

**Comment by shinebar1001** [comment]
It's stated in the error message: libvips >= 8.10.5 is missing. Unfortunately 8.10 is quite new. You could try to install a version from here: https://pkgs.org/download/libvips (you have to use the debian sid ones)

**Comment by Rubber1Duck** [comment]
> 
> 
> It's stated in the error message: libvips >= 8.10.5 is missing. Unfortunately 8.10 is quite new. You could try to install a version from here: https://pkgs.org/download/libvips (you have to use the debian sid ones)

Hello shinebar1001,
i compiled libvips from source in Version 8.10.5 but this ends in the same Error as above .....

I'm a bloody newbee in Docker ............. and i not realy know whats going on there ... but i think it is not enough to install this libary in the OS ............ this Error is in the Docker build prozess, but, as i said ... i'm a bloody newwbee ..............

**Comment by Rubber1Duck** [comment]
when building for AMD64 at the same point the following happens:

Step 4/9 : RUN npm install
 ---> Running in 22a42b82c031

> sharp@0.27.0 install /usr/src/app/node_modules/sharp
> (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)

info sharp Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.10.5/libvips-8.10.5-linux-x64.tar.br

why not for arm64? At the same location libvips-8.10.5-linux-arm64v8.tar.br exists.

maybe only another FROM node:12  package is needed, but which one ?

**Comment by aeff81** [comment]
Hi!
I've got the container running on Raspbian 10 without sharp.
As far as I understood, sharp is a graphics library, needed for creating maps or something; at least nothing I'm interested in.
It's a really dirty hack. I just commented out everything that mentiones sharp. 
I could post a "git diff" of my copy. But this thing is so nasty that I'm afraid to show it to somebody; but you can just try "fgrep -Ri sharp" yourself. :-)

**Comment by Rubber1Duck** [comment]
Hi all,
i have it running under Raspian OS Buster 10 arm64
details: (its running under 64 bit!)
pi@raspberrypi:~ $ uname -a
Linux raspberrypi 5.10.5-v8+ #1392 SMP PREEMPT Sat Jan 9 18:56:30 GMT 2021 aarch64 GNU/Linux
pi@raspberrypi:~ $ cat /etc/os-release                                                                    ^^^^^
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

with the following Dockerfile building the Image is successfully:

```
FROM arm64v8/node:12

# build dependencies
RUN apt-get update && apt-get install -y \
        build-essential \
        autoconf \
        libtool \
        pkg-config \
        curl \
        gettext \
        nasm \
        gtk-doc-tools \
        libffi-dev \
        zlib1g-dev \
        glib2.0 \
        libjpeg-dev \
        libtiff-dev \
        libpng-dev \
        libgif-dev \
        libexpat1-dev \
        libtiff5-dev \
        libgsf-1-dev

# build prefix
ENV DEST /opt

# common build paths and flags
ENV PKG_CONFIG_PATH ${PKG_CONFIG_PATH}:${DEST}/lib/pkgconfig
ENV LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${DEST}/lib
ENV PATH ${PATH}:${DEST}/bin
ENV CPPFLAGS -I${DEST}/include
ENV LDFLAGS -L${DEST}/lib
ENV CFLAGS -O3
ENV CXXFLAGS -O3

# libvips
WORKDIR /tmp

RUN curl -sOL https://github.com/libvips/libvips/releases/download/v8.10.5/vips-8.10.5.tar.gz \
        && tar zxf vips-8.10.5.tar.gz \
        && cd vips-8.10.5 \
        && ./configure --prefix=${DEST} \
        && make \
        && make install \
        && ldconfig

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY package*.json ./

RUN npm install
# If you are building your code for production
# RUN npm ci --only=production

RUN npm install pm2 -g

# Bundle app source
COPY . .

RUN npm run build

EXPOSE 8080
CMD ["pm2-runtime", "dist/server.js", "-i", "-1"]
```

to build a 32 bit image under RaspiOS(32bit) i think you have not more to do as change
`FROM arm64v8/node:12`
to
`FROM arm32v7/node:12`
but i have not tested this yet!

as libvips is compiling from source the build takes a while! (on my Raspberry4 with SSD round about 20-25 minutes (i didn't take the time)

cu
Peter

**Comment by Rubber1Duck** [comment]
Okay, also testet under RaspiOS 32bit
with
`FROM arm32v7/node:12`
all works fine!
Buildtime round about 22 Minutes with my Raspi 4 4GB and my very fast Internet Line!

**Comment by marlon360** [comment]
I can add the Docker files to the build pipeline and publish them at Docker Hub on push.

@Rubber1Duck You can create a PR with the new Docker files if you want to.

**Comment by Rubber1Duck** [comment]
> 
> 
> I can add the Docker files to the build pipeline and publish them at Docker Hub on push.

that would be great thanks

> 
> @Rubber1Duck You can create a PR with the new Docker files if you want to.

I'm not shure how to do that. must that be differnt branches? 
I have only done PRs for simple changes until now, so it would be great if you did that!

**Comment by Rubber1Duck** [comment]
In the meenwhile i have a solution for the Dockerfile that works with every linux architctures linux/amd64 linux/arm64 and linux arm32v7 and not testet but i think linux/arm32v6 should work also ....... (have to search for my old raspberry pi ......)
Now i have to go to the 3rd birthday of my granddauther.
I will do a PR in the evening!
