### ISSUE TITLE
503 Service Temporarily Unavailable

### ISSUE THREAD

**Issue by nimpla** [marlon360/rki-covid-api#68]
Hello,
the nginx server gives "503 Service Temporarily Unavailable" as response.

**Comment by helmar74** [comment]
samehere, when contacting:
https://api.corona-zahlen.org/germany

**Comment by marlon360** [comment]
I had to take it offline for today.
The RKI API responds with errors on some endpoints.
This causes a bypass of the caching system which leads to many requests to the RKI API.
Last time this happened my IP got blocked by their server. To prevent this to happen again, I have to add an error handler that caches the error.

This API gets 6 million hits per day, which looks like a DDoS attack if not cached correctly.

This endpoint for example responds with a time out error:
https://services7.arcgis.com/mOBPykOjAyBO2ZKk/arcgis/rest/services/RKI_COVID19/FeatureServer/0/query?where=NeuGenesen+IN(1,0)&objectIds=&time=&resultType=standard&outFields=AnzahlGenesen,MeldeDatum,IdBundeland&returnIdsOnly=false&returnUniqueIdsOnly=false&returnCountOnly=false&returnDistinctValues=false&cacheHint=false&orderByFields=IdBundesland&groupByFieldsForStatistics=IdBundesland&outStatistics=[{%22statisticType%22:%22sum%22,%22onStatisticField%22:%22AnzahlGenesen%22,%22outStatisticFieldName%22:%22recovered%22},{%22statisticType%22:%22max%22,%22onStatisticField%22:%22MeldeDatum%22,%22outStatisticFieldName%22:%22date%22}]&having=&resultOffset=&resultRecordCount=&sqlFormat=none&f=pjson&token=

**Comment by helmar74** [comment]
> I had to take it offline for today.
> The RKI API responds with errors on some endpoints.
> This causes a bypass of the caching system which leads to many requests to the RKI API.
> Last time this happened my IP got blocked by their server. To prevent this to happen again, I have to add an error handler that caches the error.
> 
> This API gets 6 million hits per day, which looks like a DDoS attack if not cached correctly.
> 
> This endpoint for example responds with a time out error:
> [https://services7.arcgis.com/mOBPykOjAyBO2ZKk/arcgis/rest/services/RKI_COVID19/FeatureServer/0/query?where=NeuGenesen+IN(1,0)&objectIds=&time=&resultType=standard&outFields=AnzahlGenesen,MeldeDatum,IdBundeland&returnIdsOnly=false&returnUniqueIdsOnly=false&returnCountOnly=false&returnDistinctValues=false&cacheHint=false&orderByFields=IdBundesland&groupByFieldsForStatistics=IdBundesland&outStatistics=[{%22statisticType%22:%22sum%22,%22onStatisticField%22:%22AnzahlGenesen%22,%22outStatisticFieldName%22:%22recovered%22},{%22statisticType%22:%22max%22,%22onStatisticField%22:%22MeldeDatum%22,%22outStatisticFieldName%22:%22date%22}]&having=&resultOffset=&resultRecordCount=&sqlFormat=none&f=pjson&token=](https://services7.arcgis.com/mOBPykOjAyBO2ZKk/arcgis/rest/services/RKI_COVID19/FeatureServer/0/query?where=NeuGenesen+IN(1,0)&objectIds=&time=&resultType=standard&outFields=AnzahlGenesen,MeldeDatum,IdBundeland&returnIdsOnly=false&returnUniqueIdsOnly=false&returnCountOnly=false&returnDistinctValues=false&cacheHint=false&orderByFields=IdBundesland&groupByFieldsForStatistics=IdBundesland&outStatistics=%5B%7B%22statisticType%22:%22sum%22,%22onStatisticField%22:%22AnzahlGenesen%22,%22outStatisticFieldName%22:%22recovered%22%7D,%7B%22statisticType%22:%22max%22,%22onStatisticField%22:%22MeldeDatum%22,%22outStatisticFieldName%22:%22date%22%7D%5D&having=&resultOffset=&resultRecordCount=&sqlFormat=none&f=pjson&token=)

Thanks for the info.
Will it be available again tomorrow?

Thank you for your good work 😀

**Comment by marlon360** [comment]
The RKI fixed their API and this server is back online.
I added error handling. When the RKI API has problems you will receive a response like this:
```json
{
  "error": {
    "message": "There is a problem with the official RKI API.",
    "rkiError": {
      "code": 503,
      "message": "Timeout Error",
      "details": []
    },
    "url": "https://services7.arcgis.com/mOBPykOjAyBO2ZKk/arcgis/rest/services/RKI_COVID19/FeatureServer/0/query?where=NeuGenesen IN(1,0,-9) AND MeldeDatum &gt;= TIMESTAMP '2021-01-11' AND IdBundesland = 2&amp;objectIds=&amp;time=&amp;resultType=standard&amp;outFields=AnzahlGenesen,MeldeDatum,Bundesland,IdBundesland&amp;returnIdsOnly=false&amp;returnUniqueIdsOnly=false&amp;returnCountOnly=false&amp;returnDistinctValues=false&amp;cacheHint=false&amp;orderByFields=IdBundesland,MeldeDatum&amp;groupByFieldsForStatistics=IdBundesland,MeldeDatum,Bundesland&amp;outStatistics=[{\"statisticType\":\"sum\",\"onStatisticField\":\"AnzahlGenesen\",\"outStatisticFieldName\":\"recovered\"}]&amp;having=&amp;resultOffset=&amp;resultRecordCount=&amp;sqlFormat=none&amp;f=pjson&amp;token="
  }
}
```
