### ISSUE TITLE
https://api.corona-zahlen.org/vaccinations/history without result!

### ISSUE THREAD

**Issue by Rubber1Duck** [marlon360/rki-covid-api#69]
https://api.corona-zahlen.org/vaccinations/history has a empty result!
(also https://api.corona-zahlen.org/vaccinations!)

{"data":{"history":[]},"meta":{"source":"Robert Koch-Institut","contact":"Marlon Lueckert (m.lueckert@me.com)","info":"https://github.com/marlon360/rki-covid-api","lastUpdate":"2021-01-18T13:56:52.000Z","lastCheckedForUpdate":"2021-01-18T14:57:36.628Z"}}

maybe the underlying Excelsheet has new colums!?

**Comment by shinebar1001** [comment]
> maybe the underlying Excelsheet has new colums!?

Yepp... There are new columns for "Erstimpfung" und "Zweitimpfung" and new columns for the vaccine used.

**Comment by marlon360** [comment]
The structure of the Excel Spreadsheet changed.
The parser has to be rewritten.

**Comment by marlon360** [comment]
I updated the [/vaccinations](https://api.corona-zahlen.org/vaccinations) and [/vaccinations/history](https://api.corona-zahlen.org/vaccinations/history) endpoint.

Now there are more features available, but the old API format is still supported.
Have a look at the docs: https://api.corona-zahlen.org/docs/endpoints/vaccinations.html
