### ISSUE TITLE
History for incidence in Germany

### ISSUE THREAD

**Issue by marlon360** [marlon360/rki-covid-api#70]

**Comment by marlon360** [comment]
Closed with 188c3c2e12a11bedf64d5154c45521e89b22b698

**Comment by Rubber1Duck** [comment]
Hi Marlon,
witch Incidence do you meen? :-)
The one RKI is reporting daily on their Website?
The one that is calculated including the late registration?
Or the one that is calculated from the daily cases (same as on the Website)

mein englisch ist einfach zu schlecht ....
Welche Inzidenz meinst du?
Die die das RKI täglich auf ihrer Webseite veröffentlicht?
Oder die die sich rechnerisch aus den gemeldeten Zahlen ergibt inklusive der Nachmeldungen (für HEUTE stimmt sie mit der Zahl die veröffentlicht wird überein!)
Oder die die nach den täglichen Gesamtdifferenz erechnet werden kann?

Hier mal ein Ausschnitt meiner Tabelle

          | RKI Web  gemeldet |          API               |         Inzidenz 100k                           |
Datum| Fälle     | Todesfälle | Fälle     | Todesfälle |       API | Tabelle  | RKI Web gemeldet |
12.01  | 19.600 |        1.060| 22.382 |          194 | 167,46 | 174,08 | 155,00                  |
13.01  | 25.164 |        1.244| 24.036 |          123 | 162,75 | 172,61 | 151,00                  |
14.01  | 22.368 |        1.113| 20.373 |          101 | 155,78 | 161,21 | 146,00                  |
15.01  | 18.678 |           980| 18.080 |          110 | 148,29 | 153,97 | 139,00                  |
16.01  | 13.882 |           445| 13.129 |            65 | 144,21 | 150,29 | 136,01                  |
17.01  | 7.141   |           214|   6.448 |            14 | 141,81 | 143,85 | 134,41                  |
18.01  | 11.369 |           989|   4.917 |            31 | 131,50 | 142,13 | 131,50                  |

heute hat das RKI für den 18.01.2021 11.369 neue Fälle gemeldet (2. Spalte) die aber nur zu 4917 Fallen dem 18.01. zugeordnet sind (4.Spalte), der Rest verteilt sich auf die Tage davor, das heisst auf der Schnittstelle ändern sich die Fallzahlen auf den Tagen vor gestern täglich.
Die Summen der Fallzahlen sind natürlich gleich!
Nun kann man ja die Inzidenz errechnen aus den Fällen aus der 2. Spalte ist für gestern (18.1. veröffentlicht heute!) 142,13 (Spalte 7).
Oder man errechnet die Inzidenz aus den dynamischen Fallzahlen in Spalte 4 (aus der Schnittstelle), das ergibt für gestern 131,50, Stand heute entspricht das auch genau der Zahl die das RKI veröffentlicht! letzte Spalte.
Gestern hat das RKI für den 17.1. als Inzidenz 134,4 veröffentlicht! (letzte Spalte) heute ist der Wert für den 17.1. aber auf 141,81 angestiegen (6. Spalte), da für den 17.1. , da Fälle von heute und/oder anderen Tagen dazugekommen sind.

Insgesamt kann man sagen das das RKI eher zu optimistische Werte veröffentlicht! Die Inzidenz die sich aus den täglich auf der Webseite veröffentlichen Fallzahlen ergibt ist eigentlich zuerst immer höher, gleicht sich aber mit der Zeit auf die API Zahlen an
Hier mal eine Grafik
![2021-01-19 13_06_51-Microsoft Excel - COVID-19-Germany xlsx](https://user-images.githubusercontent.com/6493772/105032711-6e0e0800-5a57-11eb-9e30-0af9421cb8e7.png)

Letztendlich, meiner bescheidenen Meinung nach, kannst du nur die Inzidenzzahlen aus Spalte 6 nachträglich errechnen, und die ändern sich auch noch täglich! Ich sehe keinen Weg die vom RKI veröffentlichen Zahlen für die Vergangenheit nachzubilden. Du kannst nur heute starten und den Wert täglich extern speichern und dann zur Verfügung stellen. wiegesagt der API Inzidenzwert von heute für heute entspricht diesem Wert. 

Einen nicht wirklich schönen Weg gibt es! Das RKI veröffentlich täglich einen Situationsreport als PDF. In diesen wird seit dem 13.09.2020 auch der Inzidenzwert veröffentlicht! da kann man sich den raussuchen, was ich auch schonmal gemacht habe (händisch) da mal die Exceltabelle durch meine Doofheit gelöscht war) 
Die Werte ab 13.09.2020 kann ich dir gerne zur Verfgung stellen!

Ich hoffe sehr das ich mich verständlich ausgedrückt habe, und sorry für das alles in deutsch, aber in englisch hätte ich das nicht hinbekommen!

**Comment by marlon360** [comment]
Hallo @Rubber1Duck 

Ich nehme immer die aktualisierte Historie, also die historischen Daten, die jeden Tag neu veröffentlicht und aktualisiert werden. Das bedeutet aber auch, dass sich die historischen Inzidenz Werte (genau wie die Fälle) sich im Laufe der Zeit anpassen.

Aus meiner Sicht ergibt diese Berechnung am meisten Sinn, da es sonst zu deutliche höheren inzidenzen kommt, wenn man immer die tägliche Inzidenz speichert.

Außerdem möchte ich aus technischer Sicht es vermeiden, dass eine Datenbank benötigt wird oder dauerhaft Dateien aktualisiert werden müssen. Dadurch ist das Docker-Image stateless und kann von jedem sofort gestartet werden.

**Comment by Rubber1Duck** [comment]
Die Werte aus der VERGANGENHEIT sind immer höher als die vom RKI veröffentlichten! Nur für heute(bzw. eigentlich ist es ja der Wert von gestern), stimmt er mit dem veröffentlichtem Wert überein!
noch ein Beispiel
Daten vom 16.01.
![Data_2021_01-16](https://user-images.githubusercontent.com/6493772/105038494-ad405700-5a5f-11eb-9c89-b106b110c9c1.png)
Was im folgenden Situationsbericht steht wurde auch auf dem Dashboard veröffentlicht!
![RKI_2021_01_16](https://user-images.githubusercontent.com/6493772/105038709-f55f7980-5a5f-11eb-9fd0-3a088c6a39dc.png)
Die ermittelten Werte für die Vergangenheit liegen immer höher als die an dem Tag veröffentlichten, das gilt für alle Werte seit dem 13.09.2020, also alles was mir zur Verfügung steht. Im Mittel liegen die Veröffentlichten Zahlen um fast 10 % niedriger!
Ich verstehe deine Beweggründe, die Frage ist nur, was sind dann die ermittelten Vergangenheitsdaten wert! Die Werte spiegeln natürlich das WIRKLICHE Infektionsgeschehen wieder, werden aber in der Form vom RKI nie veröffentlicht!
Interessant ist, das die heute veröffentlichte Zahl von 131,5 in 8-11 Tagen der entspricht welche sich durch die Errechnung der täglichen Fallzahlen ergibt 142,13 (mit mittlerer Abweichung von 1,22%). Das ist ganz klar in der Tabelle zu beobachten!
Das sind nur meine Gedanken dazu, ich möchte hier nix schlechtreden oder dergleichen, vielen Dank für deine tolle Arbeit an dieser Schnittstelle
VG
Peter
