### ISSUE TITLE
Use of JSON instead of PJSON

### ISSUE THREAD

**Issue by Rubber1Duck** [marlon360/rki-covid-api#72]
during my research, I stumbled upon this website

http://geobern.blogspot.com/2017/02/the-difference-between-json-and-pjson.html

and on this site i found this:

>      If you want the JSON object response to be more readable, you can use pjson. This option should only be used for debugging purposes, since it takes longer to process the response.

in Issue #68 you wrote 

> This API gets 6 million hits per day, which ..............

Maybe it is a good idea to switch to 
=&resultRecordCount=&sqlFormat=none&f=json&token=
instead of
=&resultRecordCount=&sqlFormat=none&f=pjson&token=
in your requests?

This is not a real issue, more a note, and if you have your reasons to do so ................ close it right now :-)

**Comment by marlon360** [comment]
Hello @Rubber1Duck 

Thanks for pointing that out, this was definitely not intended.
Will fix this soon!

Thank you for improving the API!

**Comment by marlon360** [comment]
Fixed with bf7ccc6ab1e37cf64ac70d3e7cbb1bdb1877aad3
