### ISSUE TITLE
Historic data seems to be completely incorrect

### ISSUE THREAD

**Issue by LupusArgentum** [marlon360/rki-covid-api#74]
I was checking the historic data of 7 days in the past, but the numbers don't make any sense to me:
The API shows 11.523 new cases for 21.01.2021, meanwhile the official data of the RKI shows 20.398 new cases for that date.
Same thing with the deaths. Am I understanding it wrong or is there some kind of issue with the API?

**Comment by marlon360** [comment]
https://github.com/marlon360/rki-covid-api/issues/64

**Comment by marlon360** [comment]
Die Neuinfektionen beinhalten alle neuen Fälle, die in den letzten 24h gemeldet wurden.
Da bedeutet aber nicht, dass die Infektionen genau an diesem Tag gemeldet wurden. Es gibt immer Verzögerungen bei der Meldung. Das RKI aktualisiert die Historie jeden Tag rückwirkend.

Wenn man sich also jeden Tag, die Neuinfektionen speichern würde, kommt es zu einer falschen Historie.
