### ISSUE TITLE
Why is there a limit of days for historic district data of 36 or 30 

### ISSUE THREAD

**Issue by Rubber1Duck** [marlon360/rki-covid-api#78]
see Head line......
for example in Function  getLastDistrictCasesHistory there is a limt of 36 days
 ```
if (days != null) {
      days = Math.min(days, 36);
    } else {
      days = 36;
    }
```
or

in Function getLastDistrictDeathsHistory the Limit is 30 days ...

```
if (days != null) {
      days = Math.min(days, 30);
    } else {
      days = 30;
    } 
```

Datarequest , Memory, CPU Power ........ ???

**Comment by marlon360** [comment]
Hello @Rubber1Duck 

the number of maximum records per requested is limited. 
But I still want to offer an endpoint with the history of all districts, so I limited the number of days.
For the full history you can request the district history individually.

This request will not return all records:
https://services7.arcgis.com/mOBPykOjAyBO2ZKk/arcgis/rest/services/RKI_COVID19/FeatureServer/0/query?objectIds=&time=&resultType=standard&outFields=AnzahlFall,MeldeDatum,Landkreis,IdLandkreis&returnIdsOnly=false&returnUniqueIdsOnly=false&returnCountOnly=false&returnDistinctValues=false&cacheHint=false&orderByFields=IdLandkreis,MeldeDatum&groupByFieldsForStatistics=IdLandkreis,MeldeDatum,Landkreis&outStatistics=[{"statisticType":"sum","onStatisticField":"AnzahlFall","outStatisticFieldName":"cases"}]&having=&resultOffset=&resultRecordCount=&sqlFormat=none&f=json&token=

**Comment by Rubber1Duck** [comment]
Thanks for the answer
