### ISSUE TITLE
At https://api.corona-zahlen.org/vaccinations the state of Bavaria has no abbreviation

### ISSUE THREAD

**Issue by Rubber1Duck** [marlon360/rki-covid-api#79]
See here:
![abbreviation](https://user-images.githubusercontent.com/6493772/106067248-956f6f80-60fe-11eb-884c-41c9a632e37e.png)

only the state of Baviaria has no abbreviation!

**Comment by shinebar1001** [comment]
Actually it is "Bavaria * " as RKI had annotations yesterday. I started to filter out any special chars in my script.

**Comment by marlon360** [comment]
Thanks @Rubber1Duck  for pointing that out!
I added a cleanup function for the strings, as @shinebar1001 suggested.

Resolved with a58a9b383133ba4c84c58bd3de18a58311ec9df9
Should be online in a few.
