### ISSUE TITLE
history not updated if new cases = 0 or new deaths =0 or new recovered = 0 for yesterday

### ISSUE THREAD

**Issue by Rubber1Duck** [marlon360/rki-covid-api#82]
For example
[https://api.corona-zahlen.org/districts/05117/history/incidence/7](url)

```
data |  
-- | --
05117 |  
ags | "05117"
name | "Mülheim an der Ruhr"
history |  
0 |  
weekIncidence | 89.08059449575696
date | "2021-01-26T00:00:00.000Z"
1 |  
weekIncidence | 90.83876412396268
date | "2021-01-27T00:00:00.000Z"
2 |  
weekIncidence | 93.18299029490365
date | "2021-01-28T00:00:00.000Z"
3 |  
weekIncidence | 65.63833278634722
date | "2021-01-29T00:00:00.000Z"
meta |  
source | "Robert Koch-Institut"
contact | "Marlon Lueckert (m.lueckert@me.com)"
info | "https://github.com/marlon360/rki-covid-api"
lastUpdate | "2021-01-29T00:00:00.000Z"
lastCheckedForUpdate | "2021-02-02T09:45:11.406Z"
```
It does not matter whether with argument "days" or not
[https://api.corona-zahlen.org/districts/05117/history/incidence/](url)

```
........................................
315 |  
-- | --
weekIncidence | 89.08059449575696
date | "2021-01-26T00:00:00.000Z"
316 |  
weekIncidence | 90.83876412396268
date | "2021-01-27T00:00:00.000Z"
317 |  
weekIncidence | 93.18299029490365
date | "2021-01-28T00:00:00.000Z"
318 |  
weekIncidence | 65.63833278634722
date | "2021-01-29T00:00:00.000Z"
meta |  
source | "Robert Koch-Institut"
contact | "Marlon Lueckert (m.lueckert@me.com)"
info | "https://github.com/marlon360/rki-covid-api"
lastUpdate | "2021-01-29T00:00:00.000Z"
lastCheckedForUpdate | "2021-02-02T10:06:27.631Z"
```
Other Districts are working well

**Comment by marlon360** [comment]
It seems lika a few districts haven’t submitted their data since 29.01.2021.
I believe it is not a server issue.

**Comment by Rubber1Duck** [comment]
> It seems lika a few districts haven’t submitted their data since 29.01.2021.

it seems you are right ....

> I believe it is not a server issue.

but does this not meen (no data submitted) the data is "0" ??? (RKI is taking this days with "0"  to calculate the incidenz! For RKI the sum for cases of the last 7 days for distrikt 055117 is 88 and the inzidenz today is 51,57297576 
![2021_02_02_Muelheim](https://user-images.githubusercontent.com/6493772/106600787-2ad58e00-655b-11eb-9122-eb3b6e73c411.png)

**Comment by marlon360** [comment]
Yes you are right these days should be `0`.
But at the moment it is hard to distinguish between "No data submitted for the days" and "The data has not been updated yet".

So we have to check if any data has been submitted for the day to be sure that we are not assuming `0` cases although the RKI has not updated the data yet. We don't want to deliver wrong number at any time.

**Comment by Rubber1Duck** [comment]
you are right thats a big problem .................

**Comment by Rubber1Duck** [comment]
Maybe it can be the solution to add "Datenstand" to the query(s)!? if this is the date from today the data should be updated by RKI ! 
e.g. like this (this is pjson format for better readability)

`https://services7.arcgis.com/mOBPykOjAyBO2ZKk/arcgis/rest/services/RKI_COVID19/FeatureServer/0/query?where=NeuerFall%20IN(1,0)%20AND%20IdLandkreis=05117&objectIds=&time=&resultType=standard&outFields=AnzahlFall,MeldeDatum,IdLandkreis,Datenstand&returnIdsOnly=false&returnUniqueIdsOnly=false&returnCountOnly=false&returnDistinctValues=false&cacheHint=false&orderByFields=IdLandkreis,MeldeDatum&groupByFieldsForStatistics=Datenstand,IdLandkreis,MeldeDatum,Landkreis&outStatistics=[{%22statisticType%22:%22sum%22,%22onStatisticField%22:%22AnzahlFall%22,%22outStatisticFieldName%22:%22cases%22}]&having=&resultOffset=&resultRecordCount=&sqlFormat=none&f=pjson&token=`

```
 {
      "attributes" : {
        "cases" : 15, 
        "Datenstand" : "02.02.2021, 00:00 Uhr", 
        "IdLandkreis" : "05117", 
        "MeldeDatum" : 1611619200000, 
        "Landkreis" : "SK Mülheim a.d.Ruhr"
      }
    }, 
    {
      "attributes" : {
        "cases" : 22, 
        "Datenstand" : "02.02.2021, 00:00 Uhr", 
        "IdLandkreis" : "05117", 
        "MeldeDatum" : 1611705600000, 
        "Landkreis" : "SK Mülheim a.d.Ruhr"
      }
    }, 
    {
      "attributes" : {
        "cases" : 36, 
        "Datenstand" : "02.02.2021, 00:00 Uhr", 
        "IdLandkreis" : "05117", 
        "MeldeDatum" : 1611792000000, 
        "Landkreis" : "SK Mülheim a.d.Ruhr"
      }
    }, 
    {
      "attributes" : {
        "cases" : 15, 
        "Datenstand" : "02.02.2021, 00:00 Uhr", 
        "IdLandkreis" : "05117", 
        "MeldeDatum" : 1611878400000, 
        "Landkreis" : "SK Mülheim a.d.Ruhr"
```

**Comment by Rubber1Duck** [comment]
today it runs into an error!
[https://api.corona-zahlen.org/districts/05117/history/incidence/7](url)

`{"error":{"message":"An error occurred.","details":"Request failed with status code 502","stack":"Error: Request failed with status code 502\n    at createError (/usr/src/app/node_modules/axios/lib/core/createError.js:16:15)\n    at settle (/usr/src/app/node_modules/axios/lib/core/settle.js:17:12)\n    at IncomingMessage.handleStreamEnd (/usr/src/app/node_modules/axios/lib/adapters/http.js:260:11)\n    at IncomingMessage.emit (events.js:326:22)\n    at IncomingMessage.EventEmitter.emit (domain.js:506:15)\n    at endReadableNT (_stream_readable.js:1241:12)\n    at processTicksAndRejections (internal/process/task_queues.js:84:21)"}}`
