### ISSUE TITLE
Diffrent numbers with arcgis maps/page

### ISSUE THREAD

**Issue by tygore587** [marlon360/rki-covid-api#84]
Hi :) 

Thanks for creating this api. I'm a little bit curious. I was comparing your insidenz of [Ostprignitz-Ruppin](https://api.corona-zahlen.org/districts/12068) with the values of [arcgis](https://www.arcgis.com/apps/webappviewer/index.html?id=129c0cb80f5e4f6c88a75a02d6a28b92) and your value was way lower. (In the time of writing: your weekIncidence was 166.901 and arcgis reported 194,2) I'm just curious if you know why there is so much diffrence between these numbers.

As an example potsdam is almost the same:

[Your api](https://api.corona-zahlen.org/districts/12054):
![image](https://user-images.githubusercontent.com/12038641/106935910-3ae89b80-671c-11eb-9815-e20a8cc9d131.png)

[Arcgis](https://experience.arcgis.com/experience/331f51a39f3046208f355412190cb57b)
![image](https://user-images.githubusercontent.com/12038641/106936089-6e2b2a80-671c-11eb-9e92-06d50b0a3d8e.png)

Have a great day,
Tygore

**Comment by marlon360** [comment]
Hello @tygore587 

My API uses the data provided by the RKI.
Your [link](https://www.arcgis.com/apps/webappviewer/index.html?id=129c0cb80f5e4f6c88a75a02d6a28b92) shows the numbers directly reported by the corresponding health department.
In general the data of the RKI is not as up-to-date compared to data from the health departments.

This API corresponds to the data from this RKI dashboard: [https://experience.arcgis.com/experience/478220a4c454480e823b17327b2bf1d4](https://experience.arcgis.com/experience/478220a4c454480e823b17327b2bf1d4)
