### ISSUE TITLE
Second vaccination delta wrong?

### ISSUE THREAD

**Issue by kaolick** [marlon360/rki-covid-api#88]
First of all thank you very much for creating this awesome API!!!

Now to the issue:

It seems that for a few days now the delta value of second vaccinations is wrong. It's almost as high as the total value of second vaccinations.

Here an example from today (07.02.2021):

`"secondVaccination": {
            "vaccinated": 903271,
            "delta": 903263
        },`

Best regards,
kaolick

**Comment by Rubber1Duck** [comment]
see #85 , Patch is ready to merge #87.
Marlon has to do that!
cu
Peter
