### ISSUE TITLE
App Infektionsgeschehen 

### ISSUE THREAD

**Issue by Akeel1994** [marlon360/rki-covid-api#89]
Hey, 

our new app which is based on your API is now online: 
https://play.google.com/store/apps/details?id=de.geekbits.infektionsgeschehen 

Thank you for your work! 

Best regards, 
Akeel

**Comment by Rubber1Duck** [comment]
see #85 .
Patch is ready, RP is written ........... , Marlon has to do the merge ....

**Comment by Akeel1994** [comment]
Hey Peter,


I just created this issue so Marlon can list the app which is based on his API. So it's not really an issue.

**Comment by Rubber1Duck** [comment]
I want to write a comment to the other Issue, just deleted my commetn, sorry!
