### ISSUE TITLE
wrong value for secondVaccination.vaccinated

### ISSUE THREAD

**Issue by Akeel1994** [marlon360/rki-covid-api#90]
Hey, 

our app is not getting the vaccination data anymore because the value of secondVaccination.vaccinated changed to datatype double. The value is currently 2.8193996994783164 which makes no sense for this variable.

**Comment by marlon360** [comment]
Thank for pointing that out!
The RKI added „AstraZeneca“ which messes with the table structure..

**Comment by Akeel1994** [comment]
Yeah, I have already thought that they changed the structure again.
I hope they don't change the structure so often :D

**Comment by marlon360** [comment]
Fixed with 6701739ec6ddcada8e9939ab88c7660fa167edcc.
Should be deployed in a few minutes!

I hope they keep the structure, but I don't believe it :D
