### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by thebino** [marlon360/rki-covid-api#92]
The nginx server responses with "502 Bad Gateway"

**Comment by marlon360** [comment]
Thanks for reporting this issue!
Should be fixed now, please reopen the issue if you still have problems reaching the server.

**Comment by thebino** [comment]
@marlon360 This issue is still / again raised:
https://api.corona-zahlen.org/districts

P.S.: re-open is restricted

**Comment by gebripe** [comment]
I think I'm having the same issue. 

It drives me mad that I'm having "NaN" being displayed in my Home Assistant for weekly incidence and was about to blame @thebino and decided to look for an RKI API myself. 

I just then realized that it is this API that was spitting 502's when I tried it "manually" in a browser (most recent Firefox). It went away when trying again a couple of times (URL: https://api.corona-zahlen.org/districts/03360 ).

Seems that it happens too when Home Assistent is requesting the URL, resulting in bad / NaN numbers, both when doing a REST call in the HA config myself and apparently also for the @thebino integration.

**Comment by gebripe** [comment]
I know this is specific to Home Assistant, but I thought I'd include it in case it might help nailing down the issue:

**configuration.yaml:**
```
  - platform: rest
    name: rest_rki
    resource: https://api.corona-zahlen.org/districts/03360
```
**Result:**
```
<template TemplateState(<state sensor.rest_rki=<html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.19.3</center>
</body>
</html>
; friendly_name=rest_rki @ 2021-02-13T16:16:50.215009+01:00>)>
```

**Comment by Rubber1Duck** [comment]
my raspberry pi with this Dockerimage "läuft wie ein Döppchen" :-) no 502 Errors......... but this have only to answer my requests ...............

**Comment by marlon360** [comment]
My server needs more optimizations for this extreme high traffic.
It has a cpu usage of 99%. I believe the problem has something to do with how I queue the request when the cache is invalid.

I would not recommend to rely on my server for your applications. If you have the chance, try to host it yourself.

**Comment by rolandsteinmeyer** [comment]
Would be easier to self-host if docker-compose.yml v2 was given so it can be deployed with portainer.

**Comment by marlon360** [comment]
@rolandsteinmeyer 
Here are the instructions on how to self-host this API: https://api.corona-zahlen.org/docs/#host-it-yourself

**Comment by rolandsteinmeyer** [comment]
yes, but your provided docker-compose.yml it uses version: "3.8" so you have to use cli instead of more user-friendly portainer gui, which is a steep learning curve for docker noobs like me.

**Comment by marlon360** [comment]
@rolandsteinmeyer 
I didn't know about portainer. But it seems that portainer itself is docker container you have to start. So starting this API or the portainer application should be the same procedure.

I tested the online portainer version and I managed to import a stack from the docker-compose. Maybe you can try that again.

**Comment by rolandsteinmeyer** [comment]
It seems you need to have swarms set up to use v3 docker-compose.yml with portainer.  I have used docker-compose on cli now. Container is running but can not be manged with portainer this way. Will try to resolve this myself since it is not a problem with this project.
Edit: Solved  with portainer update 2.1.1.

**Comment by marlon360** [comment]
What's the status with this issues?

@thebino @gebripe Are you still experiencing issues?
 I haven't changed anything, but maybe the issue resolved by itself 😄

**Comment by thebino** [comment]
I'm fine, looks like communication is back to normal.

**Comment by marlon360** [comment]
Great! Closing this for now.

**Comment by gebripe** [comment]
Well, unfortunately, I've had the issue the last four days again. What I really can't understand is that a re-install of the integration helps, but is no guarantee, 

![grafik](https://user-images.githubusercontent.com/76658951/109402849-7a8c5700-7959-11eb-9046-ceec60d36fb4.png)
